### ISSUE TITLE
Trying to do development on Windows and getting an error about win32ctypes not found

### ISSUE THREAD

**Issue by alexschneider** [gpodder/gpodder#1022]
Hi All,

I'm trying to hack on gpodder to add a feature I care about, but it seems like there's no way to get it to run on Windows using the instructions in https://github.com/gpodder/gpodder/blob/master/tools/win_installer/README.rst.

What I've done:

1. Downloaded and installed MSYS2
2. Run MINGW 32 terminal
3. `pacman -Syu`
4. `./tools/win_installer/bootstrap.sh`
5. `python tools/localdepends.py`
6. `bin/gpodder` or `bin/gpo` both return the same error message:

```
Alex Schneider@DESKTOP-RKKBOMT MINGW32 ~/gpodder
$ bin/gpo
Traceback (most recent call last):
  File "bin/gpo", line 134, in <module>
    import gpodder  # isort:skip
  File "C:/msys64/home/Alex Schneider/gpodder/src/gpodder/__init__.py", line 218, in <module>
    default_home = fixup_home(default_home)
  File "C:/msys64/home/Alex Schneider/gpodder/src/gpodder/__init__.py", line 188, in fixup_home
    from gpodder.utilwin32ctypes import (
  File "C:/msys64/home/Alex Schneider/gpodder/src/gpodder/utilwin32ctypes.py", line 27, in <module>
    from win32ctypes.core.ctypes._util import check_zero, function_factory
ModuleNotFoundError: No module named 'win32ctypes'

Alex Schneider@DESKTOP-RKKBOMT MINGW32 ~/gpodder
$ bin/gpodder

    Warning: python-dbus not found. Disabling D-Bus support.

Traceback (most recent call last):
  File "bin/gpodder", line 166, in <module>
    main()
  File "bin/gpodder", line 81, in main
    import gpodder  # isort:skip
  File "C:/msys64/home/Alex Schneider/gpodder/src/gpodder/__init__.py", line 218, in <module>
    default_home = fixup_home(default_home)
  File "C:/msys64/home/Alex Schneider/gpodder/src/gpodder/__init__.py", line 188, in fixup_home
    from gpodder.utilwin32ctypes import (
  File "C:/msys64/home/Alex Schneider/gpodder/src/gpodder/utilwin32ctypes.py", line 27, in <module>
    from win32ctypes.core.ctypes._util import check_zero, function_factory
ModuleNotFoundError: No module named 'win32ctypes'
```

I checked to make sure that `python` uses the mingw python path

```
$ python --help
usage: C:\msys64\mingw32\bin\python.exe ...
(cut for terseness)
```

Google searches for `win32ctypes` turn up nothing useful or with a similar error message. I'm out of ideas. Any idea why this is happening?

**Comment by auouymous** [comment]
Perhaps it was commit ab76aa70a02cfddb650677a49c2a23695732f549? Try inserting those lines in that file and see if it works. Let me know if it does and I'll revert it.

**Comment by auouymous** [comment]
If that fixes the error, you will probably get additional errors and need to add the new packages to those lines listed in https://github.com/gpodder/gpodder/blob/master/tools/win_installer/_base.sh#L86.

**Comment by elelay** [comment]
Yes, and the documentation should be updated to mention installing dependencies listed in _base.sh.
`pip install` in bootstrap was redundant with https://github.com/gpodder/gpodder/blob/master/tools/win_installer/_base.sh#L119

**Comment by auouymous** [comment]
Could bootstrap.sh simply source _base.sh and call install_deps? It would eliminate duplication of the other deps as well, and actually load all required deps without the user needing to manually do it.

**Comment by blushingpenguin** [comment]
I can confirm that reverting ab76aa7... fixed the windows issue. I also had to `pip install requests` and copy the fake dbus module to site-packages.

**Comment by auouymous** [comment]
@blushingpenguin Could you save the following to `test.sh` in ~/gpodder/tools/win_installer/ and try running it on a fresh install? It should call the same code used to build the Windows release, and include all required dependencies.

```
#!/usr/bin/env bash
source _base.sh
install_deps
```

**Comment by blushingpenguin** [comment]
error: failed to initialize alpm library
(could not find or read directory: /home/mark/gpodder/tools/win_installer/build_root/var/lib/pacman/)

seems to be due to pacman --root /home/mark/gpodder/tools/win_installer/build_root/var/lib/pacman/

this was on a clean win10 vm with just msys2 installed from the website as per instructions
