### ISSUE TITLE
Cannot use sock5 proxy (Tor connection)

### ISSUE THREAD

**Issue by realSConway** [gpodder/gpodder#1026]
Hello experts,

I'm trying to force gPodder to tunnel downloads through my proxy server.

Running gPodder flatpack version: 3.10.19

My env variable is set with:
```
$ echo $all_proxy
socks5://127.0.0.1:9050
```

When attempting to download a podcast error:
```
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/gpodder/download.py", line 790, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "/app/lib/python3.8/site-packages/gpodder/download.py", line 340, in retrieve_resume
    headers, real_url = downloader.retrieve_resume(url,
  File "/app/lib/python3.8/site-packages/gpodder/download.py", line 268, in retrieve_resume
    with session.get(url,
  File "/app/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/app/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/app/lib/python3.8/site-packages/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/app/lib/python3.8/site-packages/requests/adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/app/lib/python3.8/site-packages/requests/adapters.py", line 182, in proxy_manager_for
    manager = self.proxy_manager[proxy] = SOCKSProxyManager(
  File "/app/lib/python3.8/site-packages/requests/adapters.py", line 47, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
```

socks is already installed via pip
```
$ pip install requests[socks]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests[socks] in /usr/lib/python3.8/site-packages (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.8/site-packages (from requests[socks]) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests[socks]) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests[socks]) (1.26.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.8/site-packages (from requests[socks]) (3.1)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/lib/python3.8/site-packages (from requests[socks]) (1.7.1)
```

Tried with all_proxy, set with `http://...`, `https://...` instead of `socks5://...`, but this threw other errors

* http://

```
requests.exceptions.ProxyError: HTTPSConnectionPool(host='traffic.libsyn.com', port=443): Max retries exceeded with url: link (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 501 Tor is not an HTTP Proxy')))
```

* https://

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='traffic.libsyn.com', port=443): Max retries exceeded with url: link (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))
```

**Comment by elelay** [comment]
I guess gPodder inside flatpak won't see your installed pysocks ?

**Comment by tpikonen** [comment]
I just submitted a merge request to the flatpak build for the new 3.10.20 release. It bundles a version of requests with socks support, so it should fix this issue. You can install the test build by running:

    flatpak install https://dl.flathub.org/build-repo/48319/org.gpodder.gpodder.flatpakref

Please test and report if it fixes this.

**Comment by realSConway** [comment]
Hello tpikonen, 
Thanks for the reply.

When attemting to install your test build I get error:
```
error: Can't load uri https://dl.flathub.org/build-repo/48319/org.gpodder.gpodder.flatpakref: Server returned status 404: Not Found
```

**Comment by tpikonen** [comment]
Apparently the test builds are deleted after some time. My pull request is here https://github.com/flathub/org.gpodder.gpodder/pull/22 if you want to build it yourself.

**Comment by tpikonen** [comment]
Flathub now has gPodder 3.10.21 with the socks flavor of requests. Could you test if it fixes your problem, @realSConway?

**Comment by realSConway** [comment]
Thanks it works!

set `all_proxy` to `socks5://127.0.0.1:9050` or `socks5://localhost:9050`

gPodder now downloads via proxy.
