### ISSUE TITLE
extra argument in syncui.py for "gpo sync" causes failure

### ISSUE THREAD

**Issue by davedeaven** [gpodder/gpodder#1077]
I use gpo command to do sync operations - it broke sometime in the last few months and gives traceback indicating too many arguments:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/gpodder/syncui.py", line 313, in cleanup_episodes
    util.idle_add(check_free_space)
  File "/usr/lib/python3.6/site-packages/gpodder/util.py", line 1264, in idle_add
    func(*args)
  File "/usr/lib/python3.6/site-packages/gpodder/syncui.py", line 281, in check_free_space
    _config=self._config)
  File "/usr/bin/gpo", line 904, in _episode_selector
    return callback([e for i, e in enumerate(episodes) if selected[i]])
  File "/usr/lib/python3.6/site-packages/gpodder/syncui.py", line 264, in auto_delete_callback
    True, resume_sync)
TypeError: _delete_episode_list() takes from 1 to 3 positional arguments but 4 were given

Note that syncing to external device from the GUI works fine.
Looking at syncui.py, near line 263:

  self.delete_episode_list(episodes, False, True, resume_sync)

has an extra argument.  I think it should be

  self.delete_episode_list(episodes, False, resume_sync)

and making this change resolves the issue.

**Comment by auouymous** [comment]
Sorry about that, I missed that call when removing the skip_lock parameter. Fixed in git.
