### ISSUE TITLE
gpodder error on Arch with python.

### ISSUE THREAD

**Issue by tiltkoko** [gpodder/gpodder#1087]
When trying to sync to my mp3 player I get:
```
[1625802114.167300] [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gpodder/gtkui/desktop/episodeselector.py", line 417, in on_btnOK_clicked
    self.callback(self.get_selected_episodes())
  File "/usr/lib/python3.9/site-packages/gpodder/syncui.py", line 263, in auto_delete_callback
    self.delete_episode_list(episodes, False,
TypeError: delete_episode_list() takes from 2 to 4 positional arguments but 5 were given

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gpodder/gtkui/desktop/episodeselector.py", line 417, in on_btnOK_clicked
    self.callback(self.get_selected_episodes())
  File "/usr/lib/python3.9/site-packages/gpodder/syncui.py", line 263, in auto_delete_callback
    self.delete_episode_list(episodes, False,
TypeError: delete_episode_list() takes from 2 to 4 positional arguments but 5 were given.
```
Whats going on here. Tried reverting to python 3.9.5, but same. Worked a few days ago..

**Comment by auouymous** [comment]
The issue was fixed in #1077, but it appears to also be a problem in the gui, at least with newer python versions. I'll try to get a new release out this weekend.

**Comment by tiltkoko** [comment]
cool. waiting for new release.
