### ISSUE TITLE
Soundcloud feeds are not working

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#1167]
It appears subscribing and updating soundcloud feeds may be broken due to more API changes, see https://github.com/soundcloud/api/issues/142.

Subscribing:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gpodder/gtkui/main.py", line 2667, in thread_proc
    channel = self.model.load_podcast(url=url, create=True,
  File "/usr/lib/python3.9/site-packages/gpodder/model.py", line 1564, in load_podcast
    return self.PodcastClass.load(self, url, create,
  File "/usr/lib/python3.9/site-packages/gpodder/model.py", line 1152, in load
    tmp.update(max_episodes)
  File "/usr/lib/python3.9/site-packages/gpodder/model.py", line 1332, in update
    self._consume_updated_feed(result.feed, max_episodes)
  File "/usr/lib/python3.9/site-packages/gpodder/model.py", line 1219, in _consume_updated_feed
    feed.get_cover_url() or None,
  File "/usr/lib/python3.9/site-packages/gpodder/plugins/soundcloud.py", line 205, in get_cover_url
    return self.sc_user.get_coverart()
  File "/usr/lib/python3.9/site-packages/gpodder/plugins/soundcloud.py", line 123, in get_coverart
    user_info = self.get_user_info()
  File "/usr/lib/python3.9/site-packages/gpodder/plugins/soundcloud.py", line 111, in get_user_info
    raise Exception('Soundcloud "%s": %d %s' % (json_url, r.status_code, r.reason))
Exception: Soundcloud "https://api.soundcloud.com/users/901720.json?consumer_key=zrweghtEtnZLpXf3mlm8mQ": 401 Unauthorized
```

From Yorvyk on mailing list:
```
I'm getting the above error on all my Soundcloud subscriptions.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 2671, in
update_feed_cache_proc
    channel.update(max_episodes=self.config.max_episodes_per_feed)
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1166, in update
    self._consume_updated_feed(result.feed, max_episodes)
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1076, in
_consume_updated_feed
    new_episodes, seen_guids = feed.get_new_episodes(self, existing_guids)
  File "/usr/lib/python3/dist-packages/gpodder/plugins/soundcloud.py", line
196, in get_new_episodes
    return self._get_new_episodes(channel, existing_guids, 'tracks')
  File "/usr/lib/python3/dist-packages/gpodder/plugins/soundcloud.py", line
204, in _get_new_episodes
    tracks = list(self.sc_user.get_tracks(track_type))
  File "/usr/lib/python3/dist-packages/gpodder/plugins/soundcloud.py", line
128, in get_tracks
    tracks = [track for track in json_tracks if track['streamable'] or
track['downloadable']]
  File "/usr/lib/python3/dist-packages/gpodder/plugins/soundcloud.py", line
128, in <listcomp>
    tracks = [track for track in json_tracks if track['streamable'] or
track['downloadable']]
TypeError: string indices must be integers
```

**Comment by christofdamian** [comment]
Would it be an idea to include the [scdl](https://github.com/flyingrub/scdl) functionality in gpodder? That one doesn't use the API and either uses the available downloads or scrapes the tracks of a user or play-list.

**Comment by auouymous** [comment]
scdl appears to use the oauth API.

**Comment by christofdamian** [comment]
Oh, my bad. I didn't realise that. Sorry about the noise.

**Comment by zotabee** [comment]
Any news on soundcloud support? Still broken for now...

**Comment by dante-chiesa** [comment]
[As of July 2021](https://developers.soundcloud.com/blog/security-updates-api), it's impossible to use soundcloud's API without first registering an app under the developer's soundcloud account to get an app-specific secret key. [Per their api docs](https://developers.soundcloud.com/docs/api/explorer/open-api#/oauth/get_connect), they don't even allow the "log in with soundcloud" `/connect` endpoint without a client_id and client_secret, so prompting users to sign in through soundcloud in order to get an oath token isn't a way around this. 

Distributing a 'secret' key as part of an open source application is not very reasonable, so any fix to gpodder's soundcloud integration would require some hacky workaround:
* Ask users to register an "app" under their personal soundcloud account and then fill those app credentials into the settings of their local gpodder install.  (probably the least worst option)
* Ask users to snoop their own Oauth token from their browser, like scdl does as mentioned above. Note that tokens have a limited duration so this would need to be repeated every 6 hours.
* Abandon the API and scrape the user-facing html instead.

**Comment by tpikonen** [comment]
I'll just note here again that the combination of [rss-bridge](https://github.com/RSS-Bridge/rss-bridge) and yt-dlp works fine with soundcloud feeds, at least the last time I tested them.

There is the PR under review (#1177) which may fix the soundcloud plugin, but if it cannot be merged, then maybe the plugin-based soundcloud support should be removed.

Also, the 'Soundcloud search' option under 'Discover new podcasts' does not work.
