### ISSUE TITLE
gpodder downloading files that have already been downloaded

### ISSUE THREAD

**Issue by RandiStone** [gpodder/gpodder#1185]
Hello. I'm having a situation where gpodder is downloading files that have already been downloaded.  It's going back as far as a week and pulling approximately 100 files that have already been downloaded.

What I've determined is that it's overwriting the exiting podcast file. It's doing this with both YouTube videos and mp3 files from a multitude of RSS feeds.

Gpodder version 3.10.21 on Gentoo Linux

Any suggestions on why this might be happening and how to stop it?  Thank you so much.

**Comment by auouymous** [comment]
Unsubscribe from `http://frequencyoffear.com/podcasts-only/rss2.aspx`, the domain name is for sale and returns a webpage instead of a feed.

`http://feeds.feedburner.com/Photonetcast` sends a feed but also sends HTML warnings before the feed data. You can contact the feed author to fix it, wait for it to be resolved or unsubscribe.

`http://www.dribblecast.org/feed/podcast/` is a web page, not a feed.

Search for `gpodder.feedcore.InvalidFeed: Could not parse feed: ` in the log and visit the URL to determine if it is valid or not. There are 32 instances.

I saw no issues with youtube feeds other than some failed DRM content which is not supported by gpodder, and requires youtube-dl to download. But it is difficult to dig through the weeds to find anything, so post another log file if the problem persists after cleaning out all the dead feeds.

**Comment by RandiStone** [comment]
I knew I had some bad feeds in there, but I found more than I expected. I cleaned out all the dead feeds and that certainly cleaned out the log file.  I have also disabled all extensions.  

So now when I look at my log file I still get a whole list of this for files that have already been downloaded:

2021-11-01 04:38:33,928 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Sigler Audiobooks/TuesdayTerror_-_Hiatus_Aug_3_2011.mp3
2021-11-01 04:38:34,009 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Sigler Audiobooks/19_THE_STARTER_Episode_19.mp3
2021-11-01 04:38:34,091 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Sigler Audiobooks/27_THE_STARTER_Episode_27.mp3
2021-11-01 04:38:34,173 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Sigler Audiobooks/14_THE_STARTER_Episode_14.mp3
2021-11-01 04:38:34,255 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Sigler Audiobooks/31_FridayFix_Aug_8_2011_-_TAP_help_request.mp3
2021-11-01 04:38:34,337 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Sigler Audiobooks/01_TUESDAY_TERROR_Episode_01___The_Tot_Tales____Triangle_Victim_.mp3
2021-11-01 04:38:34,419 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Sigler Audiobooks/32_THE_STARTER_Episode_32.mp3
2021-11-01 04:38:34,501 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Sigler Audiobooks/05_THE_STARTER_Episode_5.mp3

There are no error messages prior to the list of unknown external files.
And the rest of my error messages are this:

2021-11-01 04:39:50,671 [gpodder.gtkui.main] ERROR: Error: not found

Traceback (most recent call last):
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/podcastparser.py", line 915, in parse
    sax.parse(stream, handler)
  File "/usr/lib/python3.9/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.9/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python3.9/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:0: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gpodder/model.py", line 212, in parse_feed
    feed = podcastparser.parse(url, data_stream)
  File "/usr/lib/python3.9/site-packages/podcastparser.py", line 917, in parse
    raise FeedParseError(e.getMessage(), e.getException(), e._locator)
podcastparser.FeedParseError: <unknown>:1:0: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gpodder/gtkui/main.py", line 2671, in update_feed_cache_proc
    channel.update(max_episodes=self.config.max_episodes_per_feed)
  File "/usr/lib/python3.9/site-packages/gpodder/model.py", line 1163, in update
    result = self.feed_fetcher.fetch_channel(self, max_episodes)
  File "/usr/lib/python3.9/site-packages/gpodder/model.py", line 203, in fetch_channel
    return self.fetch(url, channel.http_etag, channel.http_last_modified, max_episodes=max_episodes)
  File "/usr/lib/python3.9/site-packages/gpodder/feedcore.py", line 213, in fetch
    return self.parse_feed(url, BytesIO(stream.content), stream.headers, UPDATED_FEED, **kwargs)
  File "/usr/lib/python3.9/site-packages/gpodder/model.py", line 217, in parse_feed
    raise feedcore.InvalidFeed('Could not parse feed: {url}: {msg}'.format(url=url, msg=e))

**Comment by auouymous** [comment]
That error is another malformed or dead feed. You are using 3.10.21, do you have an error icon on any channels after an update? Hovering over the channel icon will show the error message. If not, look for a feed URL near the top or bottom of the error message in log file.

If the scott sigler feed is bad, it might have wiped or corrupted the episodes, causing the unknown external file warnings for episodes you have downloaded.

**Comment by RandiStone** [comment]
I deleted Scot Sigler.  None of the feed show error messages when hovering over the icons.

Right now it wants to download 11 episode that have already been downloaded.  That's better than the 100+ I had before.

My log file is empty other than 213 lines of unknown external files.


2021-11-08 11:44:05,645 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Duct Tape Marketing/DTM-Dorie-Clark.mp3
2021-11-08 11:44:05,664 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Duct Tape Marketing/DTM-Tom-Stanfill.mp3
2021-11-08 11:44:05,681 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Duct Tape Marketing/John_Ruhlin-final.mp3
2021-11-08 11:44:05,698 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Duct Tape Marketing/DTM-Tim-Brown.mp3
2021-11-08 11:44:05,772 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Design Matters/Toshi_Reagon_Final.mp3
2021-11-08 11:44:05,814 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Design Matters/Nick_Offerman_Final.mp3
2021-11-08 11:44:05,862 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/The Three Month Vacation Podcast_ Online Small Business_Mark/6_Nov_Motivate_yourself_wav.mp3
2021-11-08 11:44:05,878 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/The Three Month Vacation Podcast_ Online Small Business_Mark/How_to_use_the_Goldilocks_Method_to_get_things_done_wav.mp3
2021-11-08 11:44:05,894 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/The Three Month Vacation Podcast_ Online Small Business_Mark/23-Productivity-wasting_time_wav.mp3
2021-11-08 11:44:05,909 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/The Three Month Vacation Podcast_ Online Small Business_Mark/16_Oct-Fewer_products_scarcity_wav.mp3
2021-11-08 11:44:05,926 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/The History of the Cold War Podcast/Documentary Episode 2 - CNN Cold War Episode 1 - Comrades.mp3 
2021-11-08 11:44:06,401 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Legends _ Losers w_Christopher Lochhead/250_FYD-New_Category_of_Humans-Native_Digitals.mp3
2021-11-08 11:44:06,423 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Legends _ Losers w_Christopher Lochhead/249_FYD-Ron_Friedman.mp3
2021-11-08 11:44:06,444 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Legends _ Losers w_Christopher Lochhead/152_Darren_Prince.mp3
2021-11-08 11:44:06,458 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/The Dick Show/The_Dick_Show_281.mp3
2021-11-08 11:44:06,470 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/The Dick Show/The_Dick_Show_280.mp3
2021-11-08 11:44:06,482 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/The Dick Show/loaded
2021-11-08 11:44:06,495 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/The Dick Show/The_Dick_Show_282.mp3
2021-11-08 11:44:06,716 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Kings and Generals/Trial by Combat_ History of Judicial Duel in Europe - Last Duel DOCUMENTARY.mp4
2021-11-08 11:44:06,787 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Kings and Generals/Battle of Klokotnitsa 1230 - Fourth Crusade DOCUMENTARY.mp4
2021-11-08 11:44:06,857 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Kings and Generals/Battle of Fraustadt 1706 - Swedish Invasion of Poland DOCUMENTARY.mp4
2021-11-08 11:44:06,870 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/http___kingsandgenerals.libsyn.com_rss/loaded
2021-11-08 11:44:06,912 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Uncensored Tactical Podcast/190_Gear_Self_Check_Buddy_Check.mp3
2021-11-08 11:44:06,919 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Uncensored Tactical Podcast/191_Tactical_Organization.mp3
2021-11-08 11:44:06,961 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Starting Strength Radio/%2358%20Actual%20AUDIO.mp3
2021-11-08 11:44:06,975 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Starting Strength Radio/%2358%20Audio.mp3
2021-11-08 11:44:07,011 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Adams' Blog/Episode-1534-Scott-Adams-Cognitive-Blind-Spots-in-the-News-Today.mp3
2021-11-08 11:44:07,013 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Adams' Blog/Episode-1532-Scott-Adams-Mandatory-Vaccinations-for-Robots.mp3
2021-11-08 11:44:07,014 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Adams' Blog/Episode-1533-Scott-Adams-The-Time-I-Met-Colin-Powell-and-More.mp3
2021-11-08 11:44:07,015 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Adams' Blog/Episode-1554-PART1.mp3
2021-11-08 11:44:07,016 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Adams' Blog/Episode-1555-Scott-Adams-The-Democrat-Party-is-Coming-to-a-Rapid-End.mp3
2021-11-08 11:44:07,017 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Scott Adams' Blog/Episode-1554-PART2.mp3
2021-11-08 11:44:07,023 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Pop & Locke/1635176874964-717766d34f01b66d06cb18c87452b2df.mp3
2021-11-08 11:44:07,046 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Radio Free Satan_ Satanic Podcast Network/rtm592.mp3
2021-11-08 11:44:07,054 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Radio Free Satan_ Satanic Podcast Network/MG103.mp3
2021-11-08 11:44:07,062 [gpodder.model] WARNING: Unknown external file: /home/skippy/gPodder/Downloads/Radio Free Satan_ Satanic Podcast Network/rtm591.mp3

**Comment by auouymous** [comment]
> I deleted Scot Sigler. None of the feed show error messages when hovering over the icons.

The icon itself in the channel list should have an error icon, similar to how paused channels have a paused icon. Hovering wouldn't show an error message without an icon present, but this only happens after a channel fails to update, because restarting gpodder clears the errors.


> Right now it wants to download 11 episode that have already been downloaded. That's better than the 100+ I had before.

So you restarted gpodder, performed a full update of all channels, and the log only contained external file warnings?

**Comment by RandiStone** [comment]
Yes. Only external file warnings.
