### ISSUE TITLE
ImportError: cannot import name 'sync' from 'os' (C:\Program Files (x86)\gPodder\lib\python3.9\os.pyc)

### ISSUE THREAD

**Issue by dreamflasher** [gpodder/gpodder#1187]
I get this error: `ImportError: cannot import name 'sync' from 'os' (C:\Program Files (x86)\gPodder\lib\python3.9\os.pyc)` with the build 41319604 on Windows.

Full stacktrace:

```
1635499886.723914 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder_launch\gpodder.py", line 174, in main
    from gpodder.gtkui import app
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\gtkui\app.py", line 36, in <module>
    from .main import gPodder
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\gtkui\main.py", line 41, in <module>
    from gpodder.syncui import gPodderSyncUI
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\syncui.py", line 28, in <module>
    from gpodder import sync, util
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\sync.py", line 33, in <module>
    from os import sync
ImportError: cannot import name 'sync' from 'os' (C:\Program Files (x86)\gPodder\lib\python3.9\os.pyc)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder_launch\gpodder.py", line 174, in main
    from gpodder.gtkui import app
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\gtkui\app.py", line 36, in <module>
    from .main import gPodder
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\gtkui\main.py", line 41, in <module>
    from gpodder.syncui import gPodderSyncUI
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\syncui.py", line 28, in <module>
    from gpodder import sync, util
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\sync.py", line 33, in <module>
    from os import sync
ImportError: cannot import name 'sync' from 'os' (C:\Program Files (x86)\gPodder\lib\python3.9\os.pyc)
```

**Comment by dreamflasher** [comment]
I tried it, should be safe to be removed.
