### ISSUE TITLE
AttributeError: 'function' object has no attribute 'startswith' (extract_hyperlinked_text)

### ISSUE THREAD

**Issue by thp** [gpodder/gpodder#1195]
Forwarded from this Launchpad bug:

https://bugs.launchpad.net/ubuntu/+source/gpodder/+bug/1952643

Haven't investigated why that is, maybe at some point `element.tag` became a function instead of an attribute, and it needs to be called?

dependencies.txt (linked in the above report says:

```
python3-html5lib 1.1-3
```

Here is the traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 988, in on_episode_list_selection_changed
    self.shownotes_object.set_episodes(self.get_selected_episodes())
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/shownotes.py", line 114, in set_episodes
    self.update(heading, subheading, episode)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/shownotes.py", line 199, in update
    for target, text in util.extract_hyperlinked_text(episode.description_html or episode.description):
  File "/usr/lib/python3/dist-packages/gpodder/util.py", line 802, in extract_hyperlinked_text
    return ExtractHyperlinkedText()(html5lib.parseFragment(html))
  File "/usr/lib/python3/dist-packages/gpodder/util.py", line 745, in __call__
    self.visit(document)
  File "/usr/lib/python3/dist-packages/gpodder/util.py", line 757, in visit
    self.visit(child)
  File "/usr/lib/python3/dist-packages/gpodder/util.py", line 750, in visit
    tag_name = (element.tag[len(NS):] if element.tag.startswith(NS) else element.tag).lower()
AttributeError: 'function' object has no attribute 'startswith'
```

**Comment by auouymous** [comment]
A podcast URL that causes the issue would make fixing it easier.

**Comment by The-Bishop** [comment]
This episode:
[https://minkorrekt.de/mi206-zwischen-den-jahren/](https://minkorrekt.de/mi206-zwischen-den-jahren/)
of this podcast feed:
[http://minkorrekt.de/feed/mp3/](http://minkorrekt.de/feed/mp3/)
shows the described problem. (At least for me)

**Comment by auouymous** [comment]
Thank you for the feed URL. I was able to reproduce the issue and create a fix (#1206).

**Comment by The-Bishop** [comment]
This patch solves the issue for me.

**Comment by auouymous** [comment]
@The-Bishop Thanks for testing it.
