### ISSUE TITLE
Error when running from CLI

### ISSUE THREAD

**Issue by realSConway** [gpodder/gpodder#1212]
Hi everyone, I'm having problems running gpodder from the cli

I'm using Sway as my DE on Opensuse.
Pulled from github, set `export GPODDER_INSTALL_UIS="cli"`, then ran `python3 tools/localdepends.py`

When I try to start gpo, with `bin/gpo`, I get a some errors.
```
1643048735.795941 [gpodder.util] WARNING: html5lib not found, falling back to HTMLParser
1643048735.811798 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "bin/gpo", line 139, in <module>
    from gpodder import common, core, download, feedcore, model, my, opml, sync, util, youtube 
 isort:skip
  File "/home/suse/bin/gpodder/src/gpodder/sync.py", line 40, in <module>
    gi.require_version('Gtk', '3.0')  # isort:skip
  File "/usr/lib64/python3.8/site-packages/gi/_init_.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

Traceback (most recent call last):
  File "bin/gpo", line 139, in <module>
    from gpodder import common, core, download, feedcore, model, my, opml, sync, util, youtube 
 isort:skip
  File "/home/suse/bin/gpodder/src/gpodder/sync.py", line 40, in <module>
    gi.require_version('Gtk', '3.0')  # isort:skip
  File "/usr/lib64/python3.8/site-packages/gi/_init_.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

Why does it require Gtk when I assumed I explicitly set cli only?

Thank you for your time

**Comment by elelay** [comment]
Thanks for reporting. The extra import slipped in uninvited...

**Comment by realSConway** [comment]
Hi @elelay,
Thanks for the quick reply!

How am I actually supposed to apply this fix?

I cd in to gpodder, then update via
```
❯ git pull
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 5 (delta 3), reused 5 (delta 3), pack-reused 0
Unpacking objects: 100% (5/5), 443 bytes | 221.00 KiB/s, done.
From https://github.com/gpodder/gpodder
   57045619..8873604e  master     -> origin/master
Updating 57045619..8873604e
Fast-forward
 src/gpodder/sync.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```

After I re-run `./bin/gpo`, unfortunately I still get similar error:
```
❯ ./bin/gpo
1643057938.361769 [gpodder.util] WARNING: html5lib not found, falling back to HTMLParser
1643057938.389517 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "./bin/gpo", line 141, in <module>
    from gpodder.syncui import gPodderSyncUI  # isort:skip
  File "/home/suse/bin/gpodder/src/gpodder/syncui.py", line 29, in <module>
    from gpodder.deviceplaylist import gPodderDevicePlaylist
  File "/home/suse/bin/gpodder/src/gpodder/deviceplaylist.py", line 29, in <module>
    gi.require_version('Gtk', '3.0')  # isort:skip
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

Traceback (most recent call last):
  File "./bin/gpo", line 141, in <module>
    from gpodder.syncui import gPodderSyncUI  # isort:skip
  File "/home/suse/bin/gpodder/src/gpodder/syncui.py", line 29, in <module>
    from gpodder.deviceplaylist import gPodderDevicePlaylist
  File "/home/suse/bin/gpodder/src/gpodder/deviceplaylist.py", line 29, in <module>
    gi.require_version('Gtk', '3.0')  # isort:skip
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```
I also re-ran `python3 tools/localdepends.py` but this did not help. Or is this not the proper way to update a git-installed application?
(I'm still new ;) )

**Comment by auouymous** [comment]
Thanks again, does another pull fix it? And nothing needs to be done to run it from the git directory.

**Comment by realSConway** [comment]
Hi @auouymous, 
Excellent!
Unfortunately, we're not quite there yet... When trying to sync to device, 
```
gpo> sync
1643092953.504130 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "./bin/gpo", line 1267, in <module>
    main()
  File "./bin/gpo", line 1261, in main
    cli._shell()
  File "./bin/gpo", line 1120, in _shell
    self._parse(args)
  File "./bin/gpo", line 1230, in _parse
    return self._checkargs(func, command_line)
  File "./bin/gpo", line 1150, in _checkargs
    return func(*command_line)
  File "./bin/gpo", line 976, in sync
    sync_ui.on_synchronize_episodes(self._model.get_podcasts(), episodes=None, force_played=True, done_callback=done_lock.release)
  File "/home/suse/bin/gpodder/src/gpodder/syncui.py", line 108, in on_synchronize_episodes
    if not device.open():
  File "/home/suse/bin/gpodder/src/gpodder/sync.py", line 541, in open
    if not self.mount_volume_for_file(self.destination):
  File "./bin/gpo", line 940, in _mount_volume_for_file
    result, message = util.mount_volume_for_file(file, None)
  File "/home/suse/bin/gpodder/src/gpodder/util.py", line 2295, in mount_volume_for_file
    gi.require_version('Gtk', '3.0')
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

Traceback (most recent call last):
  File "./bin/gpo", line 1267, in <module>
    main()
  File "./bin/gpo", line 1261, in main
    cli._shell()
  File "./bin/gpo", line 1120, in _shell
    self._parse(args)
  File "./bin/gpo", line 1230, in _parse
    return self._checkargs(func, command_line)
  File "./bin/gpo", line 1150, in _checkargs
    return func(*command_line)
  File "./bin/gpo", line 976, in sync
    sync_ui.on_synchronize_episodes(self._model.get_podcasts(), episodes=None, force_played=True, done_callback=done_lock.release)
  File "/home/suse/bin/gpodder/src/gpodder/syncui.py", line 108, in on_synchronize_episodes
    if not device.open():
  File "/home/suse/bin/gpodder/src/gpodder/sync.py", line 541, in open
    if not self.mount_volume_for_file(self.destination):
  File "./bin/gpo", line 940, in _mount_volume_for_file
    result, message = util.mount_volume_for_file(file, None)
  File "/home/suse/bin/gpodder/src/gpodder/util.py", line 2295, in mount_volume_for_file
    gi.require_version('Gtk', '3.0')
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```
I think `util.py` also needs to be patched.

**Comment by auouymous** [comment]
That one actually needs Gtk.

@elelay I assume the Gtk main loop code has something to do with the progress tab updating. #1213 seems to work when syncing to a directory in gtk and cli, can you confirm?

**Comment by elelay** [comment]
I'm not sure: as `gio.File.mount_enclosing_volume` is asynchronous, doesn't it need an event loop to be processed?

**Comment by elelay** [comment]
I've tested using a folder in a usb key as sync device: it fails when the device is not mounted.
With USB key label=TRAVEL, I browsed and mounted the Volume via the dialog.
I get `file:///run/media/elelay/TRAVEL/gpodder` as sync folder name in the text field.
unmount outside gPodder and try to sync => `Gio.IOErrorEnum.NOT_SUPPORTED` in the `mount_volume_for_file` callback.
Generally, when the volume is not mounted Gio is not able to figure out the volume to mount from the file path: `mount_volume_for_file` fails as well as `find_enclosing_mount` directory on the `GLocalFile`.

It must be different with a `mtp://` scheme where gvfs-mtp knows that it's a device to access via mtp.

So my conclusion is that auto-mounting is currently broken.

I played with a interactive python shell
```
>>> from gi.repository import Gio, GLib
>>> m = Gio.VolumeMonitor.get()
>>> [v.get_name() for v in m.get_volumes()]
['Volume de 68 Go', 'Volume de 1,0 Go', 'TRAVEL']
>>> v = m.get_volumes()[-1]
>>> v.mount(0, None, None, None)
>>> v.get_mount()
>>> ml = GLib.MainLoop()
>>> ml.run()
^C
>>> v.get_mount()
<__gi__.GProxyMount object at 0x7f985d56aa40 (GProxyMount at 0x5607599b8250)>
>>> r = mnt.get_root()
>>> g = r.get_child("gpodder")
>>> g.get_uri()
'file:///run/media/elelay/TRAVEL/gpodder'
>>> g.find_enclosing_mount().get_volume().get_name()
'TRAVEL'
>>> gg = Gio.File.new_for_uri('file:///run/media/elelay/TRAVEL/gpodder')
>>> gg.find_enclosing_mount().get_volume().get_name()
'TRAVEL'
```

After `v.mount()` the volume was mounted but gio didn't report it.
After running the main loop (and interrupting with Ctrl-C) it now knew the volume was mounted.
From the file I could then get volume information back, even when creating the file from uri.
So I think gpo must run a `Glib.MainLoop()` in order for the mtp mount to succeed.

**Comment by auouymous** [comment]
Yes, it probably does need a loop, I updated #1213.

**Comment by auouymous** [comment]
@elelay Did the loop fix in #1213 work?

**Comment by elelay** [comment]
Digging into this keeps giving: I had rate limiter to 1kb/s => wasn't seeing the end of syncing.
I selected all and clicked cancel => here's the stacktrace!

```
647466648.424128 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/home/elelay/devel/gPodder/src/gpodder/gtkui/main.py", line 3721, in on_item_cancel_download_activate
    self.cancel_task_list(selected_tasks, force=force)
  File "/home/elelay/devel/gPodder/src/gpodder/gtkui/main.py", line 3196, in cancel_task_list
    task.cancel()
  File "/home/elelay/devel/gPodder/src/gpodder/sync.py", line 802, in cancel
    self.device.cancel(self)
TypeError: Device.cancel() takes 1 positional argument but 2 were given
```

**Comment by elelay** [comment]
Regarding the fix in #1213, adding the loop doesn't fix that glib will not find a volume to mount given the `file:///run/media/elelay/TRAVEL/gpodder`.
OK for merging #1213 as is but we shall remember that auto-mounting doesn't work (for me).

**Comment by auouymous** [comment]
The Device.cancel() issue has been fixed with f6bae4f780798e8304ca0c8111e564a768f7d554.

**Comment by auouymous** [comment]
@realSConway Is this now fixed for you?

**Comment by auouymous** [comment]
3.11.0 has been released, please re-open if this issue has not been resolved.
