### ISSUE TITLE
issue updating podcasts from gui, works perfectly in cli interface

### ISSUE THREAD

**Issue by nerdguy1338** [gpodder/gpodder#1260]
using the latest version of the debian package (v3.10.21) i click on a podcast to update it, or run the refresh all option, and this happens.

Storing downloads in /media/ben/disk3/gPodder/ (GPODDER_DOWNLOAD_DIR is set)
1648264243.857393 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 3007, in on_itemUpdateChannel_activate
    self.update_feed_cache(channels=[self.active_channel])
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 2631, in update_feed_cache
    self.rewrite_urls_mygpo()
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 576, in rewrite_urls_mygpo
    rewritten_urls = self.mygpo_client.get_rewritten_urls()
  File "/usr/lib/python3/dist-packages/gpodder/my.py", line 227, in get_rewritten_urls
    self._store.remove(rewritten_urls)
  File "/usr/lib/python3/dist-packages/gpodder/minidb.py", line 148, in remove
    self.remove(child)
  File "/usr/lib/python3/dist-packages/gpodder/minidb.py", line 159, in remove
    self.db.execute('DELETE FROM %s WHERE %s' % (table,
sqlite3.OperationalError: incomplete input

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 3007, in on_itemUpdateChannel_activate
    self.update_feed_cache(channels=[self.active_channel])
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 2631, in update_feed_cache
    self.rewrite_urls_mygpo()
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 576, in rewrite_urls_mygpo
    rewritten_urls = self.mygpo_client.get_rewritten_urls()
  File "/usr/lib/python3/dist-packages/gpodder/my.py", line 227, in get_rewritten_urls
    self._store.remove(rewritten_urls)
  File "/usr/lib/python3/dist-packages/gpodder/minidb.py", line 148, in remove
    self.remove(child)
  File "/usr/lib/python3/dist-packages/gpodder/minidb.py", line 159, in remove
    self.db.execute('DELETE FROM %s WHERE %s' % (table,
sqlite3.OperationalError: incomplete input

i see that in the terminal if i ran gpodder from there.
gpo works fine though.

**Comment by auouymous** [comment]
Sorry for the long delay. For whatever reason, that code is only called by gpodder, which is why gpo doesn't have an issue.

Would you be able to edit `/usr/lib/python3/dist-packages/gpodder/minidb.py`, copy and paste lines 159 and 160, change only the `self.db.execute` on line 159 to `print`, and then run gpodder from a terminal? It should look like the code below and print out a line that begins with "DELETE FROM" when you perform the action that crashes.

```python
            print('DELETE FROM %s WHERE %s' % (table,
                ' AND '.join('%s=?' % s for s in slots)), values)
            self.db.execute('DELETE FROM %s WHERE %s' % (table,
                ' AND '.join('%s=?' % s for s in slots)), values)
```

You could also try renaming the `gpodder.net` file and doing the action in gpodder. If that works, it could be a corrupt gpodder.net file, which is only important if you use the gpodder.net site.

**Comment by nerdguy1338** [comment]
Couldn't you fix this yourself with a code update? I installed through pip,
I think.

**Comment by auouymous** [comment]
The code works fine for me and something is causing it to break on your end, but I can't figure out what that is without your help.

**Comment by nerdguy1338** [comment]
tried it, didn't work.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 3014, in on_itemUpdate_activate
    self.update_feed_cache()
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 2631, in update_feed_cache
    self.rewrite_urls_mygpo()
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 576, in rewrite_urls_mygpo
    rewritten_urls = self.mygpo_client.get_rewritten_urls()
  File "/usr/lib/python3/dist-packages/gpodder/my.py", line 227, in get_rewritten_urls
    self._store.remove(rewritten_urls)
  File "/usr/lib/python3/dist-packages/gpodder/minidb.py", line 148, in remove
    self.remove(child)
  File "/usr/lib/python3/dist-packages/gpodder/minidb.py", line 161, in remove
    self.db.execute('DELETE FROM %s WHERE %s' % (table,
sqlite3.OperationalError: incomplete input


got that as output.
