### ISSUE TITLE
database copy not working

### ISSUE THREAD

**Issue by 122christo** [gpodder/gpodder#1315]
The system is Linux mate
I made a new install on a new system. As a backup I made a copy of the "gPodder" directory from the old ~.
Now I changed the new gPodder dir with the old one - and it doesn't work. No podcasts!

edit:
Ok I started gpodder from the console and I got this:

christoph@christo:~$ gpodder
1656690173.259315 [gpodder.sync] WARNING: Could not find gpod
1656690173.539465 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/app.py", line 130, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 86, in __init__
    BuilderWidget.__init__(self, None, _builder_expose={'app': app})
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/interface/common.py", line 36, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/base.py", line 71, in __init__
    self.new()
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 165, in new
    self.channels = self.model.get_podcasts()
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1352, in get_podcasts
    self.children = self.db.load_podcasts(podcast_factory)
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 162, in load_podcasts
    result = [factory(dict(list(zip(keys, row))), self) for row in cur]
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 162, in <listcomp>
    result = [factory(dict(list(zip(keys, row))), self) for row in cur]
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1349, in podcast_factory
    return self.PodcastClass.create_from_dict(dct, self, dct['id'])
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 232, in create_from_dict
    o = cls(*args)
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 814, in __init__
    self.children = self.db.load_episodes(self, self.episode_factory)
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 177, in load_episodes
    cur.execute(sql, args)
sqlite3.DatabaseError: database disk image is malformed

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/app.py", line 130, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 86, in __init__
    BuilderWidget.__init__(self, None, _builder_expose={'app': app})
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/interface/common.py", line 36, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/base.py", line 71, in __init__
    self.new()
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 165, in new
    self.channels = self.model.get_podcasts()
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1352, in get_podcasts
    self.children = self.db.load_podcasts(podcast_factory)
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 162, in load_podcasts
    result = [factory(dict(list(zip(keys, row))), self) for row in cur]
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 162, in <listcomp>
    result = [factory(dict(list(zip(keys, row))), self) for row in cur]
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1349, in podcast_factory
    return self.PodcastClass.create_from_dict(dct, self, dct['id'])
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 232, in create_from_dict
    o = cls(*args)
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 814, in __init__
    self.children = self.db.load_episodes(self, self.episode_factory)
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 177, in load_episodes
    cur.execute(sql, args)
sqlite3.DatabaseError: database disk image is malformed
...

How to fix it?
Thank You for reading and help

**Comment by auouymous** [comment]
>  sqlite3.DatabaseError: database disk image is malformed

It works fine to copy the database but the database file you copied is either corrupted or perhaps sqlite databases aren't portable between different hardware. Is the 32/64bitness different? Is the endianess (x86 vs ppc) different?

**Comment by 122christo** [comment]
Its the same hardware. I 've made the same database copy some time ago and it worked. Ok, I took another solution: I extracted the rssfeed urls from the database and made with each a new podcast abo. It took some time, but now it works again.
