### ISSUE TITLE
gpodder shows no podcasts, not a Python programmer, help please

### ISSUE THREAD

**Issue by brian-in-crawford** [gpodder/gpodder#1332]
I'm running Linux Mint V20 LTS with an XFCE desktop. The version of Python is 3.8.4. I'm using gpodder as downloaded from GitHub. 

gpodder has been running fine for me up to July 7th. Suddenly, all the podcasts disappeared. I tried updating from Git, but that had no effect. Running gpodder from the terminal produces the output appended below. There's a whole lot more of it (100 Kb), but I suspect the errors in the rest of the file are consequential on these at the top. I've checked the files mentioned and they DO exist. I'm not a python programmer, that's about as far as I can go on my own. Can anybody assist, please? 

Copy of first section of output to the terminal follows. 

1657517436.836100 [gpodder.extensions] ERROR: Cannot load normalize_audio from /data3/git/gpodder/share/gpodder/extensions/normalize
_audio.py: Command not found: normalize-ogg
Traceback (most recent call last):
  File "/data3/git/gpodder/src/gpodder/extensions.py", line 261, in set_enabled
    self.load_extension()
  File "/data3/git/gpodder/src/gpodder/extensions.py", line 319, in load_extension
    self.module = module_file.gPodderExtension(self)
  File "/data3/git/gpodder/share/gpodder/extensions/normalize_audio.py", line 48, in __init__
    self.container.require_command('normalize-ogg')
  File "/data3/git/gpodder/src/gpodder/extensions.py", line 221, in require_command
    raise MissingCommand(msg, command)
gpodder.extensions.MissingCommand: Command not found: normalize-ogg
1657517436.840376 [gpodder.extensions] ERROR: Cannot load youtube-dl from /data3/git/gpodder/share/gpodder/extensions/youtube-dl.py:
 No module named 'youtube_dl'
Traceback (most recent call last):
  File "/data3/git/gpodder/share/gpodder/extensions/youtube-dl.py", line 14, in <module>
    import yt_dlp as youtube_dl
ModuleNotFoundError: No module named 'yt_dlp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data3/git/gpodder/src/gpodder/extensions.py", line 261, in set_enabled
    self.load_extension()
  File "/data3/git/gpodder/src/gpodder/extensions.py", line 303, in load_extension
    module_file = imp.load_module(basename, fp, self.filename,
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data3/git/gpodder/share/gpodder/extensions/youtube-dl.py", line 16, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'
1657517436.963187 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/data3/git/gpodder/src/gpodder/gtkui/app.py", line 190, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/data3/git/gpodder/src/gpodder/gtkui/main.py", line 92, in __init__
    BuilderWidget.__init__(self, None,
  File "/data3/git/gpodder/src/gpodder/gtkui/interface/common.py", line 52, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "/data3/git/gpodder/src/gpodder/gtkui/base.py", line 71, in __init__
    self.new()
  File "/data3/git/gpodder/src/gpodder/gtkui/main.py", line 187, in new
    self.channels = self.model.get_podcasts()
  File "/data3/git/gpodder/src/gpodder/model.py", line 1483, in get_podcasts

**Comment by auouymous** [comment]
The normalize-audio failure is because the normalize-ogg binary wasn't found in your path. The youtube-dl failure is because you don't have youtube-dl or yt-dlp installed. Do you have multiple python versions and one of them is installed in a different version?

Neither of those errors will cause gpodder to fail to start, but that last chopped off failure could. Can you please post the rest of it?

**Comment by brian-in-crawford** [comment]
[errors.lst.gz](https://github.com/gpodder/gpodder/files/9083349/errors.lst.gz)

As requested, gzipped on grounds of size.

**Comment by auouymous** [comment]
> sqlite3.DatabaseError: database disk image is malformed

Do you have a backup? If so, overwrite the `Database` file in gpodder's directory with your backup copy. If not, delete the `Database` file and subscribe to your podcasts again.

**Comment by brian-in-crawford** [comment]
Ugh! I wonder what happened to cause that? OK, if that's the only route out, so be it. Thanks for your help.
