### ISSUE TITLE
[SOLVED] All YouTube feeds, and ONLY YouTube feeds, failing with a 'Connection reset by peer

### ISSUE THREAD

**Issue by brian-in-crawford** [gpodder/gpodder#1354]
[2022-08-03.log](https://github.com/gpodder/gpodder/files/9252264/2022-08-03.log)

Since sometime late last month (the last successful download I can find occurred on 26th July) ALL of my YouTube feeds, and ONLY my YouTube feeds, have been failing with one of two error messages

Seven feeds fail with

`ERROR: ERROR: Unable to download webpage: <urlopen error [Errno 104] connection reset by peer. (Caused by URLError (ConnectionResetError (104, 'Connection reset by peer')))`

while another six fail with 

`ERROR: Unable to download JSON metadata: <urlopen error [Errno 104] connection reset by peer. (Caused by URLError (ConnectionResetError (104, 'Connection reset by peer')))`

All of these feeds have been downloading correctly for at least two months before these sudden failures. 

This is all totally reproducible, I've had five or six tries over the week since then, with exactly the same results. 

I'm using the latest gpodder updated from GitHub (3.11.0 datestamped 2022-07-30), and I've also tried updating youtube-dl, which gives me a version dated 2021-12-17.

I'm running 64-bit Linux Mint v20.3 LTS, and my net connection is a (usually!) rock-solid 20/5 Mb/s VDSL line. I just don't believe that it can be the net connection at fault, because once again, everything works perfectly apart from the YouTube feeds. 

I've got a LOT of warnings in the log file about missing files, these are episodes that I moved out of the gPodder directory, so they're my own fault.  I;ve removed them from the log file (there were close on 1000 lines of them!)

**Comment by auouymous** [comment]
Does youtube.com work in your web browser? Is your ca-certificates package up to date? And python3.8, certifi, urllib3 and requests?

You could try installing yt-dlp. Gpodder 3.11.0 will now use it (if installed) instead of youtube-dl and it downloads episodes at full speed instead of ~50kb/s. But it might not fix whatever is preventing access to youtube.com.

**Comment by brian-in-crawford** [comment]
Yes, YouTube works in Firefox. I tried making sure all available updates had been applied before I posted here. ca-certificates is datestamped 20211016. Python 3.8 is installed, and is the latest version from the Ubuntu repositories. Same goes for certifi, urllib3 and requests. 

I tried installing yt-dlp. The only difference was that the error message was modified very slightly, Instead of the seven 'Unable to download webpage', I got 'unable to download API page', but the six which mentioned a JSON metadata error changed to the same error message as the other seven.

**Comment by auouymous** [comment]
What does the following display when you run it?

```
python3 -c 'from __future__ import print_function; import requests; \
r = requests.get("https://www.youtube.com/channel/UCd18OhMfRmjMjzSHP7Zrzmw") ; \
print("%d %s" % (r.status_code, r.reason))'
```

**Comment by brian-in-crawford** [comment]
`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: SysCallError(104, 'ECONNRESET')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /channel/UCd18OhMfRmjMjzSHP7Zrzmw (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /channel/UCd18OhMfRmjMjzSHP7Zrzmw (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))
`

**Comment by auouymous** [comment]
Your ca-certificates is 9 months newer than mine, so that shouldn't be the issue.

Could you try running this one? It disables certificate checking.

```
python -c 'from __future__ import print_function; import requests; \
r = requests.get("https://www.youtube.com/channel/UCd18OhMfRmjMjzSHP7Zrzmw", verify=False) ; \
print("%d %s" % (r.status_code, r.reason))'
```

**Comment by brian-in-crawford** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: SysCallError(104, 'ECONNRESET')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /channel/UCd18OhMfRmjMjzSHP7Zrzmw (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /channel/UCd18OhMfRmjMjzSHP7Zrzmw (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))

**Comment by auouymous** [comment]
So not a certificate issue, what version of openssl do you have? Is your browser using a proxy that python hasn't been configured for, and maybe a firewall is blocking access to youtube? I doubt it would help but are you able to update to python 3.9 or 3.10?

**Comment by brian-in-crawford** [comment]
Synaptic shows openssl as 1.1.1f and python3-openssl as 19.0.0

There are no proxies configured on this PC. 

There's a firewall in my VDSL modem/router, but that hasn't been changed (unless my ISP did it remotely and didn't tell me) since long before gPodder stopped working at the end of July. 

The same applies to the Raspberry Pi-hole I use as an ad-blocker, it's been running unchanged (apart from occasionally updating the junk site list) for months, if not years. I can access YouTube through the browser without a problem, it's just the ads get blanked due to the Pi-hole. 

The latest version of Python in the Ubuntu repositories is Python 3.9. I will try upgrading to that sometime in the next day or two (I'm a bit busy over the weekend) and will report back.

**Comment by auouymous** [comment]
1.1.1f is more than two years old, is there an update for it?

**Comment by brian-in-crawford** [comment]
It appears I can get up to 1.1.1q OR 3.0.5 by installing from sources. I'm willing to go up to 1.1.1q if you think there's a significant chance of it solving the problem - or try to, I'm not a C programmer - but I'd be concerned about going to a different major version on the grounds of possibly breaking other installed software. I have no idea about how good the backwards compatibility is from 3.0.5 to 1.1.1. 

I can at least try downloading the sources and see whether I can get them to build correctly, though. Again, you will have to give me a couple of days before I have time to do that - I'll post an update probably on Monday morning my time (GMT/UTC minus 4)

**Comment by auouymous** [comment]
The 3.0.x series is marked unstable in Gentoo, I have 1.1.1q. By source do you mean a package that configures, compiles and installs itself via your package manager, or would you be manually building it? It only takes a few minutes to compile, but you probably shouldn't do it if your package manager isn't handling it, unless you've done it before and know how.

> if you think there's a significant chance of it solving the problem

It is more likely openssl is the problem than python, since openssl is what connects to the server. I doubt either one will help, but there isn't much left to try.

**Comment by brian-in-crawford** [comment]
I meant downloading the sources and building them myself. I was a programmer in my chequered past, but a very specialised one (laboratory systems), I'm totally at home with Pascal(Delphi), FORTRAN, various flavours of SQL, but I haven't written a single byte of C-type languages in my life. 

Anyway, I downloaded the sources to both 1.1.1q and 3.0.5 (which the OpenSSL website seems to consider is stable, BTW). The 1.1.1q built just fine, but in attempting to build 3.0.5 the gcc compiler threw an internal error. I'll try to get it installed and tested in the next day or so.

Thanks for all your attempts to help, BTW.

**Comment by brian-in-crawford** [comment]
I don't know whether this provides any useful information, but it did occur to me to try to add another YouTube feed. Obviously gPodder connected to YouTube, but adding the feed failed, generating the following error message

`https://www.youtube.com/feeds/videos.xml?channel_id=UCgUueMmSpcl-aCTt5CuCKQw:
local variable 'contents' referenced before assignment`

**Comment by auouymous** [comment]
Your python is not connecting to youtube, and that prevents gpodder from connecting. Getting that python command to work is the only thing that matters.

**Comment by brian-in-crawford** [comment]
Sorry for the delay, I upgraded to openssl 1.1.1q but the python commands you gave me above still didn't work, the output is as follows

`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: SysCallError(104, 'ECONNRESET')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /channel/UCd18OhMfRmjMjzSHP7Zrzmw (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /channel/UCd18OhMfRmjMjzSHP7Zrzmw (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))
`

**Comment by brian-in-crawford** [comment]
Once again, I'm recording a morphing error message, in case somebody else comes across this thread. Without any upgrades to either gPodder or OpenSSL, all of the error messages produced when running gPodder now read 
`ERROR: format exception () missing 2 required positional arguments: 'value' and 'tb' `

There appears to be no difference in the error messages caused by running the first of the Python commands given above. However, the second one (the one disabling certificate checking) now fails with an error message that there is no module named requests.

When I get chance, I am going to try downgrading to the version of gPodder in the Ubuntu repositories. I can also try using a Windows 10 PC. I'll add another post when I've done that.

**Comment by brian-in-crawford** [comment]
I don't pretend to understand why, but upgrading to Mint 21 solved the problem. gPodder now works flawlessly again.

**Comment by auouymous** [comment]
Good to hear. It either upgraded something that was broken or repaired a corrupted system. I say corrupted because one command found the requests package while the other did not.
