### ISSUE TITLE
podcasts getting downloaded multiple times

### ISSUE THREAD

**Issue by arbizm** [gpodder/gpodder#1407]
There are a number of podcasts that will come up on  multiple days as being new.  I usually do a download once a day and every day, each podcast is either downloaded or marked as old, so I should have a clean feed.

I have discussed this issue with someone from the team before and they said that they based whether an episode is new upon the GUID that an episode has and that if it's a GUID problem, to report it to the individual publisher.  It seems that about 10% of the episodes are coming up as duplicates on a second+ day.  The duplicate podcasts have the same size in addition to title.

I can provide specifics with screenshots if need be.  If someone needs some specific info gleaned from the file, that is easy enough to do also.
The GUID approach may not be an optimal solution at this time.  When a significant percentage of podcasts, at least those in my feed, are coming up with errors, things have moved on from the original idea of using GUIDs.  Perhaps publishers are giving a new GUID based on the day or something but in the end, the initial assumptions of a unique GUID, once and only once, may no longer apply.

Perhaps the podcast title (and possibly podcast name) should be hashed (and turned into a GUID:  https://stackoverflow.com/questions/2190890/how-can-i-generate-a-guid-for-a-string) if a GUID format is easiest in the future.

**Comment by auouymous** [comment]
> I have discussed this issue with someone from the team before 

Previous conversation was #1337.

> Perhaps the podcast title (and possibly podcast name) should be hashed (and turned into a GUID

See https://github.com/kurtmckee/feedparser/issues/322#issuecomment-1213537730.

Gpodder uses the link if guid is not found and enclosure if no link. The title and description are far more unstable than those two fields. It really doesn't matter which order it uses to select alternate guids, there will always be a feed that breaks. We could fix the problem for your unstable feed and next week someone else will post an issue because one of their unstable feeds no longer works.

Getting the publisher to add a guid is the only way to fix the issue.

**Comment by arbizm** [comment]
I understand that the title can be unstable but when 4/9 of my downloads today are duplicates, it's no longer an unstable feed, it's an ecosystem change.  Yesterday, there were three duplicates, the day before that, three more and the day before that one was three.

Today it was only BBC feeds, pattern?  Checked the day before that and it was other publishers, same with one before that.  At a certain point, maybe the underlying way publishers are working in changing.  Maybe publishers are focused on how apple or spotify do things, I am unsure.  An example of this is long ago, most podcasts downloaded by RSS had something recognizable in the file name or title attributes.  In the last six months, there has been an increase in the number of gibberish titles 100 characters long as well as no title attributes.  Not just one publisher but a number of them.  Why is this?  I am unsure but it might, be due to how people are using/downloading podcasts.  Like I said, might, but it's been a very noticeable trend but not one for which I have kept data.

I understand how the title can change but when multiple ones per day occur, that's a problem.  I've checked the duplicates and they have have the same byte count (unsure if the GUID is in the file).  Maybe a hash of the file can be added and this info tracked and a note made to the user indicating the file is a duplicate and inquire keep/toss.  I've listened to a podcast and said, "I think I've already heard this one before" after it's been downloaded twice.  Maybe if you hash the downloaded file, there still is an attribute in the file that will give a different hash, I don't know, but it might be investigated and I can provide .mp3s for examination if desired.

**Comment by auouymous** [comment]
These images don't help me, can you please provide a feed URL?

**Comment by arbizm** [comment]
opml file attached with .txt as file type

[repeatDownloads.txt](https://github.com/gpodder/gpodder/files/9658248/repeatDownloads.txt)

**Comment by auouymous** [comment]
I have looked at and subscribed to The Documentary Podcast and Twenty Thousand Hertz feeds. Both of them use guid tags in the feed and should be stable, unless they are actually changing the guid which makes it an invalid feed. I'll let you know if it downloads anything twice.

Do you have any extensions enabled?

Do you have any warnings or errors in your log files?

Are you on Windows? If so, did you install from our binary or a third-party?

**Comment by computerfreak105** [comment]
I noticed that multiple downloads can happen if you close Gpodder during a download, but they may happen even if you don't interrupt anything and if you continue to use GPodder par example the next day.
As far I can tell it seems to be random. I will have to check the log files if it happens again.
I'm under windows 10, using GPodder only for youtube channels.

**Comment by arbizm** [comment]
No extensions installed.  On Windows 10 and installed from binary on webpage.  I'm not sure where the log is, looked around but am unsure.

The downloads aren't interrupted but it is used once a day.

**Comment by auouymous** [comment]
https://gpodder.github.io/docs/user-manual.html#default-gpodder-home-folder

There is a `Logs` folder at that location.

**Comment by arbizm** [comment]
For example, I see these errors by the hundreds for 20K Hertz and other podcasts (newer episodes is my folder in the 20k download folder):
2022-09-27 11:58:28,935 [gpodder.model] WARNING: Unknown external file: d:\gpodder\Twenty Thousand Hertz\TTH4155218717.mp3
2022-09-27 11:58:28,937 [gpodder.model] WARNING: Unknown external file: d:\gpodder\Twenty Thousand Hertz\newer episodes

I see many errors like for feeds that work fine:
2022-09-27 11:16:20,501 [gpodder.model] ERROR: Report this feed: Podcast http://astronomycast.com/podcast.xml, episode 
2022-09-27 11:16:20,523 [gpodder.model] WARNING: Unknown external file: d:\gpodder\Astronomy Cast\AstroCast-071022_nvb_20091228155936_nva_20091229160936_t_0a8fb08b1ca1b746e2a84.mp3

The warnings/errors above are consistent and numerous.  The error below is the last in the log, fwiw, I closed by 'x' in the upper right, so it's probably not an issue:

2022-09-27 11:58:55,765 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.10\site-packages\gpodder\gtkui\model.py", line 339, in _update_background
    if self.background_update.update():
  File "C:\Program Files (x86)\gPodder\lib\python3.10\site-packages\gpodder\gtkui\model.py", line 133, in update
    (model.C_PUBLISHED_TEXT, episode.cute_pubdate()),
  File "C:\Program Files (x86)\gPodder\lib\python3.10\site-packages\gpodder\model.py", line 827, in cute_pubdate
    result = util.format_date(self.published)
  File "C:\Program Files (x86)\gPodder\lib\python3.10\site-packages\gpodder\util.py", line 549, in format_date
    timestamp_date = time.localtime(timestamp)[:3]
OSError: [Errno 22] Invalid argument

2022-09-27 11:59:39,763 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.10\site-packages\gpodder\gtkui\model.py", line 339, in _update_background
    if self.background_update.update():
  File "C:\Program Files (x86)\gPodder\lib\python3.10\site-packages\gpodder\gtkui\model.py", line 133, in update
    (model.C_PUBLISHED_TEXT, episode.cute_pubdate()),
  File "C:\Program Files (x86)\gPodder\lib\python3.10\site-packages\gpodder\model.py", line 827, in cute_pubdate
    result = util.format_date(self.published)
  File "C:\Program Files (x86)\gPodder\lib\python3.10\site-packages\gpodder\util.py", line 549, in format_date
    timestamp_date = time.localtime(timestamp)[:3]
OSError: [Errno 22] Invalid argument

**Comment by auouymous** [comment]
```python
timestamp_date = time.localtime(timestamp)[:3]
OSError: [Errno 22] Invalid argument
```

This error is caused by an episode's publishing date not being an integer, and it would throw an sqlite error when trying to save to the database.


```
2022-09-27 11:58:28,935 [gpodder.model] WARNING: Unknown external file: d:\gpodder\Twenty Thousand Hertz\TTH4155218717.mp3
```

Do you have any `sqlite` errors in the log files? I'm thinking your database isn't being saved due to the invalid publishing date, or something else. You update the 20k feed which adds and downloads the 1-900-20K-HRTZ episode. You then quit gpodder but the episode doesn't get saved, so it throws the unknown file error next time you start gpodder. The next time you update 20k it adds and downloads that episode again because it was never stored in the database.

Feeds use ETag when updating so a feed that hasn't been updated won't get sent to gpodder. And if the broken feed isn't sent, its invalid publishing date won't cause gpodder to not save the database, and other feeds would properly save episodes.

**Comment by auouymous** [comment]
Ignore the HKEY errors.

Are you able to associate any of the unknown external files with episodes inside gpodder? Some of them like d:\gpodder\Tides of History\TOH_S4E109_ Lauren Bestock Interview_V2_ADS.mp3 might match episode titles. If so, could you create an `Extensions` folder in the same folder as the `Logs` folder, unzip http://borg.qzx.com/files/gpodder-debug-extension.zip to it and then enable the `DEBUG` extension? It adds a `DEBUG` item to the episode right-click menu that shows internal information for an episode. Is `download_filename` empty or set to something else?

**Comment by arbizm** [comment]
Not sure if it's relevant or something on the BBC side the "The Documentary Podcast" downloaded two identical episodes today and renamed the second one with a "...(2).mp3" at the end.


[2022-10-29.zip](https://github.com/gpodder/gpodder/files/9893725/2022-10-29.zip)
