### ISSUE TITLE
Any hack to get gpodder running without dbus?

### ISSUE THREAD

**Issue by clort81** [gpodder/gpodder#1415]
I do not use dbus on my system.  
I thought gpodder was able to run without dbus.  No? 
Running devuna linux ceres, from a current (2022-09-30) git clone I see:

```
gpodder$ bin/gpodder
1664547587.921619 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/media/sd/Projects/Ereader/gpodder/bin/gpodder", line 182, in <module>
    main()
  File "/media/sd/Projects/Ereader/gpodder/bin/gpodder", line 151, in main
    session_bus = dbus.SessionBus()
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

Traceback (most recent call last):
  File "/media/sd/Projects/Ereader/gpodder/bin/gpodder", line 182, in <module>
    main()
  File "/media/sd/Projects/Ereader/gpodder/bin/gpodder", line 151, in main
    session_bus = dbus.SessionBus()
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
```

```
grep -ri dbus *
bin/gpodder:    import dbus
bin/gpodder:    from dbus.mainloop.glib import DBusGMainLoop
bin/gpodder:    have_dbus = True
bin/gpodder:    Warning: python-dbus not found. Disabling D-Bus support.
bin/gpodder:    have_dbus = False
bin/gpodder:    if have_dbus:
bin/gpodder:        session_bus = dbus.SessionBus()
bin/gpodder:        if session_bus.name_has_owner(gpodder.dbus_bus_name):
bin/gpodder:                    gpodder.dbus_bus_name,
bin/gpodder:                    gpodder.dbus_gui_object_path)
bin/gpodder:                    dbus_interface=gpodder.dbus_interface)
bin/gpodder:            except dbus.exceptions.DBusException as dbus_exception:
makefile:GPODDER_SERVICE_FILE=share/dbus-1/services/org.gpodder.service
README.md:As an alternative to python-dbus on Mac OS X and Windows, you can use
README.md:the dummy (no-op) D-Bus module provided in "tools/fake-dbus-module/".
setup.cfg:known_third_party=dbus,gi,mutagen,cairo,requests,github3,jinja2,magic,youtube_dl,podcastparser,mygpoclient
setup.py:        freedesktop_folders = ('applications', 'dbus-1', 'icons', 'metainfo')
share/gpodder/examples/gpodder_mark_played.py:# Set the configuration options "audio_played_dbus" and "video_played_dbus"
share/gpodder/examples/gpodder_mark_played.py:import dbus
share/gpodder/examples/gpodder_mark_played.py:session_bus = dbus.SessionBus()
share/gpodder/examples/gpodder_mark_played.py:proxy = session_bus.get_object(gpodder.dbus_bus_name,
share/gpodder/examples/gpodder_mark_played.py:                               gpodder.dbus_gui_object_path)
share/gpodder/examples/gpodder_mark_played.py:interface = dbus.Interface(proxy, gpodder.dbus_interface)
share/gpodder/extensions/enqueue_in_mediaplayer.py:    OBJECT_DBUS = '/org/freedesktop/DBus'
share/gpodder/extensions/enqueue_in_mediaplayer.py:    INTERFACE_PROPS = 'org.freedesktop.DBus.Properties'
share/gpodder/extensions/enqueue_in_mediaplayer.py:    NAME_DBUS = 'org.freedesktop.DBus'
share/gpodder/extensions/enqueue_in_mediaplayer.py:    def init_dbus(self):
share/gpodder/extensions/enqueue_in_mediaplayer.py:        bus = gpodder.dbus_session_bus
share/gpodder/extensions/enqueue_in_mediaplayer.py:            dbus_interface=self.INTERFACE_PROPS)
share/gpodder/extensions/enqueue_in_mediaplayer.py:        bus = gpodder.dbus_session_bus
share/gpodder/extensions/enqueue_in_mediaplayer.py:        obj = bus.get_object(self.NAME_DBUS, self.OBJECT_DBUS)
share/gpodder/extensions/enqueue_in_mediaplayer.py:        cancel = obj.connect_to_signal('NameOwnerChanged', name_owner_changed, dbus_interface=self.NAME_DBUS)
share/gpodder/extensions/enqueue_in_mediaplayer.py:        if self.init_dbus():
share/gpodder/extensions/enqueue_in_mediaplayer.py:                                dbus_interface=self.INTERFACE_PLAYER,
share/gpodder/extensions/enqueue_in_mediaplayer.py:                                        dbus_interface=self.INTERFACE_PLAYER,
share/gpodder/extensions/enqueue_in_mediaplayer.py:    #  File "/usr/lib/totem/plugins/dbus/dbusservice.py", line 329, in OpenUri
share/gpodder/extensions/enqueue_in_mediaplayer.py:        # needs dbus, doesn't handle more than 1 episode
share/gpodder/extensions/enqueue_in_mediaplayer.py:        # and no point in using DBus when episode is not played.
share/gpodder/extensions/enqueue_in_mediaplayer.py:        if not hasattr(gpodder.dbus_session_bus, 'fake') and \
share/gpodder/extensions/mpris-listener.py:import dbus
share/gpodder/extensions/mpris-listener.py:import dbus.service
share/gpodder/extensions/mpris-listener.py:class MPRISDBusReceiver(object):
share/gpodder/extensions/mpris-listener.py:    INTERFACE_PROPS = 'org.freedesktop.DBus.Properties'
share/gpodder/extensions/mpris-listener.py:            except dbus.exceptions.DBusException:
share/gpodder/extensions/mpris-listener.py:            except dbus.exceptions.DBusException:
share/gpodder/extensions/mpris-listener.py:        props = dbus.Interface(proxy, self.INTERFACE_PROPS)
share/gpodder/extensions/mpris-listener.py:class gPodderNotifier(dbus.service.Object):
share/gpodder/extensions/mpris-listener.py:        dbus.service.Object.__init__(self, bus, path)
share/gpodder/extensions/mpris-listener.py:    @dbus.service.signal(dbus_interface='org.gpodder.player', signature='us')
share/gpodder/extensions/mpris-listener.py:    @dbus.service.signal(dbus_interface='org.gpodder.player', signature='uuus')
share/gpodder/extensions/mpris-listener.py:        if gpodder.dbus_session_bus is None:
share/gpodder/extensions/mpris-listener.py:            logger.debug("dbus session bus not available, not loading")
share/gpodder/extensions/mpris-listener.py:            self.session_bus = gpodder.dbus_session_bus
share/gpodder/extensions/mpris-listener.py:            self.rcvr = MPRISDBusReceiver(self.session_bus, self.notifier)
share/gpodder/extensions/rockbox_convert2mp4.py:# Requirements: apt-get install python-kaa-metadata  ffmpeg python-dbus
src/gpodder/gtkui/main.py:import dbus.service
src/gpodder/gtkui/main.py:from gpodder.dbusproxy import DBusPodcastsProxy
src/gpodder/gtkui/main.py:class gPodder(BuilderWidget, dbus.service.Object):
src/gpodder/gtkui/main.py:        dbus.service.Object.__init__(self, object_path=gpodder.dbus_gui_object_path, bus_name=bus_name)
src/gpodder/gtkui/main.py:        self.podcasts_proxy = DBusPodcastsProxy(lambda: self.channels,
src/gpodder/gtkui/main.py:        self.player_receiver = player.MediaPlayerDBusReceiver(self.on_played)
src/gpodder/gtkui/main.py:                    o = gpodder.dbus_session_bus.get_object(PANUCCI_NAME, PANUCCI_PATH)
src/gpodder/gtkui/main.py:                    i = dbus.Interface(o, PANUCCI_INTF)
src/gpodder/gtkui/main.py:    @dbus.service.method(gpodder.dbus_interface)
src/gpodder/gtkui/main.py:    @dbus.service.method(gpodder.dbus_interface)
src/gpodder/gtkui/main.py:    @dbus.service.method(gpodder.dbus_interface)
src/gpodder/gtkui/main.py:    @dbus.service.method(gpodder.dbus_interface)
src/gpodder/gtkui/app.py:import dbus
src/gpodder/gtkui/app.py:import dbus.service
src/gpodder/gtkui/app.py:from dbus.mainloop.glib import DBusGMainLoop
src/gpodder/gtkui/app.py:            dbus_main_loop = DBusGMainLoop(set_as_default=True)
src/gpodder/gtkui/app.py:            gpodder.dbus_session_bus = dbus.SessionBus(dbus_main_loop)
src/gpodder/gtkui/app.py:            self.bus_name = dbus.service.BusName(gpodder.dbus_bus_name, bus=gpodder.dbus_session_bus)
src/gpodder/gtkui/app.py:        except dbus.exceptions.DBusException as dbe:
src/gpodder/dbusproxy.py:# gpodder.dbusproxy - Expose Podcasts over D-Bus
src/gpodder/dbusproxy.py:import dbus
src/gpodder/dbusproxy.py:import dbus.service
src/gpodder/dbusproxy.py:class DBusPodcastsProxy(dbus.service.Object):
src/gpodder/dbusproxy.py:    Methods on DBusPodcastsProxy can be called by D-Bus clients. They implement
src/gpodder/dbusproxy.py:    # DBusPodcastsProxy(lambda: self.channels, self.on_itemUpdate_activate(), self.playback_episodes, self.download_episode_list, bus_name)
src/gpodder/dbusproxy.py:        dbus.service.Object.__init__(self,
src/gpodder/dbusproxy.py:                object_path=gpodder.dbus_podcasts_object_path,
src/gpodder/dbusproxy.py:    @dbus.service.method(dbus_interface=gpodder.dbus_podcasts, in_signature='', out_signature='a(ssss)')
src/gpodder/dbusproxy.py:    @dbus.service.method(dbus_interface=gpodder.dbus_podcasts, in_signature='s', out_signature='ss')
src/gpodder/dbusproxy.py:    @dbus.service.method(dbus_interface=gpodder.dbus_podcasts, in_signature='s', out_signature='a(sssssbbb)')
src/gpodder/dbusproxy.py:    @dbus.service.method(dbus_interface=gpodder.dbus_podcasts, in_signature='as', out_signature='(bs)')
src/gpodder/dbusproxy.py:    @dbus.service.method(dbus_interface=gpodder.dbus_podcasts, in_signature='', out_signature='')
src/gpodder/__init__.py:dbus_bus_name = 'org.gpodder'
src/gpodder/__init__.py:dbus_gui_object_path = '/gui'
src/gpodder/__init__.py:dbus_podcasts_object_path = '/podcasts'
src/gpodder/__init__.py:dbus_interface = 'org.gpodder.interface'
src/gpodder/__init__.py:dbus_podcasts = 'org.gpodder.podcasts'
src/gpodder/__init__.py:dbus_session_bus = None
grep: src/gpodder/__pycache__/__init__.cpython-310.pyc: binary file matches
src/gpodder/player.py:class MediaPlayerDBusReceiver(object):
src/gpodder/player.py:        self.bus = gpodder.dbus_session_bus
tools/fake-dbus-module/dbus/__init__.py:import dbus.exceptions
tools/fake-dbus-module/dbus/exceptions.py:class DBusException(Exception):
tools/fake-dbus-module/dbus/mainloop/glib.py:def DBusGMainLoop(*args, **kwargs):
tools/fake-dbus-module/dbus/glib.py:class DBusGMainLoop(object):
tools/fake-dbus-module/README:This directory contains a dummy "dbus" module for use with gPodder on platforms
tools/fake-dbus-module/README:where D-Bus is not available. The dummy "dbus" module will do nothing, but still
tools/win_installer/_base.sh:   # install fake dbus
tools/win_installer/_base.sh:    rsync -arv --delete "${REPO_CLONE}"/tools/fake-dbus-module/dbus "${site_packages_unix}/"
tools/win_installer/_base.sh:    rm -Rf "${MINGW_ROOT}"/share/dbus-1
tools/win_installer/_base.sh:           done < <(cd "${MINGW_ROOT}" && find . -type f -a \( -path '*gpodder*' -o -path '*/site-packages/dbus/*' -o -name gpo.exe \))
tools/mac-osx/release_on_mac.sh:cp share/dbus-1/services/org.gpodder.service{.in,}
tools/mac-osx/release_on_mac.sh:# copy fake dbus
tools/mac-osx/release_on_mac.sh:cp -r tools/fake-dbus-module/dbus $resources/lib/python3.9/site-packages/dbus
tools/mac-osx/release_on_mac.sh:rm -Rf "$resources"/share/dbus-1
``

**Comment by auouymous** [comment]
`bin/gpo` should work without dbus but it is required for `bin/gpodder` to access gtk. Have you tried installing `tools/fake-dbus-module/` as `dbus` in the system's site-packages? Or as `$HOME/.local/lib/python/site-packages/dbus` and then setting `PYTHONPATH=$HOME/.local/lib/python/site-packages`.

**Comment by clort81** [comment]
Thanks and Blessings to you auouymous!
This in-deed worked
```
mkdir -p $HOME/.local/lib/python/site-packages
cp -r tools/fake-dbus-module/dbus/ $HOME/.local/lib/python/site-packages
export PYTHONPATH=$HOME/.local/lib/python/site-packages
bin/gpodder
```

**Comment by auouymous** [comment]
> while gpodder was loading, firefox-esr became unresponsive

Is your firefox built with dbus disabled or was it slowing down due to cpu load?


> Perhaps dbus faking should be automated?

A distro could install the fake dbus module, and have it block dbus-python so both couldn't be installed together. But gpodder can't just install it, even local to the user because it would break other python packages. It also breaks the mpris extension in gpodder.

We should however mention the fake dbus module in the installation docs.

I just removed dbus-python after installing the fake dbus module. I'm unable to remove dbus because gtk+3 requires at-spi2-atk which requires dbus. Gpodder seems to work fine without dbus-python, but it does still launch dbus. I don't use MPRIS and can't say if it works or doesn't, I'd guess it doesn't since the fake dbus module can't communicate with dbus.

**Comment by clort81** [comment]
I can't tell how debian's firefox-esr-102.3.0esr interacts with dbus.  
In debian/rules the build-depends matches dbus with:
               libdbus-glib-1-dev, 
In debian/browser.mozconfig.in there are no tweaks to --disable-dbus.
I tried building firefox-esr with native flags but even limited to jobs=1, rust needs 14GB+ RAM to compile, and cheating with 32GB swap crashed it.

I suspect those running without dbus will be fine following your above instructions from a README.   Overall gpodder is running fine for me now.
.
Thank you very sincerely.

**Comment by auouymous** [comment]
I compile firefox ESR 102 on gentoo and -j3 only uses ~4GB of ram. Enabled features `gmp-autoupdate hwaccel openh264 system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-png system-webp`. Disabled features `-clang -dbus -debug -eme-free -geckodriver -hardened -jack -libproxy -lto -pgo -pulseaudio -screencast -selinux -sndio -system-python-libs -wayland -wifi`.

The fake dbus module is python only, so I'm not even sure its presence would alter firefox built with dbus. But I will mention it in the readme.
