### ISSUE TITLE
Gpodder completely broken after reinstall

### ISSUE THREAD

**Issue by TernaryC** [gpodder/gpodder#1436]
OS: Linux Mint 20.3 Cinnamon

I have been using the apt version of gpodder (3.10.15) for a while.
I decided to try upgrading to newest version, available on flatpak (3.11.0), however I ran into an issue with getting VLC to work (the exact issue is the same as #782, however it appears that no solution was ever found for it).
Upon uninstalling the flatpack version and reinstalling the older apt version, gpodder now crashes upon loading.
I have followed the [downgrading instructions](https://gpodder.github.io/docs/user-manual.html#moving-to-an-older-gpodder-release), to little effect.

The crash log (using gpodder -v) is pasted below.
I recognize a couple of these seem to be complaining that it can't find a log file, but the rest I don't know what to do with.

```
1667979532.511449 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/app.py", line 130, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 86, in __init__
    BuilderWidget.__init__(self, None, _builder_expose={'app': app})
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/interface/common.py", line 36, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/base.py", line 71, in __init__
    self.new()
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 165, in new
    self.channels = self.model.get_podcasts()
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1352, in get_podcasts
    self.children = self.db.load_podcasts(podcast_factory)
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 158, in load_podcasts
    cur = self.cursor()
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 99, in cursor
    return self.db.cursor()
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 90, in db
    schema.upgrade(self._db, self.database_file)
  File "/usr/lib/python3/dist-packages/gpodder/schema.py", line 225, in upgrade
    assert version == CURRENT_VERSION
AssertionError

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/app.py", line 130, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 86, in __init__
    BuilderWidget.__init__(self, None, _builder_expose={'app': app})
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/interface/common.py", line 36, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/base.py", line 71, in __init__
    self.new()
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 165, in new
    self.channels = self.model.get_podcasts()
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1352, in get_podcasts
    self.children = self.db.load_podcasts(podcast_factory)
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 158, in load_podcasts
    cur = self.cursor()
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 99, in cursor
    return self.db.cursor()
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 90, in db
    schema.upgrade(self._db, self.database_file)
  File "/usr/lib/python3/dist-packages/gpodder/schema.py", line 225, in upgrade
    assert version == CURRENT_VERSION
AssertionError
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_gpodder.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/app.py", line 130, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 86, in __init__
    BuilderWidget.__init__(self, None, _builder_expose={'app': app})
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/interface/common.py", line 36, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/base.py", line 71, in __init__
    self.new()
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 165, in new
    self.channels = self.model.get_podcasts()
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1352, in get_podcasts
    self.children = self.db.load_podcasts(podcast_factory)
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 158, in load_podcasts
    cur = self.cursor()
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 99, in cursor
    return self.db.cursor()
  File "/usr/lib/python3/dist-packages/gpodder/dbsqlite.py", line 90, in db
    schema.upgrade(self._db, self.database_file)
  File "/usr/lib/python3/dist-packages/gpodder/schema.py", line 225, in upgrade
    assert version == CURRENT_VERSION
AssertionError
1667979533.142375 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 1281, in on_treeview_query_tooltip
    if not getattr(treeview, TreeViewHelper.CAN_TOOLTIP) or x > 50 or (column is not None and column != treeview.get_columns()[0]):
AttributeError: 'TreeView' object has no attribute '_gpodder_can_tooltip'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 1281, in on_treeview_query_tooltip
    if not getattr(treeview, TreeViewHelper.CAN_TOOLTIP) or x > 50 or (column is not None and column != treeview.get_columns()[0]):
AttributeError: 'TreeView' object has no attribute '_gpodder_can_tooltip'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_gpodder.1000.crash'
```
(that final traceback is then repeated about 5 times)

**Comment by auouymous** [comment]
Are you sure the downgrade worked?

```
    assert version == CURRENT_VERSION
```

Ignore the tooltip errors, they happen whenever something else breaks. The log errors is probably something your system is doing, improperly. But that assertion means the code is older than the database.

```
sqlite3 ~/gPodder/Database 'select * from version;'
```

That command should output `7` for the 3.10.* database, and 8 for the 3.11.0 database.

**Comment by TernaryC** [comment]
That'll be the problem then; there were no v7 databases in my ~/gPodder folder when I performed the downgrade. I just used the oldest file present, which was still v8. Not sure what would've happened to the older v7 backup.

Luckily, deleting my databases entirely and letting gPodder regenerate the file worked fine enough. I had a .opml backup of my subscriptions, so nothing was lost.
