### ISSUE TITLE
Current git does not work with yt-dlp 2022.04.08

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#1439]
https://github.com/gpodder/gpodder/commit/642bf7e738036e6e7a68aa8b8c752a3c9d619f52 in #1382 causes the following error when downloading episodes with yt-dlp 2022.04.08:

```
Traceback (most recent call last):
  File "/home/test/git-gpodder-tmp/src/gpodder/download.py", line 900, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "/home/test/git-gpodder-tmp/share/gpodder/extensions/youtube-dl.py", line 109, in retrieve_resume
    opts['paths']['home'], opts['outtmpl']['default']) % info
TypeError: string indices must be integers
```

I haven't yet determined which version of yt-dlp is required to make #1382 work. This issue either needs to be fixed for older versions of yt-dlp, or gpodder needs to split `want_ytdl_version` to support separate versions for youtube-dl and yt-dlp, which I already had plans to do. @tpikonen Do you know an easy fix for this or should we require a newer yt-dlp?

**Comment by auouymous** [comment]
It is now possible for yt-dlp to require a different version than youtube-dl. However, yt-dlp 2022.04.08 is currently the latest available for Mint and Ubuntu.

**Comment by auouymous** [comment]
2022.5.18 also fails, and 2022.06.22.1 is the first version that works. #1440 should make gpodder work on both versions.
