### ISSUE TITLE
Issue downloading a podcast ( possible from Spreaker or from Global Audio Hosting )

### ISSUE THREAD

**Issue by tanja84dk** [gpodder/gpodder#1453]
I have just noticed that my podcast container has stopped being able to download this feed between the 19 October 2022 and 26 October 2022 possible due to an change in the spreaker api  or Global Audio Hosting

and I have tested on my windows laptop with the newest gPodder release and that fails with the feed completely ( Traceback snipped attached )

After looking into the rss feed I then noticed that it looks like the feed type perhaps has changed to a purely itunes based feed ( based on my limited understanding tbh )

I did also try to download it manually with yt-dlp manually from the terminal in my docker gpodder container and yt-dlp had no issue downloading the feed

But I do have to say that I see why yt-dlp should be needed in the first place ( even that I do have it installed ) because the audio files are listed in the feed and its just mp3

Feed: https://pod.link/doingit.rss ( redirects to https://podcast.global.com/show/3539182/episodes/feed )

Files listed as this tag:
<enclosure url="https://api.spreaker.com/download/episode/41290162/doing_it_se_03_ep_12_shani_and_tony_hart_1.mp3" length="46060280" type="audio/mpeg"/>

Traceback:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.10\site-packages\gpodder\download.py", line 874, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py", line 95, in retrieve_resume
    res = self._ytdl.fetch_video(self._url, outtmpl, self._my_hook)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py", line 310, in fetch_video
    return ydl.extract_info(url, download=True)
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1422, in extract_info
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1449, in wrapper
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 971, in report_error
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 914, in trouble
yt_dlp.utils.DownloadError: ERROR: [Spreaker] 40744838: Requested format is not available. Use --list-formats for a list of available formats
2023-01-04 19:49:39,312 [youtube-dl] ERROR: ERROR: [Spreaker] 41290162: Requested format is not available. Use --list-formats for a list of available formats
2023-01-04 19:49:39,312 [gpodder.download] ERROR: Download failed: ERROR: [Spreaker] 41290162: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1521, in __extract_info
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2624, in process_video_result
yt_dlp.utils.ExtractorError: [Spreaker] 41290162: Requested format is not available. Use --list-formats for a list of available formats
´´´

**Comment by tpikonen** [comment]
Commit c1981801c1 from #1383 should fix the issue with spreaker feeds. Can you upgrade to a version with it and test? Alternatively, you can disable the youtube-dl extension, and the feed should work (at the price of youtube feeds not working).

**Comment by tanja84dk** [comment]
Can confirm after testing that commit in a linux vm that at least for spreaker that does fix it. But unfortunally there si no way for me to upgrade without a installer ( at least on my windows laptop ) and the docker container is also using releases so I guess it will be a pain also ( because i'm not the maintainer of the docker image ).

So Ill guess the best is to wait for a new release within the next half a year

But it were also just because couldnt find any issue reports about spreaker that made me create the issue

**Comment by auouymous** [comment]
@tanja84dk https://ci.appveyor.com/project/elelay/gpodder/builds/45834367/artifacts has a Windows installer for the latest commit.

**Comment by tanja84dk** [comment]
@auouymous Thank you very much but unfortunally I'm actually facing another and almost bigger bug with that artifact so I'll chose to stay on the release and then when needed then deactivate the youtube-dl extension

But again in any way thank you very much both for the quick responces

**Comment by auouymous** [comment]
@tanja84dk What is the bug?

**Comment by auouymous** [comment]
```
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Bruger\\Documents\\gPodder\\Downloads\\Doing It! with Hannah Witton\\folder.jpg'
```

Do you have access to that file? Is gpodder running with some sort of restriction that prevents it from accessing it?

```
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/utils.py", line 5661, in windows_enable_vt_mode
OSError: [Errno 9] Bad file descriptor: 'CONOUT$'
```

The yt-dlp in gpodder failed while trying to enable virtualization. Are you running gpodder inside a container?

**Comment by tanja84dk** [comment]
> ```
> PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Bruger\\Documents\\gPodder\\Downloads\\Doing It! with Hannah Witton\\folder.jpg'
> ```
> 
> Do you have access to that file? Is gpodder running with some sort of restriction that prevents it from accessing it?

No there shouldn't be any restrictions at all also its the default Documents folder also the weird part is that it's only coverart.py there fails where the downloader is saving the files just fine just to show

```
 Directory of C:\Users\Bruger\Documents\gPodder\Downloads\Doing It! with Hannah Witton

01/05/2023  03:14 AM    <DIR>          .
01/05/2023  03:14 AM    <DIR>          ..
01/05/2023  02:22 AM         2,118,842 2019-05-24 - Doing It! with Hannah Witton - Doing It! with Hannah Witton Trailer.mp3
01/05/2023  02:22 AM       108,125,432 2019-05-29 - Doing It! with Hannah Witton - Chronic Pain and Losing Your Virginity _Late_ with Scarlett Curtis.mp3
01/05/2023  02:23 AM        92,194,054 2019-05-31 - Doing It! with Hannah Witton - Gay Teens in YA Books with Calum McSwiggan.mp3
01/05/2023  02:23 AM        89,144,571 2019-06-05 - Doing It! with Hannah Witton - Finding Out You're Pregnant at 5 Months and Mental Health with Yasmin Johal.mp3
01/05/2023  02:25 AM       104,577,880 2019-06-12 - Doing It! with Hannah Witton - Dating Advice and Social Media Etiquette with Gaby Dunn & Allison Raskin.mp3
01/05/2023  02:25 AM       114,942,766 2019-06-19 - Doing It! with Hannah Witton - Getting Married Young with Sierra Schultzzie.mp3
01/05/2023  02:26 AM        93,602,450 2019-06-26 - Doing It! with Hannah Witton - Surviving and Ending FGM with Nimko Ali.mp3
```

> 
> ```
>   File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/utils.py", line 5661, in windows_enable_vt_mode
> OSError: [Errno 9] Bad file descriptor: 'CONOUT$'
> ```
> 
> The yt-dlp in gpodder failed while trying to enable virtualization. Are you running gpodder inside a container?

No I installed it in windows from the artifact you linked and its installed as normal.
Now that I look further that path it is saying does not exist in my msys64 folder so I'm actually in a way thinking its sime remedense from the artifact compiling  that arent prober stripped specially now that I notice it says the user is appveyor and saying its in _gpodder_build_root ( used this installer as you linked https://ci.appveyor.com/project/elelay/gpodder/builds/45834367/artifacts )

I have it installed in the default "C:\Program Files (x86)\gPodder" folder as it recommended directly on my windows 10 Pro laptop
