### ISSUE TITLE
Unhandled exception for URL timeout

### ISSUE THREAD

**Issue by stuartmckim** [gpodder/gpodder#1469]
I'm getting the following error filling up my .xsession-errors file whenever gpodder tries to check for new files (I think) when we don't have a full internet connection.

I'm running version 3.10.17 (most recent version available in Debian bullseye/stable).

```
1675183096.961331 [gpodder.gtkui.main] ERROR: Error: <urlopen error timed out>
Traceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.9/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 2633, in update_feed_cache_proc
    channel.update(max_episodes=self.config.max_episodes_per_feed)
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1148, in update
    result = self.feed_fetcher.fetch_channel(self, max_episodes)
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 206, in fetch_channel
    res = self.fetch(url, channel.http_etag, channel.http_last_modified, max_episodes)
  File "/usr/lib/python3/dist-packages/gpodder/feedcore.py", line 242, in fetch
    return self._parse_feed(url, etag, modified, max_episodes)
  File "/usr/lib/python3/dist-packages/gpodder/feedcore.py", line 197, in _parse_feed
    stream = util.urlopen(url, headers)
  File "/usr/lib/python3/dist-packages/gpodder/util.py", line 1212, in urlopen
    return opener.open(request)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
```

**Comment by auouymous** [comment]
The error indicates exactly what you already know, gpodder has no connection to the internet. There is code to detect if gpodder can connect before it performs automatic updates, but I believe it was broken on some linux distros, and has since been fixed.

Newer versions of gpodder require dependencies your distro most likely lacks. You will need to update your distro or figure out how to install a newer gpodder and its dependencies, which will require their own dependency updates and so on...
