### ISSUE TITLE
More than 30 redirects exceeded error Libsyn.

### ISSUE THREAD

**Issue by venthewolf** [gpodder/gpodder#1552]
Gpodder throws an error that 30 redirects are exceeded when i try to sync to the following RSS feed: 
https://bellobard.libsyn.com/rss

I opened the feed in question, and apart from that my browser (Mozilla Firefox) is downloading the feed as a file the formatting seems fine.

Here is a snippet of the logfile when it happend:
```
2023-09-06 14:51:17,408 [gpodder.gtkui.main] ERROR: Error updating feed: Irish & Celtic Music Podcast: Exceeded 30 redirects.
Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.11\site-packages\gpodder\gtkui\main.py", line 2905, in update_feed_cache_proc
    new_episodes.extend(channel.update(max_episodes=self.config.limit.episodes))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\gPodder\lib\python3.11\site-packages\gpodder\model.py", line 1297, in update
    result = self.feed_fetcher.fetch_channel(self, max_episodes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\gPodder\lib\python3.11\site-packages\gpodder\model.py", line 213, in fetch_channel
    return self.fetch(url, channel.http_etag, channel.http_last_modified, max_episodes=max_episodes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\gPodder\lib\python3.11\site-packages\gpodder\feedcore.py", line 185, in fetch
    stream = util.urlopen(url, headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\gPodder\lib\python3.11\site-packages\gpodder\util.py", line 1264, in urlopen
    return s.get(url, headers=headers, data=data, timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.11/site-packages/requests/sessions.py", line 725, in send
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.11/site-packages/requests/sessions.py", line 725, in <listcomp>
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.11/site-packages/requests/sessions.py", line 191, in resolve_redirects
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

**Comment by auouymous** [comment]
Is this still an issue, because https://bellobard.libsyn.com/rss works fine for me in gpodder.

**Comment by venthewolf** [comment]
The issue seems to be cleared now
