### ISSUE TITLE
gpodder-3.11.1 stack trace with python3-3.12.0

### ISSUE THREAD

**Issue by andbenn** [gpodder/gpodder#1567]
Using Void Linux, recently both python3 and gpodder were updated..
`gpodder-3.11.1_2`
`python3-3.12.0_1`

When I launch, I get this stack trace and gpodder fails to start:

```
1697316527.979454 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/bin/gpodder", line 181, in <module>
    main()
  File "/usr/bin/gpodder", line 173, in main
    from gpodder.gtkui import app
  File "/usr/lib/python3.12/site-packages/gpodder/gtkui/app.py", line 31, in <module>
    from gpodder import core, util
  File "/usr/lib/python3.12/site-packages/gpodder/core.py", line 25, in <module>
    from gpodder import config, dbsqlite, extensions, model, util
  File "/usr/lib/python3.12/site-packages/gpodder/extensions.py", line 34, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

Traceback (most recent call last):
  File "/usr/bin/gpodder", line 181, in <module>
    main()
  File "/usr/bin/gpodder", line 173, in main
    from gpodder.gtkui import app
  File "/usr/lib/python3.12/site-packages/gpodder/gtkui/app.py", line 31, in <module>
    from gpodder import core, util
  File "/usr/lib/python3.12/site-packages/gpodder/core.py", line 25, in <module>
    from gpodder import config, dbsqlite, extensions, model, util
  File "/usr/lib/python3.12/site-packages/gpodder/extensions.py", line 34, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

```

**Comment by auouymous** [comment]
Python 3.12 removed that module, along with at least #1386. Void either doesn't verify packages work with newest Python versions or they missed gPodder. You will need to downgrade Python to 3.11 until we can migrate, and report this to Void Linux.

**Comment by andbenn** [comment]
Thanks for the quick check and reply.  I've created an issue for Void Linux at https://github.com/void-linux/void-packages/issues/46683
