### ISSUE TITLE
Tag downloaded files extension ERROR name 'file' is not defined

### ISSUE THREAD

**Issue by politas** [gpodder/gpodder#1584]
gPodder 3.11.4 (2023-10-11)

```
2023-11-12 07:48:44,869 [gpodder.extensions] ERROR: Error in /usr/share/gpodder/extensions/tagging.py in on_episode_downloaded: name 'file' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gpodder/extensions.py", line 77, in handler
    cb_res = callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/gpodder/extensions/tagging.py", line 213, in on_episode_downloaded
    self.write_info2file(info, episode)
  File "/usr/share/gpodder/extensions/tagging.py", line 297, in write_info2file
    audio.insert_coverart()
  File "/usr/share/gpodder/extensions/tagging.py", line 155, in insert_coverart
    p = self.get_cover_picture(self.cover)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/gpodder/extensions/tagging.py", line 139, in get_cover_picture
    f = file(cover)
        ^^^^
```

**Comment by tpikonen** [comment]
Thanks for the report, this is fixed in the PR referenced above, but it may take a while to get it reviewed and merged.
