### ISSUE TITLE
Gpodder doesn't start anymore on Ubuntu 24.04 : ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by Valeryan24** [gpodder/gpodder#1614]
Hi, since a few days, Gpodder (last deb version from repositery) doesn't launch anymore on Ubuntu 24.04 (beta version in development) : 
"[gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/bin/gpodder", line 181, in <module>
    main()
  File "/usr/bin/gpodder", line 173, in main
    from gpodder.gtkui import app
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/app.py", line 31, in <module>
    from gpodder import core, util
  File "/usr/lib/python3/dist-packages/gpodder/core.py", line 25, in <module>
    from gpodder import config, dbsqlite, extensions, model, util
  File "/usr/lib/python3/dist-packages/gpodder/extensions.py", line 34, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

Traceback (most recent call last):
  File "/usr/bin/gpodder", line 181, in <module>
    main()
  File "/usr/bin/gpodder", line 173, in main
    from gpodder.gtkui import app
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/app.py", line 31, in <module>
    from gpodder import core, util
  File "/usr/lib/python3/dist-packages/gpodder/core.py", line 25, in <module>
    from gpodder import config, dbsqlite, extensions, model, util
  File "/usr/lib/python3/dist-packages/gpodder/extensions.py", line 34, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'"

There is a major bug related to AppArmor in Ubuntu, which prevents many programs to start, could it be related to this or is it something different ?

https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844

AppArmor user namespace creation restrictions on Ubuntu cause many applications  to crash with SIGTRAP or SIGSEGV.
Ubuntu recently decided to disable unprivileged access to user namespaces. You can find more information it about it here:
https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces

"You can enable user namespaces by either making a apparmor profile for your installs, making sure the directory where the program is installed is correct in the profile, or by just enabling user namespaces for your system."

Thanks !

**Comment by auouymous** [comment]
You are using python 3.12 and gpodder 3.11.4 does not support it. You need to have the package maintainer apply https://github.com/gpodder/gpodder/pull/1571/commits/dd9b594d24a541c0f1d3b096e47b6d7f1c11ca7e and https://github.com/gpodder/gpodder/pull/1571/commits/510de4b3a0b0444231f87bc6cb60527817847865 to make it work.

**Comment by tmancill** [comment]
> You are using python 3.12 and gpodder 3.11.4 does not support it. You need to have the package maintainer apply [dd9b594](https://github.com/gpodder/gpodder/commit/dd9b594d24a541c0f1d3b096e47b6d7f1c11ca7e) and [510de4b](https://github.com/gpodder/gpodder/commit/510de4b3a0b0444231f87bc6cb60527817847865) to make it work.

I will apply the patches and upload to Debian.  Will there be a released version that includes these changes soon?

**Comment by tmancill** [comment]
Updated Debian version tested against Python 3.12:  https://tracker.debian.org/news/1512534/accepted-gpodder-3113-2-source-into-unstable/

**Comment by elelay** [comment]
would it make sense to release an unstable ppa from master ?

**Comment by auouymous** [comment]
I would like to get a release out soon. I'm going to try applying a patch only to the Windows build that removes the python 3.12 support in hopes it fixes the build.

**Comment by Iizuki** [comment]
This landed on Arch too. Is there a lot of work to be done?

**Comment by patrickuhlmann** [comment]
It works again on Arch if the file "/usr/lib/python3.12/site-packages/gpodder/extensions.py" is edited according to https://github.com/gpodder/gpodder/commit/dd9b594d24a541c0f1d3b096e47b6d7f1c11ca7e. Would be nice if this could be integrated tough.

**Comment by christian-heusel** [comment]
I have just pushed a fix to the Arch Linux package, next time also feel free to report this earlier to our Bugtracker aswell (was [submitted yesterday](https://gitlab.archlinux.org/archlinux/packaging/packages/gpodder/-/issues/1#note_184072= when there already is a commit to backport.

**Comment by barracuda156** [comment]
> You are using python 3.12 and gpodder 3.11.4 does not support it. You need to have the package maintainer apply [dd9b594](https://github.com/gpodder/gpodder/commit/dd9b594d24a541c0f1d3b096e47b6d7f1c11ca7e) and [510de4b](https://github.com/gpodder/gpodder/commit/510de4b3a0b0444231f87bc6cb60527817847865) to make it work.

Should these be used only with python312 or it gonna still work with earlier ones too?

**Comment by auouymous** [comment]
@barracuda156 They work with 3.11. The importlib patch needs 3.5, so it will work with all supported versions. I assume setuptools has always had `setup`, so it should also work, but I don't know.

**Comment by barracuda156** [comment]
Thank you. On the next update we can make the patch unconditional then. For now I just added it when building with python 3.12: https://github.com/macports/macports-ports/commit/d78f2d5b5291fcf4e4bb7507261df28d9b02f02d
