### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by SuminTchen** [gpodder/gpodder#1690]
Losing all my podcasts when I upgrade  to the latest version?  You've got to be kidding, but maybe I did something wrong.

**Comment by elelay** [comment]
Indeed, not likely.
Please give us additional details, like platform, old version, what installation package you used.

**Comment by SuminTchen** [comment]
HI Eric,


Thanks for your quick reply.  I upgraded from 3.11.4 to 3.11.5.  Windows 11.  Download package from here:  https://gpodder.github.io/


Let me know if you would like any additional info.


Regards,

S.


________________________________

**Comment by masoudd** [comment]
Did you install the installer or the portable version? Installed version uses `Documents\gPodder\Downloads`. Portable version uses its own settings directory. For the settings and podcasts to carry over you need to have installed the installer version for both the old and new version. Otherwise you need to copy the `Database` and `Settings.json` manually to the right directory.

**Comment by SuminTchen** [comment]
HI Masoud,


I believe that I used the installer version for both.  But maybe I made an error.


Many thanks,

Sumin


________________________________

**Comment by elelay** [comment]
Hi Sumin,
please can you run gpodder again and take a look at `Documents\gPodder\Logs`? There should be a file named after Today.
Its contents might help us find the error...
Also see https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows for running in verbose mode if necessary.
Thanks

**Comment by SuminTchen** [comment]
HI Eric,


Unfortunately, I've uninstalled gPodder.  I'm getting ready to go away for a month and will not likely have a chance to reinstall and test.


Sorry,

Sumin


________________________________

**Comment by Nemesis11p** [comment]
I upgraded from 3.11.4 to 3.11.5. Instalation Package. Windows 10. The application never starts and the process disappears seconds later.
Error log running "gpodder.exe -v":
---------------------------------------------------------------------------
2024-12-24 23:24:31,629 [enqueue_in_mediaplayer] WARNING: Win32 player not found: HKEY_CLASSES_ROOT\Winamp.File\shell\Enqueue\command ([WinError 2] The system cannot find the file specified)
2024-12-24 23:24:31,630 [enqueue_in_mediaplayer] WARNING: Win32 player not found: HKEY_CLASSES_ROOT\foobar2000.MP3\shell\enqueue\command ([WinError 2] The system cannot find the file specified)
2024-12-24 23:24:35,630 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Winamp.File\shell\Play\command ([WinError 2] The system cannot find the file specified)
2024-12-24 23:24:35,631 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Applications\foobar2000.exe\shell\open\command ([WinError 2] The system cannot find the file specified)
2024-12-24 23:24:35,632 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\WMP11.AssocFile.MP3\shell\open\command ([WinError 2] The system cannot find the file specified)
2024-12-24 23:24:35,633 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\QuickTime.mp3\shell\open\command ([WinError 2] The system cannot find the file specified)
2024-12-24 23:29:08,557 [gpodder.log] DEBUG: ==== gPodder starts up (ui=gtk) ===
2024-12-24 23:29:09,229 [gpodder.registry] DEBUG: Registering download_url resolver: <function youtube_real_download_url at 0x03db4e88>
2024-12-24 23:29:09,234 [gpodder.registry] DEBUG: Registering download_url resolver: <function vimeo_real_download_url at 0x03dc9b18>
2024-12-24 23:29:09,779 [gpodder.sync] INFO: iPod sync not available
2024-12-24 23:29:09,784 [gpodder.sync] INFO: eyeD3 MP3 not available
2024-12-24 23:29:09,916 [gpodder.gtkui.shownotes] INFO: No WebKit2 gobject bindings, so no HTML shownotes
2024-12-24 23:29:10,011 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/site-packages/gpodder_launch/gpodder.py", line 175, in main
  File "C:\Program Files (x86)\gPodder\lib\python3.12\site-packages\gpodder\gtkui\app.py", line 360, in main
    gp.run()
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/site-packages/gi/overrides/Gio.py", line 41, in run
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/contextlib.py", line 137, in __enter__
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/site-packages/gi/_ossighelper.py", line 253, in running
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/contextlib.py", line 137, in __enter__
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/site-packages/gi/_ossighelper.py", line 77, in wakeup_on_signal
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/socket.py", line 642, in _fallback_socketpair
ConnectionError: Unexpected peer connection
---------------------------------------------------------------------------



After renaming the files "Database" to "Database_" and "Settings.json" to "Settings.json_".
Error log running "gpodder.exe -v":
---------------------------------------------------------------------------
2024-12-24 23:35:41,605 [gpodder.log] DEBUG: ==== gPodder starts up (ui=gtk) ===
2024-12-24 23:35:42,725 [gpodder.registry] DEBUG: Registering download_url resolver: <function youtube_real_download_url at 0x03d54e88>
2024-12-24 23:35:42,734 [gpodder.registry] DEBUG: Registering download_url resolver: <function vimeo_real_download_url at 0x03d69b18>
2024-12-24 23:35:43,446 [gpodder.sync] INFO: iPod sync not available
2024-12-24 23:35:43,450 [gpodder.sync] INFO: eyeD3 MP3 not available
2024-12-24 23:35:43,575 [gpodder.gtkui.shownotes] INFO: No WebKit2 gobject bindings, so no HTML shownotes
2024-12-24 23:35:43,696 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/site-packages/gpodder_launch/gpodder.py", line 175, in main
  File "C:\Program Files (x86)\gPodder\lib\python3.12\site-packages\gpodder\gtkui\app.py", line 360, in main
    gp.run()
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/site-packages/gi/overrides/Gio.py", line 41, in run
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/contextlib.py", line 137, in __enter__
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/site-packages/gi/_ossighelper.py", line 253, in running
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/contextlib.py", line 137, in __enter__
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/site-packages/gi/_ossighelper.py", line 77, in wakeup_on_signal
  File "C:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.12/socket.py", line 642, in _fallback_socketpair
ConnectionError: Unexpected peer connection
---------------------------------------------------------------------------

Best Regards.

**Comment by masoudd** [comment]
@Nemesis11p That's strange. Can you make sure the installer is downloaded correctly? [from release page](https://github.com/gpodder/gpodder/releases/tag/3.11.5):

    windows-gpodder-3.11.5-installer.exe
    md5:2e09083e15a5f189464b708fad52009d
    sha256:212a88b68469e9b83e920d950b260ce6a9eea3fae913e6a3bff9833ab31bf6a1

And since the error originates from low level python networking library, do you have any unusual network connection setup?
