### ISSUE TITLE
Unicode path not supported for GPODDER_HOME

### ISSUE THREAD

**Issue by ahiskali** [gpodder/gpodder#202]
I get that error when I try to run gpodder.exe.

Running gpo.exe in console returns this: 
```
C:\Program Files (x86)\gPodder>gpo.exe
Storing data in E:\ahiskali\╧юфърёЄ√ (GPODDER_HOME is set)

gPodder 3.9.3 "Whacketts" (2016-12-22) - http://gpodder.org/
? 2005-2016 Thomas Perl and the gPodder Team
License: GNU General Public License, version 3 or later

Entering interactive shell. Type 'help' for help.
Press Ctrl+D (EOF) or type 'quit' to quit.

1483584940.380000 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "bin\gpo", line 898, in <module>
    cli._shell()
  File "bin\gpo", line 758, in _shell
    cli._run_cleanups()
  File "bin\gpo", line 230, in _run_cleanups
    old_episodes = list(common.get_expired_episodes(self._model.get_podcasts(), self._config))
  File "C:\Program Files (x86)\gPodder\src\gpodder\model.py", line 1239, in get_podcasts
    self.children = self.db.load_podcasts(podcast_factory)
  File "C:\Program Files (x86)\gPodder\src\gpodder\dbsqlite.py", line 159, in load_podcasts
    cur = self.cursor()
  File "C:\Program Files (x86)\gPodder\src\gpodder\dbsqlite.py", line 103, in cursor
    return self.db.cursor()
  File "C:\Program Files (x86)\gPodder\src\gpodder\dbsqlite.py", line 91, in db
    self._db = sqlite.connect(self.database_file, check_same_thread=False)
OperationalError: unable to open database file

Traceback (most recent call last):
  File "bin\gpo", line 898, in <module>
    cli._shell()
  File "bin\gpo", line 758, in _shell
    cli._run_cleanups()
  File "bin\gpo", line 230, in _run_cleanups
    old_episodes = list(common.get_expired_episodes(self._model.get_podcasts(), self._config))
  File "C:\Program Files (x86)\gPodder\src\gpodder\model.py", line 1239, in get_podcasts
    self.children = self.db.load_podcasts(podcast_factory)
  File "C:\Program Files (x86)\gPodder\src\gpodder\dbsqlite.py", line 159, in load_podcasts
    cur = self.cursor()
  File "C:\Program Files (x86)\gPodder\src\gpodder\dbsqlite.py", line 103, in cursor
    return self.db.cursor()
  File "C:\Program Files (x86)\gPodder\src\gpodder\dbsqlite.py", line 91, in db
    self._db = sqlite.connect(self.database_file, check_same_thread=False)
sqlite3.OperationalError: unable to open database file
```

**Comment by vossad01** [comment]
> Storing data in E:\ahiskali\╧юфърёЄ√ (GPODDER_HOME is set)

Do you actually have a folder called **╧юфърёЄ√**?

I am wondering if gpodder is handling the encoding wrong for a unicode file path which ultimately causes the failure.

**Comment by ahiskali** [comment]
@vossad01 no, it has cyrillic symbols. I just changed it in regedit and everything worked. Thank you.

**Comment by vossad01** [comment]
Ahh, so that would make this a bug in that little Windows-only piece of gPodder that provides a GUI for setting GPODDER_HOME!  Or, I assume that is how you set GPODDER_HOME initially.

**Comment by ahiskali** [comment]
Yep, I changed it in the window that appeared after installation.

**Comment by thp** [comment]
We'll have to look into this, not sure when there's time, but for now the solution as you said is that you change it in regedit. With that said, do you now have a working folder with cyrillic names? (i.e. is the application working, and it was just the registry entry that we put in wrong, or did you change the folder name and the registry entry to using ASCII-only characters?)

**Comment by elelay** [comment]
gPodder Home directory and episodes can now have Unicode in their name since gPodder 3.10.2.
Please try with the latest 3.10.3 release.

**Comment by elelay** [comment]
@ahiskali please reopen if it doesn't work for you
