### ISSUE TITLE
Codify way to mark extensions Python 2 vs Python 3 compatible

### ISSUE THREAD

**Issue by elelay** [gpodder/gpodder#252]
Does it make sense to be able to mark extensions gtk2/gtk3 only?
Especially for external extensions where I will want to have both versions in same profile, going back and forth between master and gtk3.

If so, adding `gpodder.ui.gtk3 = True` to `bin/gPodder` and using `__only_for__ = 'gtk3'` would be the easiest way. Maybe better use gpodder.ui.python2/3?

**Comment by vossad01** [comment]
I think given the existence of external extensions, some way to mark an extension as Python 3 compatible is needed.  Anything that can be done to mitigate user issues and confusion over the transition really.

I agree it would be more relevant to describe it based on the Python version compatibility rather than the GTK version otherwise. (For that matter I'd rename the branch if it wouldn't affect anyone's development.)

**Comment by vossad01** [comment]
I think there may be an instance of this incompatibility occurring in the log from #274 (unrelated)

> 2017-04-17 20:04:50,922 [gpodder.extensions] ERROR: Cannot load ubuntu_appindicator from /usr/src/gpodder/share/gpodder/extensions/ubuntu_appindicator.py: No module named 'appindicator'
Traceback (most recent call last):
  File "/usr/src/gpodder/src/gpodder/extensions.py", line 251, in set_enabled
    self.load_extension()
  File "/usr/src/gpodder/src/gpodder/extensions.py", line 294, in load_extension
    (extension, 'r', imp.PY_SOURCE))
  File "/usr/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/src/gpodder/share/gpodder/extensions/ubuntu_appindicator.py", line 19, in <module>
    import appindicator
ImportError: No module named 'appindicator'

We also know #160 is would benefit from this.

**Comment by vossad01** [comment]
Though about this a little more and it occurred to me: won't the Python interpreter process the entire file when the extension is loaded?  So if Python 3 incompatible syntax is used, it would fail even before it has a chance to read a member saying it is incompatible?

**Comment by elelay** [comment]
No: the extension file is first processed as text to [extract metadata](https://github.com/gpodder/gpodder/blob/master/src/gpodder/extensions.py#L232). So adding python2/python3 UIs makes sense.
