### ISSUE TITLE
Shownotes: AttributeError: 'NoneType' object has no attribute 'title'

### ISSUE THREAD

**Issue by vossad01** [gpodder/gpodder#280]
I observed the following exception which put gPodder into an odd state while I was testing #266, but have not reproduced it.

I'm guessing we will probably need to filter out `None` in `get_selected_episodes`

```
1492524887.464470 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/home/user/dev/gpodder/src/gpodder/gtkui/main.py", line 990, in on_episode_list_selection_changed
    self.shownotes_object.set_episodes(self.get_selected_episodes())
  File "/home/user/dev/gpodder/src/gpodder/gtkui/shownotes.py", line 85, in set_episodes
    heading = episode.title
AttributeError: 'NoneType' object has no attribute 'title'
```

**Comment by elelay** [comment]
Fixed by #291.
