### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by binaryplease** [gpodder/gpodder#301]
Hi,  gpodder crashed with this error on startup:

```❯ gpodder
1494330068.774426 [gpodder.util] WARNING: html5lib not found, falling back to HTMLParser
1494330068.874485 [gpodder.sync] WARNING: Could not find eyed3.mp3
1494330068.938172 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/bin/gpodder", line 159, in <module>
    main()
  File "/usr/bin/gpodder", line 154, in main
    main.main(options)
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/main.py", line 3487, in main
    gp = gPodder(bus_name, core.Core(UIConfig, model_class=Model), options)
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/main.py", line 121, in __init__
    BuilderWidget.__init__(self, None)
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/interface/common.py", line 38, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, **kwargs)
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/base.py", line 66, in __init__
    self.new()
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/main.py", line 229, in new
    self.channels = self.model.get_podcasts()
  File "/usr/lib/python2.7/site-packages/gpodder/model.py", line 1239, in get_podcasts
    self.children = self.db.load_podcasts(podcast_factory)
  File "/usr/lib/python2.7/site-packages/gpodder/dbsqlite.py", line 159, in load_podcasts
    cur = self.cursor()
  File "/usr/lib/python2.7/site-packages/gpodder/dbsqlite.py", line 103, in cursor
    return self.db.cursor()
  File "/usr/lib/python2.7/site-packages/gpodder/dbsqlite.py", line 94, in db
    schema.upgrade(self._db, self.database_file)
  File "/usr/lib/python2.7/site-packages/gpodder/schema.py", line 209, in upgrade
    assert version == CURRENT_VERSION
AssertionError

Traceback (most recent call last):
  File "/usr/bin/gpodder", line 159, in <module>
    main()
  File "/usr/bin/gpodder", line 154, in main
    main.main(options)
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/main.py", line 3487, in main
    gp = gPodder(bus_name, core.Core(UIConfig, model_class=Model), options)
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/main.py", line 121, in __init__
    BuilderWidget.__init__(self, None)
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/interface/common.py", line 38, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, **kwargs)
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/base.py", line 66, in __init__
    self.new()
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/main.py", line 229, in new
    self.channels = self.model.get_podcasts()
  File "/usr/lib/python2.7/site-packages/gpodder/model.py", line 1239, in get_podcasts
    self.children = self.db.load_podcasts(podcast_factory)
  File "/usr/lib/python2.7/site-packages/gpodder/dbsqlite.py", line 159, in load_podcasts
    cur = self.cursor()
  File "/usr/lib/python2.7/site-packages/gpodder/dbsqlite.py", line 103, in cursor
    return self.db.cursor()
  File "/usr/lib/python2.7/site-packages/gpodder/dbsqlite.py", line 94, in db
    schema.upgrade(self._db, self.database_file)
  File "/usr/lib/python2.7/site-packages/gpodder/schema.py", line 209, in upgrade
    assert version == CURRENT_VERSION
AssertionError

```

I'm running Arch Linux, installed gpodder from AUR, everything up to date.

**Comment by elelay** [comment]
Hi,
have you tried running gPodder from a git checkout? This would explain the error: the DB version would be greater than the one supported in the AUR code.

Assuming your GPODDER_HOME is  `~/gPodder`, can you run this?
```
sqlite3 ~/gPodder/Database 'select version from version;'
```
**6** is the version for gpodder 3.9.3 (AUR version)
**7** is the development version (master)

Also, could you also provide us with the output of `gpodder --version`?

Thanks,

**Comment by boada** [comment]
I'm also getting this error. The version of gpodder cloned from git seems to start no problem. 

....@....$ sqlite3 ~/gPodder/Database 'select version from version;'
7
....@....$ gpodder --version
gpodder 3.9.3

**Comment by adamvoss** [comment]
Database upgrades in gPodder are not designed to be backwards compatible; I think making them so is probably out of scope.  Once you upgrade to a new DB version, the only semi-automatic way to return to an earlier gPodder version is to use the [automatically created] database backup from before the upgrade.

Do any of the reporters have a recommendation on what is to be changed/implemented for this ticket?  As is, I don't see what should be done.
