### ISSUE TITLE
gpodder and debian jessie

### ISSUE THREAD

**Issue by dodddummy** [gpodder/gpodder#311]
Installed gpodder by simple apt-get install gpodder.  This is on a new installation of debian jessie.  Are there dependencies missing from the debian package?

Here's the output.
Traceback (most recent call last):
  File "./gpodder", line 159, in <module>
    main()
  File "./gpodder", line 154, in main
    main.main(options)
  File "/home/jason/bin/gpodder/src/gpodder/gtkui/main.py", line 3535, in main
    gp = gPodder(bus_name, core.Core(UIConfig, model_class=Model), options)
  File "/home/jason/bin/gpodder/src/gpodder/gtkui/main.py", line 121, in __init__
    BuilderWidget.__init__(self, None)
  File "/home/jason/bin/gpodder/src/gpodder/gtkui/interface/common.py", line 38, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, **kwargs)
  File "/home/jason/bin/gpodder/src/gpodder/gtkui/base.py", line 66, in __init__
    self.new()
  File "/home/jason/bin/gpodder/src/gpodder/gtkui/main.py", line 229, in new
    self.channels = self.model.get_podcasts()
  File "/home/jason/bin/gpodder/src/gpodder/model.py", line 1239, in get_podcasts
    self.children = self.db.load_podcasts(podcast_factory)
  File "/home/jason/bin/gpodder/src/gpodder/dbsqlite.py", line 159, in load_podcasts
    cur = self.cursor()
  File "/home/jason/bin/gpodder/src/gpodder/dbsqlite.py", line 103, in cursor
    return self.db.cursor()
  File "/home/jason/bin/gpodder/src/gpodder/dbsqlite.py", line 94, in db
    schema.upgrade(self._db, self.database_file)
  File "/home/jason/bin/gpodder/src/gpodder/schema.py", line 205, in upgrade
    version = db.execute('SELECT version FROM version').fetchone()[0]

**Comment by dodddummy** [comment]
The issue was that I copied over a gpodder folder from another computer, also running debian jessie.  But the version seems to be different.  Would be nice if this failed more gracefully but restoring an older version of the database file worked well enough.

**Comment by adamvoss** [comment]
@dodddummy I think some of the output may be missing.  You have provided the stack trace so we know _where_ the issue happened, but we don't have the exception message saying _what_ the error was.  If you still have access could you provide the exception text?  It can probably be found in **~/gPodder/Logs** if you are using the default configuration, and is probably on the next line after the part you copied.

Based on your description I can guess what it says, but it is generally better not to make assumptions.  Thanks!

**Comment by tmancill** [comment]
@dodddummy I'm the Debian maintainer of the gpodder package and am also curious about the problem you encountered.  The version of gPodder release with Debian jessie is [3.8.1](https://packages.debian.org/jessie/x11/gpodder) and the upgrade from the 2.x -> 3.x database format occurred during the wheezy -> jessie upgrade cycle and should have been accompanied by this NEWS message:

```
gpodder (3.5.0-1) unstable; urgency=low

 gPodder 3.x uses a new configuration file format.  Users upgrading
 from gPodder 2.x to 3.x can make use of the gpodder-migrate2tres
 utility to migrate their configuration files.

 -- tony mancill <tmancill@debian.org>  Fri, 08 Mar 2013 21:21:00 -0800
```

In any event, there should be more in the stack trace if the problem is still reproducible.
