### ISSUE TITLE
Uncaught exception when searching for podcasts

### ISSUE THREAD

**Issue by netzverweigerer** [gpodder/gpodder#327]
gpo

gPodder 3.9.3 "Whacketts" (2016-12-22) - http://gpodder.org/
© 2005-2016 Thomas Perl and the gPodder Team
License: GNU General Public License, version 3 or later

Entering interactive shell. Type 'help' for help.
Press Ctrl+D (EOF) or type 'quit' to quit.

gpo> search foo
1499278723.003215 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "./bin/gpo", line 898, in <module>
    cli._shell()
  File "./bin/gpo", line 786, in _shell
    self._parse(args)
  File "./bin/gpo", line 872, in _parse
    return self._checkargs(func, command_line)
  File "./bin/gpo", line 814, in _checkargs
    return func(*command_line)
  File "./bin/gpo", line 661, in search
    results = directory.search(query)
  File "/home/armin/gpodder/src/gpodder/my.py", line 659, in search
    for p in self.client.search_podcasts(query)
  File "/home/armin/.local/lib/python2.7/site-packages/mygpoclient/public.py", line 160, in search_podcasts
    return [simple.Podcast.from_dict(x) for x in self._client.GET(uri)]
  File "/home/armin/.local/lib/python2.7/site-packages/mygpoclient/http.py", line 135, in GET
    return self._request('GET', uri, None)
  File "/home/armin/.local/lib/python2.7/site-packages/mygpoclient/http.py", line 130, in _request
    raise UnknownResponse(http_error.code)
UnknownResponse: 503

Traceback (most recent call last):
  File "./bin/gpo", line 898, in <module>
    cli._shell()
  File "./bin/gpo", line 786, in _shell
    self._parse(args)
  File "./bin/gpo", line 872, in _parse
    return self._checkargs(func, command_line)
  File "./bin/gpo", line 814, in _checkargs
    return func(*command_line)
  File "./bin/gpo", line 661, in search
    results = directory.search(query)
  File "/home/armin/gpodder/src/gpodder/my.py", line 659, in search
    for p in self.client.search_podcasts(query)
  File "/home/armin/.local/lib/python2.7/site-packages/mygpoclient/public.py", line 160, in search_podcasts
    return [simple.Podcast.from_dict(x) for x in self._client.GET(uri)]
  File "/home/armin/.local/lib/python2.7/site-packages/mygpoclient/http.py", line 135, in GET
    return self._request('GET', uri, None)
  File "/home/armin/.local/lib/python2.7/site-packages/mygpoclient/http.py", line 130, in _request
    raise UnknownResponse(http_error.code)
mygpoclient.http.UnknownResponse: 503

This happens with the most recent version of gpodder as well as the version available in the Repositories of Debian Buster and Ubuntu 17.04.

**Comment by adamvoss** [comment]
The response shown in what you posted is 503.  I think you will need to look into which podcast is causing the issue.

> 503 Service Unavailable
>    The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state.

I think you will need to look into which podcast is causing the issue.

**Comment by elelay** [comment]
gpodder.net is down.
The home page http://gpodder.net also answers with 503 and a "Maintenance" message.

**Comment by adamvoss** [comment]
Thanks @elelay!  I looked at it too briefly and missed that it was search.

**Comment by netzverweigerer** [comment]
Thanks a lot for your responses and for your quick information.

**Comment by adamvoss** [comment]
The website is back up.  Closing this.
