### ISSUE TITLE
unhandled exception on sync

### ISSUE THREAD

**Issue by markmrsmith** [gpodder/gpodder#344]
Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\src\gpodder\gtkui\main.py", line 1137, in update_downloads_list
    self.downloads_finished(self.download_tasks_seen)
  File "C:\Program Files (x86)\gPodder\src\gpodder\gtkui\main.py", line 1397, in downloads_finished
    self.update_podcast_list_model()
  File "C:\Program Files (x86)\gPodder\src\gpodder\gtkui\main.py", line 2063, in update_podcast_list_model
    self.podcast_list_model.update_all()
  File "C:\Program Files (x86)\gPodder\src\gpodder\gtkui\model.py", line 809, in update_all
    self.update_by_iter(row.iter)
  File "C:\Program Files (x86)\gPodder\src\gpodder\gtkui\model.py", line 854, in update_by_iter
    pill_image = self._get_pill_image(channel, downloaded, unplayed)
  File "C:\Program Files (x86)\gPodder\src\gpodder\gtkui\model.py", line 692, in _get_pill_image
    return draw.draw_pill_pixbuf(str(count_unplayed), str(count_downloaded))
  File "C:\Program Files (x86)\gPodder\src\gpodder\gtkui\draw.py", line 279, in draw_pill_pixbuf
    return cairo_surface_to_pixbuf(draw_text_pill(left_text, right_text))
  File "C:\Program Files (x86)\gPodder\src\gpodder\gtkui\draw.py", line 239, in draw_text_pill
    ctx.move_to(x-1+x_border, y+border)
MemoryError

I'm using windows 7 and the latest gpodder 3.9.3

**Comment by elelay** [comment]
Thanks for the report.
Please try latest 3.10.4 release.
