### ISSUE TITLE
Sync to device

### ISSUE THREAD

**Issue by tiltkoko** [gpodder/gpodder#380]
When I am filesystem device syncing to my mp3 player, when I used to get a dialog with the files deleted on the device to confirm, I now get..  
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/gpodder/download.py", line 352, in run
    task = self.queue.get_next()
  File "/usr/lib/python3.6/site-packages/gpodder/gtkui/download.py", line 154, in get_next
    (row[DownloadStatusModel.C_TASK] for row in self)
  File "/usr/lib/python3.6/site-packages/gpodder/gtkui/download.py", line 155, in <genexpr>
    if task.status == task.QUEUED)
AttributeError: 'NoneType' object has no attribute 'status'
```

Hope to se a bugfix release in the near future.

**Comment by elelay** [comment]
Hi  @tiltkoko, thanks for reporting. I can't reproduce it in master right now. Maybe it has been fixed?

**Comment by tiltkoko** [comment]
Hi @elelay. It works perfect again with 3.10.1, keep up the good work! :)
