### ISSUE TITLE
exception when downloading from YouTube with version 3.10.0

### ISSUE THREAD

**Issue by tmancill** [gpodder/gpodder#386]
As reported in [Debian #888420](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888420), attempting to download from YouTube results in the following exception:

```
1516943895.460834 [gpodder.download] ERROR: Download failed: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 729, in run
    url = youtube.get_real_download_url(self.__episode.url, fmt_ids)
  File "/usr/lib/python3/dist-packages/gpodder/youtube.py", line 121, in get_real_download_url
    fmt_id_url_map = sorted(find_urls(page), reverse=True)
  File "/usr/lib/python3/dist-packages/gpodder/youtube.py", line 110, in find_urls
    r4 = re.search('url_encoded_fmt_stream_map=([^&]+)', page)
  File "/usr/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```
The following patch addresses the issue in my testing:

```patch
diff --git a/src/gpodder/youtube.py b/src/gpodder/youtube.py
index b61ebf3..9bb006d 100644
--- a/src/gpodder/youtube.py
+++ b/src/gpodder/youtube.py
@@ -118,7 +118,7 @@ def get_real_download_url(url, preferred_fmt_ids=None):
                 error_message = util.remove_html_tags(error_info['reason'][0])
                 raise YouTubeError('Cannot download video: %s' % error_message)
 
-        fmt_id_url_map = sorted(find_urls(page), reverse=True)
+        fmt_id_url_map = sorted(find_urls(str(page)), reverse=True)
 
         if not fmt_id_url_map:
             raise YouTubeError('fmt_url_map not found for video ID "%s"' % vid)
```

**Comment by tmancill** [comment]
If that patch looks okay, I'll submit a PR.

**Comment by elelay** [comment]
Thanks for reporting!
I believe this issue is already fixed by [c937184] in master.

**Comment by tmancill** [comment]
@elelay  Ah, I should have looked at the commit log.  The commit in master is certainly a better fix than what I proposed.  Thank you for the pointer.

**Comment by Strubbl** [comment]
Is it possible to get a minor release, which has this fix included? Currently 36 items are queued in my gpodder with that error. It would be really cool to download them the easy way
