### ISSUE TITLE
Invalid URL for dts.podtrac.com

### ISSUE THREAD

**Issue by tekvsakdan** [gpodder/gpodder#399]
The gpoodder version 3.10.0 is receiving the following error. 

```
(gpodder:1711): Gtk-WARNING **: Allocating size to GtkApplicationWindow 0x1ee42a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
1518227947.296376 [gpodder.download] ERROR: HTTP 403 while downloading "Vozovnica za Mars bi bila enosmerna": Forbidden
Traceback (most recent call last):
  File "/tmp/gp/gpodder/src/gpodder/download.py", line 763, in run
    self.tempname, reporthook=self.status_updated)
  File "/tmp/gp/gpodder/src/gpodder/download.py", line 271, in retrieve_resume
    fp = self.open(url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1757, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.6/urllib/request.py", line 1936, in open_http
    return self._open_generic_http(http.client.HTTPConnection, url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1932, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1952, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File "/tmp/gp/gpodder/src/gpodder/download.py", line 215, in http_error_default
    raise gPodderDownloadHTTPError(url, errcode, errmsg)
gpodder.download.gPodderDownloadHTTPError: ('//dts.podtrac.com/redirect.mp3/http%3A//videoweb.rtvslo.si/podcast/ava_archive04/2017/09/21/VozovnicazaMarsbibilaenosmerna3573020.mp3', 403, 'Forbidden')
```

If we test the link with curl, it doesnt work.
```
curl dts.podtrac.com/redirect.mp3/http%3A//videoweb.rtvslo.si/podcast/ava_archive04/2017/09/21/VozovnicazaMarsbibilaenosmerna3573020.mp3
```
If we replace `http%3A//` with the  `http://`,  the link works
```
curl dts.podtrac.com/redirect.mp3/http://videoweb.rtvslo.si/podcast/ava_archive04/2017/09/21/VozovnicazaMarsbibilaenosmerna3573020.mp3
```
Actually this `http` or `https` inside url is not necessary according to `http://analytics.podtrac.com/how-to-measure/`

**Comment by elelay** [comment]
Fixed in master. Thanks for reporting the issue :-)
