### ISSUE TITLE
AttributeError: module 'gi' has no attribute 'require_version'

### ISSUE THREAD

**Issue by samusz** [gpodder/gpodder#424]
Just installed gpodder from git with  the https://gpodder.github.io/docs/run-from-git.html instructions. 
Here is the trace : 

```
bin]$ ./gpodder

    Warning: python-dbus not found. Disabling D-Bus support.
    
1521121688.396469 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "./gpodder", line 158, in <module>
    main()
  File "./gpod``der", line 151, in main
    from gpodder.gtkui import main
  File "/home/samusz/lib/git/gpodder/src/gpodder/gtkui/main.py", line 23, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'

Traceback (most recent call last):
  File "./gpodder", line 158, in <module>
    main()
  File "./gpodder", line 151, in main
    from gpodder.gtkui import main
  File "/home/samusz/lib/git/gpodder/src/gpodder/gtkui/main.py", line 23, in <module>
    gi.require_version('Gtk', '3.0')
```
is it my python install that sucks (anaconda) or what ? 

I say that because before this exception I had to patch my install to get there : 
```
[samusz@jj-1197-fixe0007 gpodder]$ python3 bin/gpodder                           # To directly launch from command line

    Warning: python-dbus not found. Disabling D-Bus support.
    
1521120468.343677 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "bin/gpodder", line 158, in <module>
    main()
  File "bin/gpodder", line 151, in main
    from gpodder.gtkui import main
  File "/home/samusz/lib/git/gpodder/src/gpodder/gtkui/main.py", line 22, in <module>
    import gi
  File "/home/samusz/anaconda3/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t url)?

Traceback (most recent call last):
  File "bin/gpodder", line 158, in <module>
    main()
  File "bin/gpodder", line 151, in main
    from gpodder.gtkui import main
  File "/home/samusz/lib/git/gpodder/src/gpodder/gtkui/main.py", line 22, in <module>
    import gi
  File "/home/samusz/anaconda3/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t url)?
[samusz@jj-1197-fixe0007 gpodder]$ atom /home/samusz/lib/git/gpodder/src/gpodder/gtkui/main.py
[samusz@jj-1197-fixe0007 gpodder]$ atom /home/samusz/anaconda3/lib/python3.6/site-packages/gi/__init__.py
[samusz@jj-1197-fixe0007 gpodder]$ 2
2to3      2to3-3.5  2to3-3.6  
[samusz@jj-1197-fixe0007 gpodder]$ 2to3.6 /home/samusz/anaconda3/lib/python3.6/site-packages/gi/__init__.py
bash: 2to3.6 : commande introuvable
[samusz@jj-1197-fixe0007 gpodder]$ 2to3 /home/samusz/anaconda3/lib/python3.6/site-packages/gi/__init__.py
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: Refactored /home/samusz/anaconda3/lib/python3.6/site-packages/gi/__init__.py
--- /home/samusz/anaconda3/lib/python3.6/site-packages/gi/__init__.py	(original)
+++ /home/samusz/anaconda3/lib/python3.6/site-packages/gi/__init__.py	(refactored)
@@ -36,6 +36,6 @@
 if __name__ == '__main__':
 	try:
 		url = save_file()
-		print url
+		print(url)
 	except GistError as e:
-		print e.value
+		print(e.value)
RefactoringTool: Files that need to be modified:
RefactoringTool: /home/samusz/anaconda3/lib/python3.6/site-packages/gi/__init__.py
[samusz@jj-1197-fixe0007 gpodder]$ python3 bin/gpodder                           # To directly launch from command line

    Warning: python-dbus not found. Disabling D-Bus support.
    
1521120872.272813 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "bin/gpodder", line 158, in <module>
    main()
  File "bin/gpodder", line 151, in main
    from gpodder.gtkui import main
  File "/home/samusz/lib/git/gpodder/src/gpodder/gtkui/main.py", line 23, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'

Traceback (most recent call last):
  File "bin/gpodder", line 158, in <module>
    main()
  File "bin/gpodder", line 151, in main
    from gpodder.gtkui import main
  File "/home/samusz/lib/git/gpodder/src/gpodder/gtkui/main.py", line 23, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'
```
Thank for any help running gpodder. 
Best
Samusz

**Comment by elelay** [comment]
You need to create an anaconda environment with python3 (`conda create python=3.6`).
Here you have gi for python2
