### ISSUE TITLE
gpodder.org/directory.opml gives 404

### ISSUE THREAD

**Issue by Alexander-Wilms** [gpodder/gpodder#434]
Not sure if this is the correct project for filing the bug report, but trying to view the recommended podcasts fails atm:

```
ERROR: Cannot import OPML from URL: http://gpodder.org/directory.opml
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/gpodder/opml.py", line 75, in __init__
    doc = xml.dom.minidom.parseString(util.urlopen(url).read())
  File "/app/lib/python3.5/site-packages/gpodder/util.py", line 1204, in urlopen
    return opener.open(request)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by stefankoegl** [comment]
Thanks for reporting. I've just fixed a wrong redirect that caused this issue.

**Comment by Alexander-Wilms** [comment]
Thanks!
