### ISSUE TITLE
Error in Gpodder 3.10 on Ubuntu: python3 main.py "TreeView object has no attribute"

### ISSUE THREAD

**Issue by Valeryan24** [gpodder/gpodder#482]
Hi, I just tried to install Gpodder 3.10.1 (from distribution package) on a fresh Ubuntu 18.10 (development version) with Wayland session.

First start works well but, as I had a previous backup of datas, after closing it I tried to copy them to re-use my old podcast subscriptions, files already donwloaded and database (see the screenshot).

https://framapic.org/BkSLlkiFZzmE/IPGpUTQrkHCV.png

This backup is from December 2016, so version 3.9 of Gpodder.

When I restart, Gpodder main screen remains all blank: no podcast list, no entry, menus stay gray and unclickable. Program does not freeze, but nothing happens.

On the folder, a Database_upgraded-v6 is added next to the Database_upgraded-v5.

Log tells:
`2018-06-17 16:08:29,120 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 3679, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 119, in __init__
    BuilderWidget.__init__(self, None, _builder_expose={'app': app})
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/interface/common.py", line 39, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/base.py", line 72, in __init__
    self.new()
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 194, in new
    self.channels = self.model.get_podcasts()
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1238, in get_podcasts
    podcast.check_download_folder()
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 782, in check_download_folder
    return_wanted_filename=True)
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 477, in local_filename
    fn_template = hashlib.md5(self.url).hexdigest()
TypeError: Unicode-objects must be encoded before hashing

2018-06-17 16:08:52,475 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 1301, in on_treeview_query_tooltip
    if not getattr(treeview, TreeViewHelper.CAN_TOOLTIP) or x > 50 or (column is not None and column != treeview.get_columns()[0]):
AttributeError: 'TreeView' object has no attribute '_gpodder_can_tooltip'

2018-06-17 16:08:52,484 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 1301, in on_treeview_query_tooltip
    if not getattr(treeview, TreeViewHelper.CAN_TOOLTIP) or x > 50 or (column is not None and column != treeview.get_columns()[0]):
AttributeError: 'TreeView' object has no attribute '_gpodder_can_tooltip'`

Thanks in advance for your help.

**Comment by elelay** [comment]
@Valeryan24 you hit a corner of the code not updated for python3 (fixed now).

I would be interested in a copy of your $GPODDER_HOME/Database file to reproduce it.
If you agree, can you send it to elelay at macports.org?
Thanks,
