### ISSUE TITLE
Unable to run gPodder anymore

### ISSUE THREAD

**Issue by HLelent** [gpodder/gpodder#519]
Since an update on Arch (Antergos) a week ago :
```
2018-08-12 08:23:23,734 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/bin/gpodder", line 158, in <module>
    main()
  File "/usr/bin/gpodder", line 151, in main
    from gpodder.gtkui import main
  File "/usr/lib/python3.7/site-packages/gpodder/gtkui/main.py", line 74, in <module>
    from gpodder.gtkui.services import CoverDownloader
  File "/usr/lib/python3.7/site-packages/gpodder/gtkui/services.py", line 104
    def __get_cover(self, channel, url, async=False, avoid_downloading=False):
                                            ^
SyntaxError: invalid syntax

```

**Comment by elelay** [comment]
This is known incompatibility with python 3.7 (async is now a reserved keyword).
You can [run from git](https://gpodder.github.io/docs/run-from-git.html) for a while, waiting for the next release.

**Comment by HLelent** [comment]
Thank You!
