### ISSUE TITLE
gpodder doesn't start anymore (Syntax error)

### ISSUE THREAD

**Issue by fapdash** [gpodder/gpodder#530]
I've recently updated my Ubuntu version to 18.04 and gpodder doesn't want to start anymore.
I'm running gpodder from latest master.

```
$ python3 --version
Python 3.6.5
$ bin/gpodder
1535193423.291722 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "bin/gpodder", line 158, in <module>
    main()
  File "bin/gpodder", line 150, in main
    from gpodder.gtkui import main
  File "/home/fap/repos/gpodder/src/gpodder/gtkui/main.py", line 44, in <module>
    from gpodder import (common, core, download, extensions, feedcore, my, opml,
  File "/home/fap/repos/gpodder/src/gpodder/my.py", line 39, in <module>
    from mygpoclient import api, public
  File "/home/fap/repos/gpodder/src/mygpoclient/api.py", line 21, in <module>
    from mygpoclient import simple
  File "/home/fap/repos/gpodder/src/mygpoclient/simple.py", line 23, in <module>
    from mygpoclient import json
  File "/home/fap/repos/gpodder/src/mygpoclient/json.py", line 79
    except ValueError, ve:
                     ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "bin/gpodder", line 158, in <module>
    main()
  File "bin/gpodder", line 150, in main
    from gpodder.gtkui import main
  File "/home/fap/repos/gpodder/src/gpodder/gtkui/main.py", line 44, in <module>
    from gpodder import (common, core, download, extensions, feedcore, my, opml,
  File "/home/fap/repos/gpodder/src/gpodder/my.py", line 39, in <module>
    from mygpoclient import api, public
  File "/home/fap/repos/gpodder/src/mygpoclient/api.py", line 21, in <module>
    from mygpoclient import simple
  File "/home/fap/repos/gpodder/src/mygpoclient/simple.py", line 23, in <module>
    from mygpoclient import json
  File "/home/fap/repos/gpodder/src/mygpoclient/json.py", line 79
    except ValueError, ve:
                     ^
SyntaxError: invalid syntax

```

Edit:

Might be totally unrelated but I tried to reinstall the dependencies and had this error:

```
$ python3 tools/localdepends.py
Fetching podcastparser ... Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/localdepends.py", line 43, in <module>
    tarball_url = get_tarball_url(module)
  File "tools/localdepends.py", line 36, in get_tarball_url
    html = urllib.request.urlopen(url).read().decode('utf-8')
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>
```

I've looked around on stackoverflow and the issues on this repo but couldn't find anything that helped.

**Comment by elelay** [comment]
Indeed, your version of mygpoclient is outdated and not compatible with python3, so you were right to update it.
You should remove `/home/fap/repos/gpodder/src/mygpoclient` before running `localdepends.py` otherwise it will not update.
I don't know why you get certificate errors with pypi. Have you tried at another time?

**Comment by fapdash** [comment]
Thank you, removing the `mygpodclient` solved it!
The ssl issues had probably something to do with problems introduced from the distro upgrade. I solved it  by exporting `SSL_CERT_DIR="/etc/ssl/certs"`.
