### ISSUE TITLE
[Request] gPodder should show episode count for every podcast infront of its name

### ISSUE THREAD

**Issue by shad90** [gpodder/gpodder#542]
like "This American Life (4)"
And
Is there any possibility that gPodder will have cover browser interface. Like in Vocal and android apps? That will be awesome. 
Thank You all who are contributing.

**Comment by elelay** [comment]
Episode count is already shown after the name in the gui, as shown on [this screenshot](https://screenshots.debian.net/package/gpodder).
There is currently no plan to implement an cover browser interface, but why not...

**Comment by shad90** [comment]
> Episode count is already shown after the name in the gui, as shown on [this screenshot](https://screenshots.debian.net/package/gpodder).

I am using it on KDE . I don't have this count. I couldn't find any way to enable it in config.

**Comment by elelay** [comment]
I've just installed gPodder on a Kubuntu 18.04 LTS live cd.
It does have counts after podcast name. Can you provide the version of gPodder you are using and attach a screenshot?
Thanks,

**Comment by shad90** [comment]
Removed every trace of old installation. Installed again and ran from terminal. This is what i got
```
Gtk-WARNING **: 15:54:20.025: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
```

**Comment by shad90** [comment]
OK!. So i got it. If you download episodes then the counter shows otherwise it doesn't. And I am not downloading episodes. I am just streaming it using SMplayer. 
But it shouldn't be that way. Counter should show how many episodes are available of which how many are new and how many played.

**Comment by elelay** [comment]
This is not how it is meant to work.
But you can easily customize it: replace  [the _get_pill_image function](https://github.com/gpodder/gpodder/blob/master/src/gpodder/gtkui/model.py#L701)
```
    def _get_pill_image(self, channel, count_downloaded, count_unplayed):
        if count_unplayed > 0 or count_downloaded > 0:
            return draw.draw_pill_pixbuf(str(count_unplayed), str(count_downloaded))
        else:
            return None
```
with
```
    def _get_pill_image(self, channel, count_downloaded, count_unplayed):
        stats = channel.get_statistics()
        if stats[2] > 0 or stats[0] > 0:
            return draw.draw_pill_pixbuf(str(stats[2]), str(stats[0]))
        else:
            return None
```
to see how many are new versus total

**Comment by shad90** [comment]
Then i'll have to rebuild it ?
Thanks

**Comment by shad90** [comment]
Also if you have time. Tell me how can i costumize gpodder to mark an episode finished after completion of streaming. It only works for downloaded episodes.

**Comment by elelay** [comment]
> Then i'll have to rebuild it ?
You won't have to rebuild it. Run it [from source](https://gpodder.github.io/docs/run-from-git.html) (or patch the system's `/usr/lib/python3.x/site-packages/gpodder/gtkui/model.py`, but I don't recommend it).
> mark an episode finished after completion of streaming
I'm not sure it's possible. I'll look into it...

**Comment by shad90** [comment]
OK!. It worked. Thanks for the help.

**Comment by elelay** [comment]
To mark episode finished after completion streaming requires a little tweak to [mpris-listener](https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/mpris-listener.py#L182):
replace line 182
```
        file_uri = urllib.request.url2pathname(urllib.parse.urlparse(self.uri).path).encode('utf-8')
```
with
```
        parsed_url = urllib.parse.urlparse(self.uri)
        if (not parsed_url.scheme) or parsed_url.scheme == 'file':
            file_uri = urllib.request.url2pathname(urllib.parse.urlparse(self.uri).path).encode('utf-8')
        else:
            file_uri = self.uri
```
I might commit to gPodder, once I've tried it a bit more.

**Comment by shad90** [comment]
Worked for both Downloaded and streamed episodes. You are awesome. Thanks for the help.
Checked with one downloaded episode and one streamed. It worked.
Thank you again for you help and time.

**Comment by elelay** [comment]
Yeah! Always fun to see how people can customize their workflow. Given that gPodder is not too big of a program, you'll be able to make it do almost anything you want. Keep experimenting ;-)

**Comment by shad90** [comment]
Me again.. If I quit media player without first pausing the stream, gpodder would mark the episode as finished even if i hadn't finished it. Is it the intended behaviour or restriction of MPRIS ?

**Comment by elelay** [comment]
I can't reproduce it using VLC and [99% invisible](http://feeds.99percentinvisible.org/99percentinvisible) podcast.
Maybe it's SMPlayer.
Running ./bin/gpodder -v will show you what gPodder receives:
```
 INFO: CurrentTrackTracker: Stopped: https://dts.podtrac.com/redirect.mp3/media.blubrry.com/99percentinvisible/dovetail.prxu.org/96/4b19aa37-bbff-42ad-8a9d-3a2bfd475b5a/323_The_House_that_Came_in_the_Mail_pt01.mp3: Stopped at 3/1932 (@1.000000)
```

**Comment by shad90** [comment]
Actually MPRIS listener doesn't work with SMplayer, maybe this will help: 
'''
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.vlc was not provided by any .service files
'''
So i started using VLC for streaming. I am having this episode marked finished issue with vlc. I can reproduce it again using VLC. If you quit it then stream, then quit it and do this for one or two times. You will have your episode marked as finished. But if you stream that again and pause its showing right information again. 
This is error it generates.
'''
ERROR: Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.mpris.MediaPlayer2.vlc': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/share/gpodder/extensions/mpris-listener.py", line 271, in on_prop_change
    collected_info['pos'] = self.query_position()
  File "/usr/local/share/gpodder/extensions/mpris-listener.py", line 284, in query_position
    proxy = self.bus.get_object(self.OBJECT_VLC, self.PATH_MPRIS)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.vlc was not provided by any .service files
'''

**Comment by elelay** [comment]
Thanks for the details.
I have no time to try it right now, but it looks like vlc disconnects from dbus when an event is still being processed.
