### ISSUE TITLE
subscriptions not updated from gpodder.net

### ISSUE THREAD

**Issue by doubletissue** [gpodder/gpodder#565]
I'm running gPodder in Ubuntu. I add a subscription on gpodder.net, but the program does not pick it up. I've tried manually initiating the download of new episodes, disabling sync and re-enabling it, and unsubscribing and resubscribing. Nothing makes it recognize the new subscription.

**Comment by mrMoe** [comment]
The same happens on Arch Linux with gPodder 3.10.8.
It seems even the webservice isn''t up to date any more

**Comment by Mic92** [comment]
Gpodder seems to receive the deletion request from the web server
but does not seem to remove the feed in question:

```
1582292641.190860 [gpodder.my] DEBUG: Received remove action: https://rss.art19.com/sinica
1582292641.191918 [gpodder.my] DEBUG: All actions have been uploaded to the server.
1582292641.192343 [gpodder.my] DEBUG: Starting episode status sync.
```

**Comment by philb61** [comment]
Still broken in 3.10.16.

The only reason I installed the gpodder client was specifically to interact with gpodder.net.  

Is there any update at all on this issue?

I'm guessing this is the culprit:

`WARNING:gpodder.my:Exception while polling for episodes.
Traceback (most recent call last):
  File "/home/philb/gpodder/src/mygpoclient/http.py", line 133, in _request
    response = self._opener.open(request)
  File "/home/philb/.pyenv/versions/3.5.7/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/home/philb/.pyenv/versions/3.5.7/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/philb/.pyenv/versions/3.5.7/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/home/philb/.pyenv/versions/3.5.7/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/home/philb/.pyenv/versions/3.5.7/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/philb/gpodder/src/gpodder/my.py", line 501, in synchronize_episodes
    changes = self._client.download_episode_actions(since_o.since)
  File "/home/philb/gpodder/src/mygpoclient/simple.py", line 38, in _wrapper
    return f(self, *args, **kwargs)
  File "/home/philb/gpodder/src/mygpoclient/api.py", line 348, in download_episode_actions
    data = self._client.GET(uri)
  File "/home/philb/gpodder/src/mygpoclient/http.py", line 147, in GET
    return self._request('GET', uri, None)
  File "/home/philb/gpodder/src/mygpoclient/http.py", line 142, in _request
    raise UnknownResponse(http_error.code)
mygpoclient.http.UnknownResponse: 500
`

Did gpodder.net change their API since the client was written?

**Comment by t3mujin** [comment]
Same goes for 3.10.17, without this this app is basically useless...

**Comment by philb61** [comment]
> Same goes for 3.10.17, without it this app is basically useless...

The gpodder server has been ridiculously unreliable for many months now. I realize that's why I got a 500 error. 

But even when their server was working reliably, the client never picked up new subscriptions for me.

**Comment by gs-foto** [comment]
Is there any progress on this? I've added a podcast via Antennapod on Android and did a successful full sync, but the podcast doesn't show up on gpodder.net. I also exported the opml from Antennapod, loaded it into gpodder on Ubuntu and did a successful upload to gpodder.net. The list on gpodder.net is still the old one, even after clearing the browser cache and logging in again. It appears that sync does not work at all, despite "Success" messages.
