### ISSUE TITLE
Double exception when updating in 3.10.6

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#594]
While checking for new episodes, it pauses for a minute on one podcast, outputs the following error and continues. There is code to display which podcast timed out but it appears to not be working. The podcast it paused on is probably a temporary issue but the url is https://feeds.pacific-content.com/commandlineheroes.

```
1547695146.205541 [gpodder.gtkui.main] ERROR: Error: <urlopen error timed out>
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gpodder/gtkui/main.py", line 2624, in update_feed_cache_proc
    channel.update(max_episodes=self.config.max_episodes_per_feed)
  File "/usr/lib/python3.6/site-packages/gpodder/model.py", line 1021, in update
    result = self.feed_fetcher.fetch_channel(self)
  File "/usr/lib/python3.6/site-packages/gpodder/model.py", line 67, in fetch_channel
    return self.fetch(url, channel.http_etag, channel.http_last_modified)
  File "/usr/lib/python3.6/site-packages/gpodder/feedcore.py", line 234, in fetch
    return self._parse_feed(url, etag, modified)
  File "/usr/lib/python3.6/site-packages/gpodder/feedcore.py", line 190, in _parse_feed
    stream = util.urlopen(url, headers)
  File "/usr/lib/python3.6/site-packages/gpodder/util.py", line 1201, in urlopen
    return opener.open(request)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

```

**Comment by auouymous** [comment]
Adding an `important=True` argument to the self.notification() call in gtkui/main.py:update_feed_cache_proc() properly displays the dialog with the feed that failed.
