### ISSUE TITLE
D-Bus disabling does not really work

### ISSUE THREAD

**Issue by probonopd** [gpodder/gpodder#595]
It says "Disabling D-Bus support" but then it is crashing nevertheless.

```
    Warning: python-dbus not found. Disabling D-Bus support.
    
1547894059.960259 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/tmp/.mount_gPodde9BKsrm/usr/conda/bin/gpodder", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/me/src/gpodder/bin/gpodder", line 158, in <module>
    main()
  File "/home/me/src/gpodder/bin/gpodder", line 150, in main
    from gpodder.gtkui import main
  File "/home/me/src/gpodder/src/gpodder/gtkui/main.py", line 38, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

Traceback (most recent call last):
  File "/tmp/.mount_gPodde9BKsrm/usr/conda/bin/gpodder", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/me/src/gpodder/bin/gpodder", line 158, in <module>
    main()
  File "/home/me/src/gpodder/bin/gpodder", line 150, in main
    from gpodder.gtkui import main
  File "/home/me/src/gpodder/src/gpodder/gtkui/main.py", line 38, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```

**Comment by elelay** [comment]
Yes, it's been like that as far as I remember : maybe the web ui was not dependent on dbus, but the gtk UI is. Is it possible to include dbus in the appimage? Even if it's not connected to the session dbus...

**Comment by elelay** [comment]
The "Disabling d-bus message" is at startup when it won't try to find a running instance using dbus...

**Comment by probonopd** [comment]
There are different Python packages on PyPI with "dbus" in their name. I failed to find out which one is the correct one. Please advise.

**Comment by elelay** [comment]
It should be this one : https://pypi.org/project/dbus-python/
maybe there is the equivalent of a system package in appimage?

**Comment by probonopd** [comment]
AppImage is just something like a zip or ISO. It does not decide what you put inside.

**Comment by jesuspi6127** [comment]
I'm having the same issue pulling from git (no Appimage in my case). It's odd since it was running without issues but, after a reboot the problem appeared. Oddly enough, the packaged version 3.9.6 starts up without problems (downloading podcasts and YouTube videos is another story). Any ideas on how to address this? Running on Opensuse Leap 15.1

**Comment by elelay** [comment]
> Oddly enough, the packaged version 3.9.6 starts up without problems (downloading podcasts and YouTube videos is another story). Any ideas on how to address this? Running on Opensuse Leap 15.1

gPodder 3.9.6 is still python 2.7 using pygtk. gPodder 3.10 has updated to python 3 and gobject python bindings.

**Comment by jesuspi6127** [comment]
Thank you for the info elelay (that explains why my distro stubbornly has stayed on 3.9.6 to this day [grumble]). I already had installed Python 3 on my machine, including the python3-gobject package (version 3.26.1) for my distribution and Gpodder version 3.10.13 from git had worked without issues until I rebooted last week.

**Comment by jesuspi6127** [comment]
Please disregard my particular iteration of the issue. It had to do with an Anaconda instance making my Python libraries go haywire. Once I took care of that my issue was resolved. Sorry for any confusion.
