### ISSUE TITLE
gPodder 3.10.7 not downloading new episodes

### ISSUE THREAD

**Issue by highflux7** [gpodder/gpodder#602]
Updated to v3.10.7 and new episodes are seen but will not download.  All subscriptions.

Only thing I see in the logfile possibly related is:

``File "gpodder/src/gpodder/gtkui/main.py", line 2918, in download_episode_list
    episodes = list(Model.sort_episodes_by_pubdate(episodes))
NameError: name 'Model' is not defined
``

**Comment by highflux7** [comment]
Matter of fact, **all** downloads fail, log showing:

``
[gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "gpodder/src/gpodder/gtkui/main.py", line 3380, in on_download_selected_episodes
    self.download_episode_list(episodes)
  File "gpodder/src/gpodder/gtkui/main.py", line 2918, in download_episode_list
    episodes = list(Model.sort_episodes_by_pubdate(episodes))
NameError: name 'Model' is not defined
``

Regards.  -hf7

**Comment by highflux7** [comment]
Thank you!
