### ISSUE TITLE
gpodder module not found

### ISSUE THREAD

**Issue by klopsi** [gpodder/gpodder#615]
Hey Thomas, I think we met in A-Dam in 2009 at the Maemo conference.  Not sure though.  Anyway.  Gpodder stopped working for me and I don't understand why.  

```
gpodder
/usr/local/bin/gpodder:43: DeprecationWarning: Importing dbus.glib to use the GLib main loop with dbus-python is deprecated.
Instead, use this sequence:

    from dbus.mainloop.glib import DBusGMainLoop

    DBusGMainLoop(set_as_default=True)

  import dbus.glib
Traceback (most recent call last):
  File "/usr/local/bin/gpodder", line 158, in <module>
    main()
  File "/usr/local/bin/gpodder", line 83, in main
    import gpodder
ModuleNotFoundError: No module named 'gpodder'
```

OS is Devuan Ceres
```apt-cache show gpodder
Package: gpodder
Version: 3.10.7-1
Installed-Size: 2263
Maintainer: Thomas Perl <m@thp.io>
```
[EDIT] Reinstall fixed it.  I'll leave this up in case anyone knows the cause and specific solution.

**Comment by elelay** [comment]
Yes, I was going to suggest reinstall...

**Comment by elelay** [comment]
I'll leave it open for a while.
(Eric)

**Comment by clort81** [comment]
Well i grabbed the latest git.
ran 'make install'
```
/pr/gpodder# make install
intltool-extract --quiet --type=gettext/glade share/gpodder/ui/gtk/gpodderaddpodcast.ui
intltool-extract --quiet --type=gettext/glade share/gpodder/ui/gtk/gpodderchannel.ui
intltool-extract --quiet --type=gettext/glade share/gpodder/ui/gtk/gpodderconfigeditor.ui
intltool-extract --quiet --type=gettext/glade share/gpodder/ui/gtk/gpodderepisodeselector.ui
intltool-extract --quiet --type=gettext/glade share/gpodder/ui/gtk/gpodderexporttolocalfolder.ui
intltool-extract --quiet --type=gettext/glade share/gpodder/ui/gtk/gpodderpodcastdirectory.ui
intltool-extract --quiet --type=gettext/glade share/gpodder/ui/gtk/gpodderpreferences.ui
intltool-extract --quiet --type=gettext/glade share/gpodder/ui/gtk/gpodder.ui
intltool-extract --quiet --type=gettext/glade share/gpodder/ui/gtk/gpodderwelcome.ui
intltool-extract --quiet --type=gettext/glade share/gpodder/ui/gtk/menus.ui
intltool-extract --quiet --type=gettext/ini share/applications/gpodder.desktop.in
intltool-extract --quiet --type=gettext/ini share/applications/gpodder-url-handler.desktop.in
xgettext --from-code=utf-8 -LPython -k_:1 -kN_:1 -kN_:1,2 -kn_:1,2 -o po/messages.pot src/gpodder/build_info.py src/gpodder/common.py src/gpodder/config.py src/gpodder/core.py src/gpodder/coverart.py src/gpodder/dbsqlite.py src/gpodder/dbusproxy.py src/gpodder/deviceplaylist.py src/gpodder/directory.py src/gpodder/download.py src/gpodder/escapist_videos.py src/gpodder/extensions.py src/gpodder/feedcore.py src/gpodder/__init__.py src/gpodder/jsonconfig.py src/gpodder/log.py src/gpodder/minidb.py src/gpodder/model.py src/gpodder/my.py src/gpodder/opml.py src/gpodder/player.py src/gpodder/query.py src/gpodder/registry.py src/gpodder/schema.py src/gpodder/services.py src/gpodder/sync.py src/gpodder/syncui.py src/gpodder/unittests.py src/gpodder/util.py src/gpodder/utilwin32ctypes.py src/gpodder/utilwin32locale.py src/gpodder/vimeo.py src/gpodder/youtube.py src/gpodder/gtkui/app.py src/gpodder/gtkui/base.py src/gpodder/gtkui/config.py src/gpodder/gtkui/desktopfile.py src/gpodder/gtkui/download.py src/gpodder/gtkui/draw.py src/gpodder/gtkui/__init__.py src/gpodder/gtkui/macosx.py src/gpodder/gtkui/main.py src/gpodder/gtkui/model.py src/gpodder/gtkui/services.py src/gpodder/gtkui/shownotes.py src/gpodder/gtkui/widgets.py src/gpodder/gtkui/interface/addpodcast.py src/gpodder/gtkui/interface/common.py src/gpodder/gtkui/interface/configeditor.py src/gpodder/gtkui/interface/__init__.py src/gpodder/gtkui/interface/progress.py src/gpodder/gtkui/interface/searchtree.py src/gpodder/gtkui/interface/tagcloud.py src/gpodder/gtkui/desktop/channel.py src/gpodder/gtkui/desktop/episodeselector.py src/gpodder/gtkui/desktop/exportlocal.py src/gpodder/gtkui/desktop/__init__.py src/gpodder/gtkui/desktop/podcastdirectory.py src/gpodder/gtkui/desktop/preferences.py src/gpodder/gtkui/desktop/welcome.py src/gpodder/plugins/__init__.py src/gpodder/plugins/soundcloud.py share/gpodder/extensions/audio_converter.py share/gpodder/extensions/command_on_download.py share/gpodder/extensions/concatenate_videos.py share/gpodder/extensions/enqueue_in_mediaplayer.py share/gpodder/extensions/episode_website_context_menu.py share/gpodder/extensions/filter.py share/gpodder/extensions/gtk_statusicon.py share/gpodder/extensions/minimize_on_start.py share/gpodder/extensions/mpris-listener.py share/gpodder/extensions/normalize_audio.py share/gpodder/extensions/notification.py share/gpodder/extensions/notification-win32.py share/gpodder/extensions/rename_download.py share/gpodder/extensions/rm_ogg_cover.py share/gpodder/extensions/rockbox_convert2mp4.py share/gpodder/extensions/rockbox_coverart.py share/gpodder/extensions/sonos.py share/gpodder/extensions/tagging.py share/gpodder/extensions/taskbar_progress.py share/gpodder/extensions/ted_subtitles.py share/gpodder/extensions/ubuntu_appindicator.py share/gpodder/extensions/ubuntu_unity.py share/gpodder/extensions/update_feeds_on_startup.py share/gpodder/extensions/video_converter.py share/gpodder/extensions/youtube-dl.py share/gpodder/ui/gtk/gpodderaddpodcast.ui.h share/gpodder/ui/gtk/gpodderchannel.ui.h share/gpodder/ui/gtk/gpodderconfigeditor.ui.h share/gpodder/ui/gtk/gpodderepisodeselector.ui.h share/gpodder/ui/gtk/gpodderexporttolocalfolder.ui.h share/gpodder/ui/gtk/gpodderpodcastdirectory.ui.h share/gpodder/ui/gtk/gpodderpreferences.ui.h share/gpodder/ui/gtk/gpodder.ui.h share/gpodder/ui/gtk/gpodderwelcome.ui.h share/gpodder/ui/gtk/menus.ui.h bin/gpo bin/gpodder bin/gpodder-migrate2tres share/applications/gpodder.desktop.in.h share/applications/gpodder-url-handler.desktop.in.h
msgmerge --previous --silent po/ca.po po/messages.pot --output-file=po/ca.po
msgattrib --set-obsolete --ignore-file=po/messages.pot -o po/ca.po po/ca.po
msgattrib --no-obsolete -o po/ca.po po/ca.po
msgfmt po/ca.po -o share/locale/ca/LC_MESSAGES/gpodder.mo
msgmerge --previous --silent po/cs_CZ.po po/messages.pot --output-file=po/cs_CZ.po
msgattrib --set-obsolete --ignore-file=po/messages.pot -o po/cs_CZ.po po/cs_CZ.po
msgattrib --no-obsolete -o po/cs_CZ.po po/cs_CZ.po
msgfmt po/cs_CZ.po -o share/locale/cs_CZ/LC_MESSAGES/gpodder.mo
msgmerge --previous --silent po/cs.po po/messages.pot --output-file=po/cs.po
msgattrib --set-obsolete --ignore-file=po/messages.pot -o po/cs.po po/cs.po
msgattrib --no-obsolete -o po/cs.po po/cs.po
....
....
```
full messages here 
http://0x0.st/iJaL.txt

```
 gpodder

    Warning: python-dbus not found. Disabling D-Bus support.
    
Traceback (most recent call last):
  File "/usr/bin/gpodder", line 164, in <module>
    main()
  File "/usr/bin/gpodder", line 81, in main
    import gpodder  # isort:skip
ModuleNotFoundError: No module named 'gpodder'
```

Why isn't it finding module 'gpodder'?

**Comment by clort81** [comment]
If i run the gpodder from the gpodder/bin directory:
```
/pr/gpodder/bin$ ./gpodder

    Warning: python-dbus not found. Disabling D-Bus support.
    

  Error: Module "podcastparser" (python-podcastparser) not found.
         The podcastparser module can be downloaded from
         http://gpodder.org/podcastparser/

  From a source checkout, you can download local copies of all
  CLI dependencies for debugging (will be placed into "src/"):

      python3 tools/localdepends.py

```

**Comment by clort81** [comment]
I also ran the suggested install of localdepends.py

```
/pr/gpodder$ python3 tools/localdepends.py
Fetching podcastparser ... 21 KiB
  downloaded from https://files.pythonhosted.org/packages/ca/7e/180d1867c0bc7082bc044c5d3983ad0f7386f0a77fbfb94263d451eb5432/podcastparser-0.6.5.tar.gz
Extracting: podcastparser.py
Fetching mygpoclient ... 42 KiB
  downloaded from http://gpodder.org/mygpoclient/mygpoclient-1.8.tar.gz
Extracting: mygpoclient/__init__.py
Extracting: mygpoclient/api.py
Extracting: mygpoclient/api_test.py
Extracting: mygpoclient/feeds.py
Extracting: mygpoclient/http.py
Extracting: mygpoclient/http_test.py
Extracting: mygpoclient/json.py
Extracting: mygpoclient/json_test.py
Extracting: mygpoclient/locator.py
Extracting: mygpoclient/locator_test.py
Extracting: mygpoclient/public.py
Extracting: mygpoclient/public_test.py
Extracting: mygpoclient/simple.py
Extracting: mygpoclient/simple_test.py
Extracting: mygpoclient/testing.py
Extracting: mygpoclient/util.py
```
and reran (as root) make install.  Still same error as above.

**Comment by clort81** [comment]
For my last experiment, i grabbed the debian package, manually unpacked it and installed it to /usr:
```
✠ /pr/gpodder/gp# dpkg -X gpodder_3.10.16-1_all.deb .
./
./usr/
./usr/bin/
./usr/bin/gpo
./usr/bin/gpodder
./usr/bin/gpodder-migrate2tres
./usr/lib/
./usr/lib/python3/
./usr/lib/python3/dist-packages/
./usr/lib/python3/dist-packages/gpodder/
./usr/lib/python3/dist-packages/gpodder/__init__.py
./usr/lib/python3/dist-packages/gpodder/build_info.py
./usr/lib/python3/dist-packages/gpodder/common.py
./usr/lib/python3/dist-packages/gpodder/config.py
./usr/lib/python3/dist-packages/gpodder/core.py
./usr/lib/python3/dist-packages/gpodder/coverart.py
./usr/lib/python3/dist-packages/gpodder/dbsqlite.py
./usr/lib/python3/dist-packages/gpodder/dbusproxy.py
./usr/lib/python3/dist-packages/gpodder/deviceplaylist.py
./usr/lib/python3/dist-packages/gpodder/directory.py
./usr/lib/python3/dist-packages/gpodder/download.py
./usr/lib/python3/dist-packages/gpodder/escapist_videos.py
./usr/lib/python3/dist-packages/gpodder/extensions.py
./usr/lib/python3/dist-packages/gpodder/feedcore.py
./usr/lib/python3/dist-packages/gpodder/gtkui/
./usr/lib/python3/dist-packages/gpodder/gtkui/__init__.py
./usr/lib/python3/dist-packages/gpodder/gtkui/app.py
./usr/lib/python3/dist-packages/gpodder/gtkui/base.py
./usr/lib/python3/dist-packages/gpodder/gtkui/config.py
./usr/lib/python3/dist-packages/gpodder/gtkui/desktop/
./usr/lib/python3/dist-packages/gpodder/gtkui/desktop/__init__.py
./usr/lib/python3/dist-packages/gpodder/gtkui/desktop/channel.py
./usr/lib/python3/dist-packages/gpodder/gtkui/desktop/episodeselector.py
./usr/lib/python3/dist-packages/gpodder/gtkui/desktop/exportlocal.py
./usr/lib/python3/dist-packages/gpodder/gtkui/desktop/podcastdirectory.py
./usr/lib/python3/dist-packages/gpodder/gtkui/desktop/preferences.py
./usr/lib/python3/dist-packages/gpodder/gtkui/desktop/welcome.py
./usr/lib/python3/dist-packages/gpodder/gtkui/desktopfile.py
./usr/lib/python3/dist-packages/gpodder/gtkui/download.py
./usr/lib/python3/dist-packages/gpodder/gtkui/draw.py
./usr/lib/python3/dist-packages/gpodder/gtkui/interface/
./usr/lib/python3/dist-packages/gpodder/gtkui/interface/__init__.py
./usr/lib/python3/dist-packages/gpodder/gtkui/interface/addpodcast.py
./usr/lib/python3/dist-packages/gpodder/gtkui/interface/common.py
...
....
```
and 
cp -r usr/* /usr

Same result
```/pr/gpodder$ /usr/bin/gpodder

    Warning: python-dbus not found. Disabling D-Bus support.
    

  Error: Module "podcastparser" (python-podcastparser) not found.
         The podcastparser module can be downloaded from
         http://gpodder.org/podcastparser/

  From a source checkout, you can download local copies of all
  CLI dependencies for debugging (will be placed into "src/"):

      python3 tools/localdepends.py
```
