### ISSUE TITLE
youtube - Download failed: 'reason'

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#623]
Future live streams fail to download and don't have a reason key in error_info.

```
1556952016.863987 [gpodder.download] ERROR: Download failed: 'reason'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gpodder/download.py", line 745, in run
    url = youtube.get_real_download_url(self.__episode.url, fmt_ids)
  File "/usr/lib/python3.6/site-packages/gpodder/youtube.py", line 150, in get_real_download_url
    fmt_id_url_map = sorted(find_urls(page), reverse=True)
  File "/usr/lib/python3.6/site-packages/gpodder/youtube.py", line 142, in find_urls
    error_message = util.remove_html_tags(error_info['reason'][0])
KeyError: 'reason'
```

The following prevents the exception and uses the reason from player_response.

```
diff --git a/src/gpodder/youtube.py b/src/gpodder/youtube.py
index 5017c901..12942c15 100644
--- a/src/gpodder/youtube.py
+++ b/src/gpodder/youtube.py
@@ -138,7 +138,13 @@ def get_real_download_url(url, preferred_fmt_ids=None):
                     yield int(video_info['itag'][0]), video_info['url'][0]
             else:
                 error_info = parse_qs(page)
-                error_message = util.remove_html_tags(error_info['reason'][0])
+                if 'reason' in error_info:
+                    error_message = util.remove_html_tags(error_info['reason'][0])
+                elif 'player_response' in error_info:
+                    player_response = json.loads(error_info['player_response'][0])
+                    error_message = util.remove_html_tags(player_response['playabilityStatus']['reason'])
+                else:
+                    error_message = ''
                 raise YouTubeError('Cannot download video: %s' % error_message)
 
         fmt_id_url_map = sorted(find_urls(page), reverse=True)
```

**Comment by auouymous** [comment]
The reason key in player_response is available before the live stream and at certain times during and after. If not available, live_playback indicates live stream is active and post_live_playback is present when the live stream has finished but can't be downloaded yet.

```
diff --git a/src/gpodder/youtube.py b/src/gpodder/youtube.py
index 5017c901..78a69e21 100644
--- a/src/gpodder/youtube.py
+++ b/src/gpodder/youtube.py
@@ -138,7 +138,20 @@ def get_real_download_url(url, preferred_fmt_ids=None):
                     yield int(video_info['itag'][0]), video_info['url'][0]
             else:
                 error_info = parse_qs(page)
-                error_message = util.remove_html_tags(error_info['reason'][0])
+                if 'reason' in error_info:
+                    error_message = util.remove_html_tags(error_info['reason'][0])
+                elif 'player_response' in error_info:
+                    player_response = json.loads(error_info['player_response'][0])
+                    if 'reason' in player_response['playabilityStatus']:
+                        error_message = util.remove_html_tags(player_response['playabilityStatus']['reason'])
+                    elif 'live_playback' in error_info:
+                        error_message = 'live stream'
+                    elif 'post_live_playback' in error_info:
+                        error_message = 'post live stream'
+                    else:
+                        error_message = ''
+                else:
+                    error_message = ''
                 raise YouTubeError('Cannot download video: %s' % error_message)
 
         fmt_id_url_map = sorted(find_urls(page), reverse=True)
```

**Comment by elelay** [comment]
Great!
Maybe with a big try/catch around to prevent unpleasant surprises?
Can you make a PR with the patch?

**Comment by auouymous** [comment]
I don't need credit for this patch either.
