### ISSUE TITLE
internal database corrupt message

### ISSUE THREAD

**Issue by highflux7** [gpodder/gpodder#639]
Received dialog box with message indicating an internal database was corrupt and that I should report such and restart gPodder.

gPodder v3.10.9
Ubuntu 18.04.2 LTS (4.18.0-25-generic)

log:
```2019-07-02 15:25:22,816 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/home/vmorgan/Source/gpodder/src/gpodder/gtkui/main.py", line 2588, in update_progress
    self.update_podcast_list_model([channel.url])
  File "/home/vmorgan/Source/gpodder/src/gpodder/gtkui/main.py", line 2197, in update_podcast_list_model
    self.podcast_list_model.update_first_row()
  File "/home/vmorgan/Source/gpodder/src/gpodder/gtkui/model.py", line 808, in update_first_row
    self.update_by_iter(self.get_iter_first())
  File "/home/vmorgan/Source/gpodder/src/gpodder/gtkui/model.py", line 871, in update_by_iter
    total, deleted, new, downloaded, unplayed = channel.get_statistics()
  File "/home/vmorgan/Source/gpodder/src/gpodder/gtkui/model.py", line 502, in get_statistics
    return self._db.get_podcast_statistics()
  File "/home/vmorgan/Source/gpodder/src/gpodder/dbsqlite.py", line 136, in get_podcast_statistics
    'GROUP BY state, is_new' % self.TABLE_EPISODE)
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by elelay** [comment]
Hi,
this looks bad! I never had such error, but could it be that the disk drive hosting gPodder/Database was full, or unplugged incorrectly if it's a USB key?
Is gPodder working after restart?
Here is a blog article about exporting the database to a new file: https://www.froebe.net/blog/2015/05/27/error-sqlite-database-is-malformed-solved/
You might want to try to follow it, replacing `mydb.db` with `PATH/TO/gPodder/Database`...

**Comment by highflux7** [comment]
Disk drive okay and not full.  Restarted gPodder and received the error message again.  Restarted a second time and haven't seen the problem since (fingers crossed).

Thanks for your support!  Keeping an eye on it and hopefully won't need to rebuild the database re:the article you referenced.

Kind regards.
