### ISSUE TITLE
can't start gPodder due to permission errors

### ISSUE THREAD

**Issue by streety71** [gpodder/gpodder#695]
I had gPodder installed on Ubuntu where I changed the Download-folder via ".pam_environment" .
Now I had to do a fresh install (I choose Manjaro erased the root-partition and kept the home-partition). Now somewhere there seems something to be stuck as I re-installed gPodder and can't start it. In a terminal I get the following:

```
$ gpodder
Storing data in /data/gPodder (GPODDER_HOME is set)
Storing downloads in /data/gPodder/Downloads (GPODDER_DOWNLOAD_DIR is set)
1572377906.017491 [gpodder.log] WARNING: Cannot create output directory: /data/gPodder/Logs
1572377906.210609 [gpodder.sync] WARNING: Could not find gpod
1572377906.210847 [gpodder.sync] WARNING: Could not find eyed3.mp3
1572377906.232776 [gpodder.util] WARNING: Could not create directory: /data/gPodder
1572377906.233312 [gpodder.config] ERROR: Cannot write settings to /data/gPodder/Settings.json
1572377906.234064 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gpodder/gtkui/app.py", line 130, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/usr/lib/python3.7/site-packages/gpodder/core.py", line 39, in __init__
    self.config = config_class(gpodder.config_file)
  File "/usr/lib/python3.7/site-packages/gpodder/gtkui/config.py", line 100, in __init__
    config.Config.__init__(self, filename)
  File "/usr/lib/python3.7/site-packages/gpodder/config.py", line 271, in __init__
    self.save()
  File "/usr/lib/python3.7/site-packages/gpodder/config.py", line 333, in save
    fp = open(filename + '.tmp', 'wt')
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/data/gPodder/Settings.json.tmp'

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gpodder/gtkui/app.py", line 130, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/usr/lib/python3.7/site-packages/gpodder/core.py", line 39, in __init__
    self.config = config_class(gpodder.config_file)
  File "/usr/lib/python3.7/site-packages/gpodder/gtkui/config.py", line 100, in __init__
    config.Config.__init__(self, filename)
  File "/usr/lib/python3.7/site-packages/gpodder/config.py", line 271, in __init__
    self.save()
  File "/usr/lib/python3.7/site-packages/gpodder/config.py", line 333, in save
    fp = open(filename + '.tmp', 'wt')
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/data/gPodder/Settings.json.tmp'
```
Is there any way I can reset the settings?

**Comment by chlorophyll-zz** [comment]
you account is lacking permission to write to /data/ 
Cannot create output directory: /data/gPodder/Logs
please do a 
sudo chown *yourusername /data/ -R

**Comment by streety71** [comment]
thanks a lot!
