### ISSUE TITLE
Youtube unable to extract video data. 

### ISSUE THREAD

**Issue by sch1308** [gpodder/gpodder#708]
![image](https://user-images.githubusercontent.com/7896067/70718251-e08daf80-1cbd-11ea-91f5-4d06ac2c5399.png)
youtube_dl.utils.ExtractorError: 1Zt1P41pjE4: YouTube said: Unable to extract vi
deo data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.7\site-packages\gpodder\downl
oad.py", line 787, in run
    self.tempname, reporthook=self.status_updated)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 81, in retrieve_resume
    res = self._ytdl.fetch_video(self._url, tempname, self._my_hook)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 286, in fetch_video
    return ydl.extract_info(url, download=True)
  File "YoutubeDL.py", line 819, in extract_info
  File "YoutubeDL.py", line 624, in report_error
  File "YoutubeDL.py", line 594, in trouble
youtube_dl.utils.DownloadError: ERROR: 1Zt1P41pjE4: YouTube said: Unable to extr
act video data
1576156861.479492 [gpodder.download] INFO: Thread-1412 is processing: Joe Rogan
Experience #1398 - Lil Duval
1576156861.481445 [gpodder.registry] INFO: custom_downloader resolved by custom_
downloader from youtube-dl: None -> <youtube-dl.YoutubeCustomDownload object at
0x04ad018c>
1576156861.481445 [gpodder.download] INFO: Downloading https://www.youtube.com/w
atch?v=UYp5KoDc3mE with <youtube-dl.YoutubeCustomDownload object at 0x04ad018c>
[youtube] UYp5KoDc3mE: Downloading webpage
[youtube] UYp5KoDc3mE: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
ERROR: UYp5KoDc3mE: YouTube said: Unable to extract video data
1576156861.973633 [gpodder.download] ERROR: Download failed: ERROR: UYp5KoDc3mE:
 YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "YoutubeDL.py", line 796, in extract_info
  File "common.py", line 530, in extract
  File "youtube.py", line 1834, in _real_extract
youtube_dl.utils.ExtractorError: UYp5KoDc3mE: YouTube said: Unable to extract vi
deo data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.7\site-packages\gpodder\downl
oad.py", line 787, in run
    self.tempname, reporthook=self.status_updated)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 81, in retrieve_resume
    res = self._ytdl.fetch_video(self._url, tempname, self._my_hook)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 286, in fetch_video
    return ydl.extract_info(url, download=True)
  File "YoutubeDL.py", line 819, in extract_info
  File "YoutubeDL.py", line 624, in report_error
  File "YoutubeDL.py", line 594, in trouble
youtube_dl.utils.DownloadError: ERROR: UYp5KoDc3mE: YouTube said: Unable to extr
act video data
1576156861.985352 [gpodder.download] INFO: Thread-1412 is processing: Disney Dre
am Day at Sea, Palo Brunch, Merchandise & More | Disney Cruise Line | Day 4
1576156861.987305 [gpodder.registry] INFO: custom_downloader resolved by custom_
downloader from youtube-dl: None -> <youtube-dl.YoutubeCustomDownload object at
0x04ad006c>
1576156861.992188 [gpodder.download] INFO: Downloading https://www.youtube.com/w
atch?v=qqpzN-kAX00 with <youtube-dl.YoutubeCustomDownload object at 0x04ad006c>
[youtube] qqpzN-kAX00: Downloading webpage
[youtube] qqpzN-kAX00: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
ERROR: qqpzN-kAX00: YouTube said: Unable to extract video data
1576156862.437500 [gpodder.download] ERROR: Download failed: ERROR: qqpzN-kAX00:
 YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "YoutubeDL.py", line 796, in extract_info
  File "common.py", line 530, in extract
  File "youtube.py", line 1834, in _real_extract
youtube_dl.utils.ExtractorError: qqpzN-kAX00: YouTube said: Unable to extract vi
deo data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.7\site-packages\gpodder\downl
oad.py", line 787, in run
    self.tempname, reporthook=self.status_updated)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 81, in retrieve_resume
    res = self._ytdl.fetch_video(self._url, tempname, self._my_hook)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 286, in fetch_video
    return ydl.extract_info(url, download=True)
  File "YoutubeDL.py", line 819, in extract_info
  File "YoutubeDL.py", line 624, in report_error
  File "YoutubeDL.py", line 594, in trouble
youtube_dl.utils.DownloadError: ERROR: qqpzN-kAX00: YouTube said: Unable to extr
act video data
1576156862.444336 [gpodder.download] INFO: Thread-1412 is processing: That Time
a Rage Against the Machine Song Was a Christmas Singles #1
1576156862.448242 [gpodder.registry] INFO: custom_downloader resolved by custom_
downloader from youtube-dl: None -> <youtube-dl.YoutubeCustomDownload object at
0x049ada6c>
1576156862.453125 [gpodder.download] INFO: Downloading https://www.youtube.com/w
atch?v=qNn9I-tjLGc with <youtube-dl.YoutubeCustomDownload object at 0x049ada6c>
[youtube] qNn9I-tjLGc: Downloading webpage
[youtube] qNn9I-tjLGc: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
ERROR: qNn9I-tjLGc: YouTube said: Unable to extract video data
1576156862.819336 [gpodder.download] ERROR: Download failed: ERROR: qNn9I-tjLGc:
 YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "YoutubeDL.py", line 796, in extract_info
  File "common.py", line 530, in extract
  File "youtube.py", line 1834, in _real_extract
youtube_dl.utils.ExtractorError: qNn9I-tjLGc: YouTube said: Unable to extract vi
deo data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.7\site-packages\gpodder\downl
oad.py", line 787, in run
    self.tempname, reporthook=self.status_updated)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 81, in retrieve_resume
    res = self._ytdl.fetch_video(self._url, tempname, self._my_hook)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 286, in fetch_video
    return ydl.extract_info(url, download=True)
  File "YoutubeDL.py", line 819, in extract_info
  File "YoutubeDL.py", line 624, in report_error
  File "YoutubeDL.py", line 594, in trouble
youtube_dl.utils.DownloadError: ERROR: qNn9I-tjLGc: YouTube said: Unable to extr
act video data
1576156862.821289 [gpodder.download] INFO: Thread-1412 is processing: This is BB
C Radio 1
1576156862.824219 [gpodder.registry] INFO: custom_downloader resolved by custom_
downloader from youtube-dl: None -> <youtube-dl.YoutubeCustomDownload object at
0x04ad0d0c>
1576156862.825195 [gpodder.download] INFO: Downloading https://www.youtube.com/w
atch?v=RwGWVSsNDYY with <youtube-dl.YoutubeCustomDownload object at 0x04ad0d0c>
[youtube] RwGWVSsNDYY: Downloading webpage
[youtube] RwGWVSsNDYY: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
ERROR: RwGWVSsNDYY: YouTube said: Unable to extract video data
1576156863.297852 [gpodder.download] ERROR: Download failed: ERROR: RwGWVSsNDYY:
 YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "YoutubeDL.py", line 796, in extract_info
  File "common.py", line 530, in extract
  File "youtube.py", line 1834, in _real_extract
youtube_dl.utils.ExtractorError: RwGWVSsNDYY: YouTube said: Unable to extract vi
deo data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.7\site-packages\gpodder\downl
oad.py", line 787, in run
    self.tempname, reporthook=self.status_updated)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 81, in retrieve_resume
    res = self._ytdl.fetch_video(self._url, tempname, self._my_hook)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 286, in fetch_video
    return ydl.extract_info(url, download=True)
  File "YoutubeDL.py", line 819, in extract_info
  File "YoutubeDL.py", line 624, in report_error
  File "YoutubeDL.py", line 594, in trouble
youtube_dl.utils.DownloadError: ERROR: RwGWVSsNDYY: YouTube said: Unable to extr
act video data
1576156863.301758 [gpodder.download] INFO: Thread-1412 is processing: Is Buying
A Cheap Used Land Rover a HUGE Mistake? We Just Sold Ours, But It's Not What You
 Think!
1576156863.308594 [gpodder.registry] INFO: custom_downloader resolved by custom_
downloader from youtube-dl: None -> <youtube-dl.YoutubeCustomDownload object at
0x043e1dac>
1576156863.312500 [gpodder.download] INFO: Downloading https://www.youtube.com/w
atch?v=FMG4tUJLUrM with <youtube-dl.YoutubeCustomDownload object at 0x043e1dac>
[youtube] FMG4tUJLUrM: Downloading webpage
[youtube] FMG4tUJLUrM: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
ERROR: FMG4tUJLUrM: YouTube said: Unable to extract video data
1576156863.883789 [gpodder.download] ERROR: Download failed: ERROR: FMG4tUJLUrM:
 YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "YoutubeDL.py", line 796, in extract_info
  File "common.py", line 530, in extract
  File "youtube.py", line 1834, in _real_extract
youtube_dl.utils.ExtractorError: FMG4tUJLUrM: YouTube said: Unable to extract vi
deo data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.7\site-packages\gpodder\downl
oad.py", line 787, in run
    self.tempname, reporthook=self.status_updated)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 81, in retrieve_resume
    res = self._ytdl.fetch_video(self._url, tempname, self._my_hook)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 286, in fetch_video
    return ydl.extract_info(url, download=True)
  File "YoutubeDL.py", line 819, in extract_info
  File "YoutubeDL.py", line 624, in report_error
  File "YoutubeDL.py", line 594, in trouble
youtube_dl.utils.DownloadError: ERROR: FMG4tUJLUrM: YouTube said: Unable to extr
act video data
1576156863.890625 [gpodder.download] INFO: No more tasks for Thread-1412 to carr
y out.
1576156864.502930 [gpodder.gtkui.main] INFO: All tasks have finished.
1576156864.598633 [gpodder.gtkui.main] INFO: All tasks have finished.
1576158963.052734 [gpodder.download] INFO: 1 tasks to do, can start at most 1 th
reads
1576158963.053711 [gpodder.download] INFO: Starting new worker thread.
1576158963.054688 [gpodder.util] DEBUG: run_in_background: <bound method Downloa
dQueueWorker.run of MainThread> (False)
1576158963.055664 [gpodder.download] INFO: Starting new thread: Thread-1413
1576158963.057617 [gpodder.download] INFO: Thread-1413 is processing: RETRO TECH
: SEGA GENESIS
1576158963.058594 [gpodder.registry] INFO: custom_downloader resolved by custom_
downloader from youtube-dl: None -> <youtube-dl.YoutubeCustomDownload object at
0x043d5d2c>
1576158963.058594 [gpodder.download] INFO: Downloading https://www.youtube.com/w
atch?v=PRVr1heimY8 with <youtube-dl.YoutubeCustomDownload object at 0x043d5d2c>
[youtube] PRVr1heimY8: Downloading webpage
[youtube] PRVr1heimY8: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request
s
ERROR: PRVr1heimY8: YouTube said: Unable to extract video data
1576158963.766602 [gpodder.download] ERROR: Download failed: ERROR: PRVr1heimY8:
 YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "YoutubeDL.py", line 796, in extract_info
  File "common.py", line 530, in extract
  File "youtube.py", line 1834, in _real_extract
youtube_dl.utils.ExtractorError: PRVr1heimY8: YouTube said: Unable to extract vi
deo data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.7\site-packages\gpodder\downl
oad.py", line 787, in run
    self.tempname, reporthook=self.status_updated)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 81, in retrieve_resume
    res = self._ytdl.fetch_video(self._url, tempname, self._my_hook)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\youtube-dl.py",
line 286, in fetch_video
    return ydl.extract_info(url, download=True)
  File "YoutubeDL.py", line 819, in extract_info
  File "YoutubeDL.py", line 624, in report_error
  File "YoutubeDL.py", line 594, in trouble
youtube_dl.utils.DownloadError: ERROR: PRVr1heimY8: YouTube said: Unable to extr
act video data
1576158963.782227 [gpodder.download] INFO: No more tasks for Thread-1413 to carr
y out.
1576158964.793945 [gpodder.gtkui.main] INFO: All tasks have finished.
1576158964.966797 [gpodder.gtkui.main] INFO: All tasks have finished.

**Comment by elelay** [comment]
youtube seems to complain about "Too Many Requests". Is it better when you retry later?

**Comment by Marrib** [comment]
Same or similar error here: Every video that I try to download from YouTube fails with the error message: "Cannot download video".
![Error](https://user-images.githubusercontent.com/40357209/73122149-e3004c00-3f81-11ea-86e7-4117961b3735.jpg)

**Comment by elelay** [comment]
Closing due to inactivity.
