### ISSUE TITLE
Error downloading youtube videos

### ISSUE THREAD

**Issue by TinoJ** [gpodder/gpodder#734]
Hello,
I hope I did not miss an open report.
Since a few weeks I get errors when downloading youtube videos. No restricted access. Not all channels, only some. But I cannot find out why.
I use gpodder portable 3.10.11. (2019-09-29) on Windows. It is the latest portable release. 
The error log for each failed video download looks like:

`gpodder.youtube.YouTubeError: Cannot download video: 
2020-01-23 23:51:01,873 [gpodder.download] ERROR: Download failed: Cannot download video: 
Traceback (most recent call last):
  File "C:\PortableApps\gPodderPortable\App\gPodder\data\lib\python3.7\site-packages\gpodder\download.py", line 790, in run
    res = registry.download_url.resolve(self._config, None, self.episode)
  File "C:\PortableApps\gPodderPortable\App\gPodder\data\lib\python3.7\site-packages\gpodder\registry.py", line 31, in resolve
    result = resolver(item, *args)
  File "C:\PortableApps\gPodderPortable\App\gPodder\data\lib\python3.7\site-packages\gpodder\youtube.py", line 120, in youtube_real_download_url
    res = get_real_download_url(episode.url, fmt_ids)
  File "C:\PortableApps\gPodderPortable\App\gPodder\data\lib\python3.7\site-packages\gpodder\youtube.py", line 169, in get_real_download_url
    fmt_id_url_map = sorted(find_urls(page), reverse=True)
  File "C:\PortableApps\gPodderPortable\App\gPodder\data\lib\python3.7\site-packages\gpodder\youtube.py", line 167, in find_urls
    raise YouTubeError('Cannot download video: %s' % error_message)
gpodder.youtube.YouTubeError: Cannot download video: `

Do you have any idea or can I help with more analysis?

Best, Tino

**Comment by elelay** [comment]
Yes, this is a known issue. #722 contains all the fixes for it and I'll do a release this week-end.
You can use the latest daily build (https://ci.appveyor.com/api/buildjobs/e60xf43a3w065lkc/artifacts/tools%2Fwin_installer%2Fgpodder-3.10.11-portable.exe) to overcome this...

**Comment by elelay** [comment]
#711 is the issue.
