### ISSUE TITLE
gpodder 3.10.13 wont run

### ISSUE THREAD

**Issue by hattiedog** [gpodder/gpodder#757]
hi

i have tried to get various versions of gpodder to work for a long time on windows 10.

v3.9.6 works great. (it is installed in another directory and still works)
I would like to move to the latest version if possible.

But gpodder 3.10.13 wont run
i double clcik on the gpodder icon and nothing happens

i ran gpodder-cmd.exe -v

but i don't understand the info.

C:\Program Files (x86)\gPodder31013\bin>gpodder-cmd.exe -v

Calling SetDllDirectoryW(C:\Program Files (x86)\gPodder31013\bin)
Successfully SetDllDirectoryW
D: windows build; registry home = E:\Podcasts gPodder
1582479095.560560 [gpodder.log] DEBUG: ==== gPodder starts up (ui=gtk) ===
C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\util.py:1647: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(p) is 0:
1582479095.660550 [gpodder.registry] DEBUG: Registering download_url resolver: <function youtube_real_download_url at 0x03b90658>
1582479095.660550 [gpodder.registry] DEBUG: Registering download_url resolver: <function escapist_real_download_url at 0x03a18148>
1582479095.670552 [gpodder.registry] DEBUG: Registering download_url resolver: <function vimeo_real_download_url at 0x03b82ec8>
1582479095.840531 [gpodder.sync] WARNING: Could not find gpod
1582479095.840531 [gpodder.sync] WARNING: Could not find eyed3.mp3
1582479095.920523 [gpodder.gtkui.shownotes] INFO: No WebKit2 gobject bindings, so no HTML shownotes
C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\gtkui\model.py:848: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(channels) is 0:

(gpodder-cmd.exe:3572): GLib-GIO-WARNING **: 17:31:35.950: win32 session dbus binary not found: C:\Program Files (x86)\gPodder31013\bin\\gdbus.exe
1582479095.970520 [gpodder.config] INFO: New default keys added - saving config.1582479095.970520 [gpodder.config] INFO: Flushing settings to disk
1582479095.970520 [gpodder.config] ERROR: Cannot write settings to E:\Podcasts gPodder\Settings.json
1582479095.970520 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "shutil.py", line 781, in move
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'E:\\Podcasts gPodder\\Settings.json.tmp' -> 'E:\\Podcasts gPodder\\Settings.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\gtkui\app.py", line 130, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\core.py", line 39, in __init__
    self.config = config_class(gpodder.config_file)
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\gtkui\config.py", line 100, in __init__
    config.Config.__init__(self, filename)
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\config.py", line 280, in __init__
    self.load()
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\config.py", line 373, in load
    self.save()
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\config.py", line 350, in save
    util.atomic_rename(filename + '.tmp', filename)
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\util.py", line 1758, in atomic_rename
    shutil.move(old_name, new_name)
  File "shutil.py", line 795, in move
  File "shutil.py", line 426, in copy2
  File "shutil.py", line 259, in copyfile
PermissionError: [Errno 13] Permission denied: 'E:\\Podcasts gPodder\\Settings.json'

Traceback (most recent call last):
  File "shutil.py", line 781, in move
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'E:\\Podcasts gPodder\\Settings.json.tmp' -> 'E:\\Podcasts gPodder\\Settings.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\gtkui\app.py", line 130, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\core.py", line 39, in __init__
    self.config = config_class(gpodder.config_file)
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\gtkui\config.py", line 100, in __init__
    config.Config.__init__(self, filename)
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\config.py", line 280, in __init__
    self.load()
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\config.py", line 373, in load
    self.save()
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\config.py", line 350, in save
    util.atomic_rename(filename + '.tmp', filename)
  File "C:\Program Files (x86)\gPodder31013\lib\python3.8\site-packages\gpodder\util.py", line 1758, in atomic_rename
    shutil.move(old_name, new_name)
  File "shutil.py", line 795, in move
  File "shutil.py", line 426, in copy2
  File "shutil.py", line 259, in copyfile
PermissionError: [Errno 13] Permission denied: 'E:\\Podcasts gPodder\\Settings.json'

thanks for any help

**Comment by elelay** [comment]
Warnings are harmless.
The only error is that `E:\Podcasts gPodder\Settings.json` can't be written to.
Can you check file properties for it in the Explorer?

**Comment by hattiedog** [comment]
the E:\Podcasts gPodder\**Settings.json** file was not read only

although it started with a lowercase **s**
**s**ettings.json

however!!

it was dated nov 2019

Probably when I last tried to install a previuos version of 3.10

I could edit and save it (i added a space at the very end - outside the last bracket)

the modification date did change as i would expect.

so i renamed it **old**settings.json

started up 3.10.13 and it looks like it's working.

it created a new **S**ettings.json file

with a capital S

maybe there was some incompatability with the old version!

but I have ran it three times now and it looks ok

it has just downloaded a podcast to a newly subscribed BBC group.
(all the other podcasts were up todate)

thanks for the help

**Comment by elelay** [comment]
thanks for the followup.
For the record, I was not able to reproduce your startup issue (modified Settings.json to --settings.json then settings.json).
