### ISSUE TITLE
Unable to run VLC from flatpak gpodder

### ISSUE THREAD

**Issue by gcarpent** [gpodder/gpodder#782]
I have configured the audio and video player as
`/usr/bin/vlc --started-from-file %U`
but the player does not start. Same behavior with other players.
The log reads:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/vlc': '/usr/bin/vlc'

**Comment by elelay** [comment]
Thanks for reporting!

Try running `gpodder -v` from a terminal.
When I choose to Stream an episode I see the log entry
```
1587584380.044044 [gpodder.gtkui.main] DEBUG: Executing: ['/usr/bin/vlc', '--started-from-file', 'https://dts.podtrac.com/redirect.mp3/media.blubrry.com/makeshiftstories/content.blubrry.com/makeshiftstories/make-shift-stories-188-1.mp3']
```

What do you have?

**Comment by gcarpent** [comment]
In the meantime I have solved the issue by re-installing gpodder from apt. Previously, I had installed the flathub version, which seems to lack some dependencies needed for the streaming functionality.
Now the log reads:
`[gpodder.gtkui.main] DEBUG: Executing: ['/usr/bin/ffplay', 'http://rf.proxycast.org/310ad267-2717-4426-b5cc-78023b8e8c28/12283-21.04.2020-ITEMA_22327950-0-1779455909.m4a']`
Nevertheless, even the apt version of gpodder keeps warning about gpod not being found
`[gpodder.sync] WARNING: Could not find gpod`
and it reports an error related to appindicator
[gpodder.extensions] ERROR: Cannot load ubuntu_appindicator from /usr/share/gpodder/extensions/ubuntu_appindicator.py: No module named 'appindicator'

**Comment by elelay** [comment]
Maybe it's isolated in the flatpak and can't find vlc?

**Comment by godfrey-cw** [comment]
I might be getting the same thing: here's the log

```
#  cat gPodder/Logs/2020-05-03.log
2020-05-03 00:05:11,630 [gpodder.sync] WARNING: Could not find gpod
2020-05-03 00:05:11,631 [gpodder.sync] WARNING: Could not find eyed3.mp3
2020-05-03 00:05:12,765 [gpodder.schema] ERROR: Orphaned episodes found in database
2020-05-03 19:00:24,450 [gpodder.my] WARNING: Flush requested, but sync disabled.
2020-05-03 19:01:52,649 [gpodder.dbsqlite] ERROR: Cannot save <gpodder.gtkui.model.GPodcast object at 0x7fc8f80cfee0>: Incorrect number of bindings supplied. The current statement uses 0, and there are 18 supplied.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gpodder/dbsqlite.py", line 220, in _save_object
    cur.execute(sql, values)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 0, and there are 18 supplied.
2020-05-03 19:01:52,699 [gpodder.gtkui.main] ERROR: Error: Cannot operate on a closed database.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gpodder/gtkui/main.py", line 2617, in update_feed_cache_proc
    channel.update(max_episodes=self.config.max_episodes_per_feed)
  File "/usr/lib/python3.8/site-packages/gpodder/model.py", line 1152, in update
    self.save()
  File "/usr/lib/python3.8/site-packages/gpodder/model.py", line 1186, in save
    self.db.save_podcast(self)
  File "/usr/lib/python3.8/site-packages/gpodder/dbsqlite.py", line 199, in save_podcast
    self._save_object(podcast, self.TABLE_PODCAST, schema.PodcastColumns)
  File "/usr/lib/python3.8/site-packages/gpodder/dbsqlite.py", line 224, in _save_object
    cur.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.
2020-05-03 19:01:52,854 [gpodder.schema] ERROR: Orphaned episodes found in database
2020-05-03 19:01:55,493 [gpodder.sync] WARNING: Could not find gpod
2020-05-03 19:01:55,493 [gpodder.sync] WARNING: Could not find eyed3.mp3
2020-05-03 19:01:55,798 [gpodder.schema] ERROR: Orphaned episodes found in database
2020-05-03 19:02:56,592 [gpodder.my] WARNING: Flush requested, but sync disabled.
2020-05-03 19:03:14,456 [gpodder.my] WARNING: Flush requested, but sync disabled.
2020-05-03 19:07:01,626 [gpodder.sync] WARNING: Could not find gpod
2020-05-03 19:07:01,626 [gpodder.sync] WARNING: Could not find eyed3.mp3
2020-05-03 19:07:01,937 [gpodder.schema] ERROR: Orphaned episodes found in database
2020-05-03 20:05:12,937 [gpodder.my] WARNING: Flush requested, but sync disabled.

```

also `gpo -h` gives
```
Could not find gpod
Could not find eyed3.mp3
1588562521.127216 [gpodder.schema] ERROR: Orphaned episodes found in database
The requested function is not available.
```

**Comment by KVAnton-WEB** [comment]
> Maybe it's isolated in the flatpak and can't find vlc?
yes, but how to fix it?

**Comment by KVAnton-WEB** [comment]
```
1606222567.846200 [gpodder.gtkui.main] ERROR: Error in playback!
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/gpodder/gtkui/main.py", line 2109, in playback_episodes
    self.playback_episodes_for_real(episodes)
  File "/app/lib/python3.7/site-packages/gpodder/gtkui/main.py", line 2094, in playback_episodes_for_real
    util.Popen(command, close_fds=True)
  File "/app/lib/python3.7/site-packages/gpodder/util.py", line 2028, in __init__
    super(Popen, self).__init__(*args, **kwargs)  # Python 2 syntax
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/vlc': '/usr/bin/vlc'
```
```

**Comment by KVAnton-WEB** [comment]
Of course `/usr/bin/vlc` exists

**Comment by elelay** [comment]
But it's not visible from the flatpak app I suppose. flatpack is a sandbox mechanism. 
Please bring the issue here: https://github.com/flathub/org.gpodder.gpodder where you'll have better chance to get an answer.
