### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER (_ssl.c:1108)

### ISSUE THREAD

**Issue by engineerjoe440** [gpodder/gpodder#824]
Hey there! I was just starting to explore this project, and installed on Windows 10 using the installer (version 3.10.15). The app itself opens just fine (and looks awesome, btw), and the CMD interface is sweet too...
Trouble I'm having is related to downloading podcasts from an RSS feed. I tried Python Bytes and The Amp Hour, but both of them are failing due to a SSL mismatched version number (according to the traceback). Any thoughts or suggestions? Traceback shown below:

```
gpo> download https://pythonbytes.fm/episodes/rss
Python Bytes
1592277836.355461 [gpodder.download] ERROR: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108) while downloading "#160 Your JSON shall be streamed": None
Traceback (most recent call last):
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1399, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 863, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 402, in retrieve_resume
    headers, real_url = downloader.retrieve_resume(url,
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 315, in retrieve_resume
    fp = self.open(url, data)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1399, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
OSError: [Errno socket error] [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)
Downloading #160 Your JSON shall be streamed                             [DONE]
1592277836.383811 [gpodder.download] ERROR: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108) while downloading "#161 Sloppy Python can mean fast answers!": None
Traceback (most recent call last):
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1399, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)
```

Note that the traceback above continues to repeat for all 26 (or so) available episodes. Any thoughts? Thank you so much for the work on this project!

**Comment by auouymous** [comment]
I was able to download the feed from pythonbytes.fm but episodes redirect to downloads.talkpython.fm which times out in gpodder, firefox and wget. What is the URL for the other feed?

**Comment by elelay** [comment]
I can be an old version of openssl libraries in the system path.
See https://github.com/gpodder/gpodder/issues/495 for debugging procedure using procmon...
Thanks,

**Comment by engineerjoe440** [comment]
Sorry about the super delayed response... Just checked OpenSSL versions from command line and found a couple instances that were from late '19... Updated the packages they were installed in (old copy of Git floating on my system) so that versions were reflected as shown below:
![image](https://user-images.githubusercontent.com/33275230/87627432-95b89800-c6e3-11ea-9c8c-4bb446bf442a.png)

Restarted gPodder, and was able to download *some* podcast episodes, but not all.... Any thoughts?

I've also captured the log as had been described in #495 (attached csv with .txt extension) 
[Logfile.CSV.txt](https://github.com/gpodder/gpodder/files/4929364/Logfile.CSV.txt)

**Comment by elelay** [comment]
Thanks! I'll look into it.

**Comment by elelay** [comment]
All dll access seem in the gPodder directory according to Logfile.CSV.
Maybe there is an actual problem with the episodes failing to download?
Do you still get wrong version number errors?

**Comment by engineerjoe440** [comment]
Gosh!!! I'm sorry that I never responded!!! For some reason, I thought I had already.

I tried again with a different episode (since you'd suggested that it might have been linked to the episodes), and it worked marvelously! I've been using it off and on now for over a month with no further issues!

Again, I'm terribly sorry for not responding!

**Comment by elelay** [comment]
Hi, good to know it's working for you :-)
No worries: I've closed a dozen blocked tickets Yesterday...
