### ISSUE TITLE
"OSError: [Errno 11004] getaddrinfo failed" on some podcasts

### ISSUE THREAD

**Issue by SteveHeist** [gpodder/gpodder#825]
I have attempted to sync my podcasts I had connected to my phone via AntennaPod, and have run into an issue. The Rooster Teeth podcasts I have (from feeds.megaphone.fm) run into Errno 11004 and a slew of other errors (seemingly associated with it). Here's a log breakdown:

`gpo> download
The Technical Difficulties
1592630417.964473 [gpodder.download] ERROR: HTTP 404 while downloading "TV Pilot One: Google Street View Race, The Battle of the Beer, and Date This Man": Not Found
Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 863, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 402, in retrieve_resume
    headers, real_url = downloader.retrieve_resume(url,
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 315, in retrieve_resume
    fp = self.open(url, data)
  File "request.py", line 1759, in open
  File "request.py", line 1937, in open_http
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2172, in http_error_301
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1953, in http_error
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 259, in http_error_default
    raise gPodderDownloadHTTPError(url, errcode, errmsg)
gpodder.download.gPodderDownloadHTTPError: ('//www.techdif.co.uk/podcast/show1-final.mp4', 404, 'Not Found')
Downloading TV Pilot One: Google Street View Race, The Battle of the B...[DONE]
Keyboard interrupt.
Downloading TV Pilot Two: Monument Morse, The Battle of the Beer and T...gpo> download
The Technical Difficulties
1592630426.650040 [gpodder_launch.gpo] WARNING: Action could not be completed
Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder_launch\gpo.py", line 216, in _action
    yield
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder_launch\gpo.py", line 616, in _download_episode
    task = download.DownloadTask(episode, self._config)
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 684, in __init__
    assert episode.download_task is None
AssertionError
Downloading TV Pilot One: Google Street View Race, The Battle of the B...[FAIL]
1592630426.651049 [gpodder_launch.gpo] WARNING: Action could not be completed
Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder_launch\gpo.py", line 216, in _action
    yield
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder_launch\gpo.py", line 616, in _download_episode
    task = download.DownloadTask(episode, self._config)
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 684, in __init__
    assert episode.download_task is None
AssertionError
Downloading TV Pilot Two: Monument Morse, The Battle of the Beer and T...[FAIL]
1592630427.966450 [gpodder.download] ERROR: HTTP 404 while downloading "TV Pilot Three: The Iron Chefs, The Battle of the Beer and The Cone": Not Found
Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 863, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 402, in retrieve_resume
    headers, real_url = downloader.retrieve_resume(url,
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 315, in retrieve_resume
    fp = self.open(url, data)
  File "request.py", line 1759, in open
  File "request.py", line 1937, in open_http
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2172, in http_error_301
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1953, in http_error
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 259, in http_error_default
    raise gPodderDownloadHTTPError(url, errcode, errmsg)
gpodder.download.gPodderDownloadHTTPError: ('//www.techdif.co.uk/podcast/show3-final.mp4', 404, 'Not Found')
Downloading TV Pilot Three: The Iron Chefs, The Battle of the Beer and...[DONE]
Off Topic
1592630430.603605 [gpodder.download] ERROR: [Errno socket error] [Errno socket error] [Errno 11004] getaddrinfo failed while downloading "Hey! You Dead?! - #41": None
Traceback (most recent call last):
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1392, in connect
  File "client.py", line 915, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1392, in connect
  File "client.py", line 915, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
OSError: [Errno socket error] [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1392, in connect
  File "client.py", line 915, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
OSError: [Errno socket error] [Errno socket error] [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 863, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 402, in retrieve_resume
    headers, real_url = downloader.retrieve_resume(url,
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 315, in retrieve_resume
    fp = self.open(url, data)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1392, in connect
  File "client.py", line 915, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
OSError: [Errno socket error] [Errno socket error] [Errno socket error] [Errno 11004] getaddrinfo failed
Downloading Hey! You Dead?! - #41                                        [DONE]
1592630433.675843 [gpodder.download] ERROR: [Errno socket error] [Errno socket error] [Errno 11004] getaddrinfo failed while downloading "Geoff’s on the Fussy Bus! - #42": None
Traceback (most recent call last):
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1392, in connect
  File "client.py", line 915, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1392, in connect
  File "client.py", line 915, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
OSError: [Errno socket error] [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1392, in connect
  File "client.py", line 915, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
OSError: [Errno socket error] [Errno socket error] [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 863, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 402, in retrieve_resume
    headers, real_url = downloader.retrieve_resume(url,
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 315, in retrieve_resume
    fp = self.open(url, data)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1392, in connect
  File "client.py", line 915, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
OSError: [Errno socket error] [Errno socket error] [Errno socket error] [Errno 11004] getaddrinfo failed
Downloading Geoff’s on the Fussy Bus! - #42                              [DONE]
1592630435.765965 [gpodder.download] ERROR: [Errno socket error] [Errno socket error] [Errno 11004] getaddrinfo failed while downloading "I’m Woefully Straight - #43": None
Traceback (most recent call last):
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1392, in connect
  File "client.py", line 915, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1392, in connect
  File "client.py", line 915, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
OSError: [Errno socket error] [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1392, in connect
  File "client.py", line 915, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
OSError: [Errno socket error] [Errno socket error] [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 863, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 402, in retrieve_resume
    headers, real_url = downloader.retrieve_resume(url,
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 315, in retrieve_resume
    fp = self.open(url, data)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1931, in _open_generic_http
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "request.py", line 1949, in http_error
  File "request.py", line 2136, in http_error_302
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\download.py", line 278, in redirect_internal
    return self.open(newurl)
  File "request.py", line 1765, in open
  File "request.py", line 1759, in open
  File "request.py", line 1968, in open_https
  File "request.py", line 1917, in _open_generic_http
  File "client.py", line 1230, in request
  File "client.py", line 1276, in _send_request
  File "client.py", line 1225, in endheaders
  File "client.py", line 1004, in _send_output
  File "client.py", line 944, in send
  File "client.py", line 1392, in connect
  File "client.py", line 915, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
OSError: [Errno socket error] [Errno socket error] [Errno socket error] [Errno 11004] getaddrinfo failed
Downloading I’m Woefully Straight - #43                                  [DONE]
Keyboard interrupt.
Downloading You’re F@#$ing at a High School Level - #44                  gpo>`

Not sure what I'm running into here. Figured I should let somebody know. 

URL of (one of) the podcasts I was trying to download: https://feeds.megaphone.fm:443/offtopic

**Comment by elelay** [comment]
Thanks for reporting!
The "offtopic" feed works for me. This is almost always a temporary bad feed, DNS issue or such transient failure.
