### ISSUE TITLE
How do i install podcastparser

### ISSUE THREAD

**Issue by clort81** [gpodder/gpodder#831]
I've made some progress installing gpodder via following steps.

*git clone https://github.com/gpodder/gpodder.git
*cd gpodder
*as root: make install
*extract gpodder from .deb and copy ./usr tree to /usr 
*run gpodder
returns:
```
$ /usr/bin/gpodder

    Warning: python-dbus not found. Disabling D-Bus support.
    

  Error: Module "podcastparser" (python-podcastparser) not found.
         The podcastparser module can be downloaded from
         http://gpodder.org/podcastparser/

  From a source checkout, you can download local copies of all
  CLI dependencies for debugging (will be placed into "src/"):

      python3 tools/localdepends.py
```

So I
git clone https://github.com/gpodder/podcastparser

Now what?  
cp podcastparser.py /usr/lib/python3/dist-packages/gpodder/

didn't help.

Thanks!

**Comment by clort81** [comment]
I found debian has packages for   python3-mygpoclient python3-podcastparser

So i try 
```
apt purge -y dbus-x11 gpodder
apt  install python3-mygpoclient python3-podcastparser
/pr/gpodder# make install
```
and now i get
```
/pr/gpodder$ gpodder

    Warning: python-dbus not found. Disabling D-Bus support.
    
Traceback (most recent call last):
  File "/usr/bin/gpodder", line 164, in <module>
    main()
  File "/usr/bin/gpodder", line 86, in main
    _ = gpodder.gettext
AttributeError: module 'gpodder' has no attribute 'gettext
```

**Comment by elelay** [comment]
You must have a remaining part of gPodder in your python libraries.
