### ISSUE TITLE
command_on_download not passing filename?

### ISSUE THREAD

**Issue by tordenflesk** [gpodder/gpodder#833]
my command: r128gain -a -s "$filename" doesn't resolve. Shows up in Task Manager as r128gain -a -s "$filename"

**Comment by auouymous** [comment]
Works for me on linux. Maybe windows doesn't support accessing environment variables with a dollar sign. Try `%filename%`.

**Comment by tordenflesk** [comment]
Yes, that worked.

**Comment by tordenflesk** [comment]
Unfortunately, running the command seems to prevent the mutagen extension from modifying tags, presumably because the file's in use by R128Gain. Also it doesn't seem to trigger at all when run with gpo.exe

**Comment by auouymous** [comment]
I don't have mutagen to test the tagging extension, but I cloned the command_on_download extension and gpodder ran both commands back to back. The command run by command_on_download should be completely finished by the time mutagen runs.

I fixed command_on_download to work in gpo. The tagging extension doesn't specify what it works with, does it work in gpo if you disable command_on_download? The same fix might also work for it but I have no way to verify it.

**Comment by tordenflesk** [comment]
Yes, it works if the file isn't locked by another process. r128Gain takes about 10-15 seconds to process the replaygain of the file, so I'm guessing the tagging extension isn't able to modify the file while it's locked.

**Comment by auouymous** [comment]
The command_on_download extension waits for the command to finish before it exits. And each extension appears to be run in order, not in parallel. Unless r128gain forks another process and terminates, it should be finished before tagging runs. Can you change the command to `r128gain -a -s "%filename%" ; echo done`, run gpodder from shell and see if the done message appears before the command is finished running?

**Comment by tordenflesk** [comment]
It "works", the file appears to get scanned and tagged correctly by both mutagen and R128Gain, but Gpodder doesn't seem happy about it:
```
λ gpo download https://feed.pod.space/krigsrevyen 78a05c4e335ff8f681c80fa36b25a896
Calling SetDllDirectoryW(C:\Program Files (x86)\gPodder\bin)
Successfully SetDllDirectoryW
D: windows build; registry home = E:\Podcasts
Krigsrevyen
File ';' MutagenError: [Errno 2] No such file or directory: ';'
File 'echo' MutagenError: [Errno 2] No such file or directory: 'echo'
File 'done' MutagenError: [Errno 2] No such file or directory: 'done'
Analyzing loudness of file 'E:\\Podcasts\\Downloads\\Krigsrevyen\\1-krigsrevyen-26-05-20-ep-7-v1.mp3'...
Analyzing loudness of file 'E:\\Podcasts\\Downloads\\Krigsrevyen\\1-krigsrevyen-26-05-20-ep-7-v1.mp3'...
File 'E:\\Podcasts\\Downloads\\Krigsrevyen\\1-krigsrevyen-26-05-20-ep-7-v1.mp3': loudness = -12.3 LUFS, sample peak = 0.0 dBFS
File ';': loudness = SKIPPED, sample peak = SKIPPED
File 'echo': loudness = SKIPPED, sample peak = SKIPPED
File 'done': loudness = SKIPPED, sample peak = SKIPPED
Album 'E:\\Podcasts\\Downloads\\Krigsrevyen': loudness = -12.3 LUFS, sample peak = 0.0 dBFS
Tagging file 'E:\\Podcasts\\Downloads\\Krigsrevyen\\1-krigsrevyen-26-05-20-ep-7-v1.mp3'
Tagging file ';'
Failed to tag file ';': FileNotFoundError [WinError 2] The system cannot find the file specified: ';'
Tagging file 'echo'
Failed to tag file 'echo': FileNotFoundError [WinError 2] The system cannot find the file specified: 'echo'
Tagging file 'done'
Failed to tag file 'done': FileNotFoundError [WinError 2] The system cannot find the file specified: 'done'
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "r128gain\__main__.py", line 7, in <module>
  File "Z:\data\Projets\r128gain\r128gain\__init__.py", line 803, in cl_main
NameError: name 'exit' is not defined
1593566732.419862 [command_on_download] WARNING: r128gain -a -s "%filename%" ; echo done run with exit code 1
Downloading #7: 21. - 28. mai 1940                                       [DONE]
1 episodes downloaded.
```

**Comment by auouymous** [comment]
The semicolon ends one command and starts another on Linux (allowing multiple commands on one line), that apparently isn't the case on Windows. Maybe try replacing the semicolon with `&&`.

**Comment by tordenflesk** [comment]
Yup, that turned out a lot cleaner. :+1:

**Comment by auouymous** [comment]
The `&& echo done` made it work? Did it display `done` after the 10-15 seconds or earlier before r128gain was finished?

**Comment by tordenflesk** [comment]
'done' was displayed right after R128Gain was finished yes. Mutagen and R128Gain tags were applied correctly. :)

**Comment by auouymous** [comment]
Strange. You could leave this open and maybe @elelay can see something I missed. It would be better to find a real fix in gpodder instead of running an echo after the command.
