### ISSUE TITLE
CPU usage at 100%

### ISSUE THREAD

**Issue by nedkellddv** [gpodder/gpodder#842]
Hi 

Got an issue, that gpodder is using 100% cpu. My system is Linux Mint 19.3, I tried to upgrade to the latest 3.10.16 version, but it is the same problem. If I start gpodder in a terminal I get the following errors

```
1594480382.267973 [gpodder.my] WARNING: Exception while polling for episodes.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mygpoclient/http.py", line 133, in _request
    response = self._opener.open(request)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/my.py", line 501, in synchronize_episodes
    changes = self._client.download_episode_actions(since_o.since)
  File "/usr/lib/python3/dist-packages/mygpoclient/simple.py", line 38, in _wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/mygpoclient/api.py", line 348, in download_episode_actions
    data = self._client.GET(uri)
  File "/usr/lib/python3/dist-packages/mygpoclient/http.py", line 147, in GET
    return self._request('GET', uri, None)
  File "/usr/lib/python3/dist-packages/mygpoclient/http.py", line 142, in _request
    raise UnknownResponse(http_error.code)
mygpoclient.http.UnknownResponse: 500 
```
Any ideas of what might be the problem?

**Comment by auouymous** [comment]
The errors mention mygpoclient, do you use gpodder.net? It might have been having issues when you started gpodder, does gpodder.net load in a browser?
