### ISSUE TITLE
YouTube issue: "Could not add some podcasts: Could not parse feed: <unknown>:1:0: syntax error"

### ISSUE THREAD

**Issue by paulhaddon** [gpodder/gpodder#844]
With gPodder 3.10.16 when trying to add YouTube channels I am sometimes receiving the error message 

"Could not add some podcasts"
"Could not parse feed: <unknown>:1:0: syntax error"

All of them are of the url format 

https://www.youtube.com/c/TheChannelName/videos 

eg:   https://www.youtube.com/c/TomPembertonFarmLife/videos

(note that old-style channels with IDs such as "https://www.youtube.com/feeds/videos.xml?channel_id=UCRDdEVmlqf-dg8PYeqc7SCg" are working correctly)

A copy of the page supplied by YouTube: 
https://www.dropbox.com/s/oha4iq99pujgs0l/sampleXML_TomPembertonFarmLife?dl=0

A dump of the console error is as follows:

 ```
   1594548095.806381 [gpodder.gtkui.main] ERROR: Subscription error: Could not parse feed: <unknown>:1:0: syntax error
    Traceback (most recent call last):
      File "/usr/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
        self._parser.Parse(data, isFinal)
    xml.parsers.expat.ExpatError: syntax error: line 1, column 0
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/gpodder/src/podcastparser.py", line 805, in parse
        sax.parse(stream, handler)
      File "/usr/lib/python3.6/xml/sax/__init__.py", line 33, in parse
        parser.parse(source)
      File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
        xmlreader.IncrementalParser.parse(self, source)
      File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
        self.feed(buffer)
      File "/usr/lib/python3.6/xml/sax/expatreader.py", line 221, in feed
        self._err_handler.fatalError(exc)
      File "/usr/lib/python3.6/xml/sax/handler.py", line 38, in fatalError
        raise exception
    xml.sax._exceptions.SAXParseException: <unknown>:1:0: syntax error
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/gpodder/src/gpodder/feedcore.py", line 223, in _parse_feed
        feed = podcastparser.parse(url, data)
      File "/root/gpodder/src/podcastparser.py", line 807, in parse
        raise FeedParseError(e.getMessage(), e.getException(), e._locator)
    podcastparser.FeedParseError: <unknown>:1:0: syntax error
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/gpodder/src/gpodder/gtkui/main.py", line 2454, in thread_proc
        max_episodes=self.config.max_episodes_per_feed)
      File "/root/gpodder/src/gpodder/model.py", line 1371, in load_podcast
        max_episodes)
      File "/root/gpodder/src/gpodder/model.py", line 960, in load
        tmp.update(max_episodes)
      File "/root/gpodder/src/gpodder/model.py", line 1136, in update
        result = self.feed_fetcher.fetch_channel(self, max_episodes)
      File "/root/gpodder/src/gpodder/model.py", line 195, in fetch_channel
        res = self.fetch(url, channel.http_etag, channel.http_last_modified, max_episodes)
      File "/root/gpodder/src/gpodder/feedcore.py", line 236, in fetch
        return self._parse_feed(url, etag, modified, max_episodes)
      File "/root/gpodder/src/gpodder/feedcore.py", line 226, in _parse_feed
        raise InvalidFeed('Could not parse feed: {msg}'.format(msg=e))
    gpodder.feedcore.InvalidFeed: Could not parse feed: <unknown>:1:0: syntax error
```

**Comment by auouymous** [comment]
That page lacks a <link> tag for the RSS feed, some /c/{user} pages have it, others don't. The channel ID can be found in the `<link rel="canonical" href="https://www.youtube.com/channel/UCuNIKo9EMJZ_FdZfGnM9G1w">` tag on that page, which can then be used to subscribe. I'll post a PR if I can figure out how to automate it.
