### ISSUE TITLE
New error: ERROR: Download failed: escapist_real_download_url() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by dieterdeyke** [gpodder/gpodder#874]
Using gpo I now get 

1600093940.489106 [gpodder.download] ERROR: Download failed: escapist_real_download_url() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/usr/local/gpodder/src/gpodder/download.py", line 861, in run
    downloader = DefaultDownloader.custom_downloader(self._config, self.episode)
  File "/usr/local/gpodder/src/gpodder/download.py", line 431, in custom_downloader
    res = registry.download_url.resolve(config, None, episode, False)
  File "/usr/local/gpodder/src/gpodder/registry.py", line 31, in resolve
    result = resolver(item, *args)
TypeError: escapist_real_download_url() takes 2 positional arguments but 3 were given

**Comment by highflux7** [comment]
Seeing same here.  All new podcast episodes.

**Comment by auouymous** [comment]
My bad! That PR will fix it.
