### ISSUE TITLE
Failed: I/O Error

### ISSUE THREAD

**Issue by v758** [gpodder/gpodder#887]
Hello,

I've been using gPodder successfully for several years. Thank you for your work. Its a great platform. I've been listening to this particular podcast source without any issues until recently.

https://townhall.com/podcasts/camandco/

rss feed: https://townhall.com/feed/v1/podcast/camandco

all the episodes and info come up, except I get this error when trying to download the episodes

Failed: I/O Error: [Errno socket error] [Errno -2] Name or service not known: None - Bearing Arms&#x27; Cam &amp; Co

all my other podcasts work fine.. any help would be appreciated

Thanks, V

**Comment by auouymous** [comment]
There is an issue between your DNS and their nameserver. Usually temporary, unless your ISP has banned them. Works fine for me.

**Comment by v758** [comment]
thanks for responding.  its been like this for a few weeks now..

**Comment by auouymous** [comment]
Does this tracker link work in a browser? https://chtbl.com/track/8D145/https://cdn.townhall.com/podcasts/9/2020-10/102020-cam-and-co.mp3

If so, is your browser using different DNS, proxy or vpn settings than the rest of the system? wget? curl?

**Comment by v758** [comment]
yes the tracker link works

**Comment by v758** [comment]
not that im aware of my browser using a different DNS...  like I said all the other podcasts work fine.. it seems any of the townhall respond with the error

**Comment by auouymous** [comment]
Can you turn on debugging (the -v command line option), try to download an episode and post the log?

**Comment by v758** [comment]
lets see.. i will give it a try

**Comment by v758** [comment]
I am running linux mint, how would I turn debugging on?

**Comment by v758** [comment]
1603241758.738542 [gpodder.dbsqlite] INFO: Loading episodes for podcast 17
1603241758.758295 [gpodder.my] INFO: Reloading settings.
1603241758.758749 [gpodder.util] DEBUG: run_in_background: <bound method UserAppsReader.read of <gpodder.gtkui.desktopfile.UserAppsReader object at 0x7f61cfacf5f8>> (False)
1603241758.924248 [gpodder.util] DEBUG: run_in_background: <bound method gPodder.find_partial_downloads of <gpodder.gtkui.main.gPodder at /gui at 0x7f6227c0d7f0>> (False)
1603241758.924555 [gpodder.gtkui.main] DEBUG: Setting up auto update timer with interval 20.
1603241796.871359 [gpodder.gtkui.main] DEBUG: Downloading episode: The Truth Behind William McRaven's "Support" for the 2A
1603241796.872749 [gpodder.model] INFO: Setting download filename: 102020-cam-and-co.mp3
1603241796.921660 [gpodder.gtkui.main] INFO: All tasks have finished.
1603241796.959515 [gpodder.gtkui.main] INFO: All tasks have finished.
1603241796.992723 [gpodder.my] DEBUG: Storing 1 episode download actions
1603241796.994432 [gpodder.download] INFO: Starting new worker thread.
1603241796.994760 [gpodder.util] DEBUG: run_in_background: <bound method DownloadQueueWorker.run of MainThread> (False)
1603241796.995192 [gpodder.download] INFO: Starting new thread: Thread-3
1603241796.996672 [gpodder.download] INFO: Thread-3 is processing: The Truth Behind William McRaven's "Support" for the 2A
1603241797.165805 [gpodder.download] ERROR: [Errno socket error] [Errno -2] Name or service not known while downloading "The Truth Behind William McRaven's "Support" for the 2A": None
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1764, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.6/urllib/request.py", line 1974, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1923, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1434, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 952, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1764, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.6/urllib/request.py", line 1974, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1939, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1955, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python3.6/urllib/request.py", line 2143, in http_error_302
    headers, data)
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 238, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python3.6/urllib/request.py", line 1770, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.6/urllib/request.py", line 1764, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.6/urllib/request.py", line 1974, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1923, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1434, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 952, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno socket error] [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 766, in run
    self.tempname, reporthook=self.status_updated)
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 275, in retrieve_resume
    fp = self.open(url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1770, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.6/urllib/request.py", line 1764, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.6/urllib/request.py", line 1974, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1939, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1955, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python3.6/urllib/request.py", line 2143, in http_error_302
    headers, data)
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 238, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python3.6/urllib/request.py", line 1770, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.6/urllib/request.py", line 1764, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.6/urllib/request.py", line 1974, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1923, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1434, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 952, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno socket error] [Errno socket error] [Errno -2] Name or service not known
1603241797.167120 [gpodder.download] INFO: No more tasks for Thread-3 to carry out.
1603241798.522658 [gpodder.gtkui.main] INFO: All tasks have finished.
1603241798.561896 [gpodder.gtkui.main] INFO: All tasks have finished.

**Comment by v758** [comment]
this one works:
1603242237.925417 [gpodder.dbsqlite] INFO: Loading episodes for podcast 17
1603242237.946397 [gpodder.my] INFO: Reloading settings.
1603242237.946837 [gpodder.util] DEBUG: run_in_background: <bound method UserAppsReader.read of <gpodder.gtkui.desktopfile.UserAppsReader object at 0x7f84dd8475f8>> (False)
1603242238.120625 [gpodder.util] DEBUG: run_in_background: <bound method gPodder.find_partial_downloads of <gpodder.gtkui.main.gPodder at /gui at 0x7f84f5847828>> (False)
1603242238.120946 [gpodder.gtkui.main] DEBUG: Setting up auto update timer with interval 20.
1603242254.416643 [gpodder.gtkui.main] DEBUG: Downloading episode: STL226: Buying a used drill press with Rollie Johnson
1603242254.418044 [gpodder.model] INFO: Setting download filename: shop-talk-live-episode-226.mp3
1603242254.475543 [gpodder.gtkui.main] INFO: All tasks have finished.
1603242254.517629 [gpodder.gtkui.main] INFO: All tasks have finished.
1603242254.554123 [gpodder.my] DEBUG: Storing 1 episode download actions
1603242254.555455 [gpodder.download] INFO: Starting new worker thread.
1603242254.555587 [gpodder.util] DEBUG: run_in_background: <bound method DownloadQueueWorker.run of MainThread> (False)
1603242254.556039 [gpodder.download] INFO: Starting new thread: Thread-3
1603242254.558208 [gpodder.download] INFO: Thread-3 is processing: STL226: Buying a used drill press with Rollie Johnson
1603242269.074906 [gpodder.download] INFO: Download was redirected (http://hwcdn.libsyn.com/p/1/2/b/12b8e7f400f977e1/shop-talk-live-episode-226.mp3?c_id=85566320&cs_id=85566320&destination_id=113998&expiration=1603247776&hwt=8b45d10317b4e5ff04d05f4c5f76e215). New filename: shop-talk-live-episode-226.mp3
1603242269.076402 [gpodder.download] INFO: No more tasks for Thread-3 to carry out.
1603242269.575000 [gpodder.gtkui.main] INFO: All tasks have finished.
1603242269.629246 [gpodder.gtkui.main] INFO: All tasks have finished.

**Comment by v758** [comment]
heres another one that works:
1603242651.218799 [gpodder.dbsqlite] INFO: Loading episodes for podcast 17
1603242651.239024 [gpodder.my] INFO: Reloading settings.
1603242651.239472 [gpodder.util] DEBUG: run_in_background: <bound method UserAppsReader.read of <gpodder.gtkui.desktopfile.UserAppsReader object at 0x7f813e68f630>> (False)
1603242651.405618 [gpodder.util] DEBUG: run_in_background: <bound method gPodder.find_partial_downloads of <gpodder.gtkui.main.gPodder at /gui at 0x7f81967d77b8>> (False)
1603242651.405934 [gpodder.gtkui.main] DEBUG: Setting up auto update timer with interval 20.
1603242664.234931 [gpodder.util] DEBUG: run_in_background: <bound method Config.save_thread_proc of <gpodder.gtkui.config.UIConfig object at 0x7f81967cdc88>> (True)
1603242670.632911 [gpodder.gtkui.main] DEBUG: Downloading episode: Episode 174: Once Upon a Time in the Wild Wild West
1603242670.633790 [gpodder.model] INFO: Setting download filename: Episode_174_Once_Upon_a_Time_in_the_Wild_Wild_West.mp3
1603242670.680915 [gpodder.gtkui.main] INFO: All tasks have finished.
1603242670.718382 [gpodder.gtkui.main] INFO: All tasks have finished.
1603242670.752447 [gpodder.my] DEBUG: Storing 1 episode download actions
1603242670.753781 [gpodder.download] INFO: Starting new worker thread.
1603242670.753892 [gpodder.util] DEBUG: run_in_background: <bound method DownloadQueueWorker.run of MainThread> (False)
1603242670.754098 [gpodder.download] INFO: Starting new thread: Thread-4
1603242670.754907 [gpodder.download] INFO: Thread-4 is processing: Episode 174: Once Upon a Time in the Wild Wild West
1603242673.758649 [gpodder.download] INFO: Download was redirected (http://hwcdn.libsyn.com/p/4/6/d/46d4ab339e1ea9c7/Episode_174_Once_Upon_a_Time_in_the_Wild_Wild_West.mp3?c_id=86224493&cs_id=86224493&destination_id=323283&expiration=1603243382&hwt=36763a27a053f4664c3d219d3c9a51ac). New filename: Episode_174_Once_Upon_a_Time_in_the_Wild_Wild_West.mp3
1603242673.759432 [gpodder.download] INFO: No more tasks for Thread-4 to carry out.
1603242675.278589 [gpodder.gtkui.main] INFO: All tasks have finished.
1603242675.319319 [gpodder.gtkui.main] INFO: All tasks have finished.

**Comment by auouymous** [comment]
Can you open a terminal, run `python3` and paste the following two lines into it?

```
import urllib.request
urllib.request.FancyURLopener().open('https://chtbl.com/track/8D145/https://cdn.townhall.com/podcasts/9/2020-10/102020-cam-and-co.mp3', None)
```

Does it throw the `OSError: [Errno socket error] [Errno -2] Name or service not known` error?

Press `ctrl-d` twice to exit python and the terminal.

**Comment by v758** [comment]
v@v-desktop:~$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.request
>>> urllib.request.FancyURLopener().open('https://chtbl.com/track/8D145/https://cdn.townhall.com/podcasts/9/2020-10/102020-cam-and-co.mp3', None)
<addinfourl at 140365721603432 whose fp = <http.client.HTTPResponse object at 0x7fa970f98b38>>

**Comment by v758** [comment]
i dont know if I did it right:
syntax
>>> Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
  File "<stdin>", line 1
    Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
             ^
SyntaxError: invalid syntax
>>> [GCC 8.4.0] on linux
  File "<stdin>", line 1
    [GCC 8.4.0] on linux
           ^
SyntaxError: invalid syntax
>>> Type "help", "copyright", "credits" or "license" for more information.
  File "<stdin>", line 1
    Type "help", "copyright", "credits" or "license" for more information.
              ^
SyntaxError: invalid syntax
>>> >>> import urllib.request
  File "<stdin>", line 1
    >>> import urllib.request
     ^
SyntaxError: invalid syntax
>>> >>> urllib.request.FancyURLopener().open('https://chtbl.com/track/8D145/https://cdn.townhall.com/podcasts/9/2020-10/102020-cam-and-co.mp3', None)
  File "<stdin>", line 1
    >>> urllib.request.FancyURLopener().open('https://chtbl.com/track/8D145/https://cdn.townhall.com/podcasts/9/2020-10/102020-cam-and-co.mp3', None)
     ^
SyntaxError: invalid syntax
>>> <addinfourl at 140365721603432 whose fp = <http.client.HTTPResponse object at 0x7fa970f98b38>>
  File "<stdin>", line 1
    <addinfourl at 140365721603432 whose fp = <http.client.HTTPResponse object at 0x7fa970f98b38>>
    ^
SyntaxError: invalid syntax
>>>

**Comment by auouymous** [comment]
Could you upgrade to gpodder 3.10.16 and re-post the debug log when downloading one of the failed episodes? It displays the failed URL, where as your old version doesn't, and maybe the feed you are receiving has a different URL.

**Comment by v758** [comment]
v@v-desktop:~$ /usr/bin/gpodder -v
1603248711.618068 [gpodder.log] DEBUG: ==== gPodder starts up (ui=gtk) ===
1603248711.700410 [gpodder.util] WARNING: html5lib not found, falling back to HTMLParser
1603248711.721837 [gpodder.sync] WARNING: Could not find gpod
1603248711.722045 [gpodder.sync] WARNING: Could not find eyed3.mp3
1603248711.761296 [gpodder.extensions] DEBUG: Found extension "audio_converter" in /usr/share/gpodder/extensions/audio_converter.py
1603248711.762020 [gpodder.extensions] DEBUG: Found extension "concatenate_videos" in /usr/share/gpodder/extensions/concatenate_videos.py
1603248711.762215 [gpodder.extensions] DEBUG: Found extension "enqueue_in_mediaplayer" in /usr/share/gpodder/extensions/enqueue_in_mediaplayer.py
1603248711.762412 [gpodder.extensions] DEBUG: Found extension "episode_website_context_menu" in /usr/share/gpodder/extensions/episode_website_context_menu.py
1603248711.762627 [gpodder.extensions] DEBUG: Found extension "gtk_statusicon" in /usr/share/gpodder/extensions/gtk_statusicon.py
1603248711.762830 [gpodder.extensions] DEBUG: Found extension "minimize_on_start" in /usr/share/gpodder/extensions/minimize_on_start.py
1603248711.763021 [gpodder.extensions] DEBUG: Found extension "mpris-listener" in /usr/share/gpodder/extensions/mpris-listener.py
1603248711.763196 [gpodder.extensions] DEBUG: Found extension "normalize_audio" in /usr/share/gpodder/extensions/normalize_audio.py
1603248711.763347 [gpodder.extensions] DEBUG: Found extension "notification" in /usr/share/gpodder/extensions/notification.py
1603248711.764173 [gpodder.extensions] INFO: Module loaded: /usr/share/gpodder/extensions/notification.py
1603248711.764604 [gpodder.extensions] DEBUG: Found extension "notification-win32" in /usr/share/gpodder/extensions/notification-win32.py
1603248711.764820 [gpodder.extensions] DEBUG: Found extension "rename_download" in /usr/share/gpodder/extensions/rename_download.py
1603248711.765007 [gpodder.extensions] DEBUG: Found extension "rm_ogg_cover" in /usr/share/gpodder/extensions/rm_ogg_cover.py
1603248711.765207 [gpodder.extensions] DEBUG: Found extension "rockbox_convert2mp4" in /usr/share/gpodder/extensions/rockbox_convert2mp4.py
1603248711.765386 [gpodder.extensions] DEBUG: Found extension "rockbox_coverart" in /usr/share/gpodder/extensions/rockbox_coverart.py
1603248711.765565 [gpodder.extensions] DEBUG: Found extension "sonos" in /usr/share/gpodder/extensions/sonos.py
1603248711.765740 [gpodder.extensions] DEBUG: Found extension "tagging" in /usr/share/gpodder/extensions/tagging.py
1603248711.765932 [gpodder.extensions] DEBUG: Found extension "taskbar_progress" in /usr/share/gpodder/extensions/taskbar_progress.py
1603248711.766111 [gpodder.extensions] DEBUG: Found extension "ted_subtitles" in /usr/share/gpodder/extensions/ted_subtitles.py
1603248711.766304 [gpodder.extensions] DEBUG: Found extension "ubuntu_appindicator" in /usr/share/gpodder/extensions/ubuntu_appindicator.py
1603248711.766446 [gpodder.extensions] DEBUG: Found extension "ubuntu_unity" in /usr/share/gpodder/extensions/ubuntu_unity.py
1603248711.766620 [gpodder.extensions] DEBUG: Found extension "update_feeds_on_startup" in /usr/share/gpodder/extensions/update_feeds_on_startup.py
1603248711.766795 [gpodder.extensions] DEBUG: Found extension "video_converter" in /usr/share/gpodder/extensions/video_converter.py
1603248711.859107 [gpodder.dbsqlite] INFO: Loading podcasts
1603248711.861213 [gpodder.dbsqlite] DEBUG: Database opened.
1603248711.862105 [gpodder.dbsqlite] INFO: Loading episodes for podcast 1
1603248711.866465 [gpodder.dbsqlite] INFO: Loading episodes for podcast 2
1603248711.873343 [gpodder.dbsqlite] INFO: Loading episodes for podcast 3
1603248711.878706 [gpodder.dbsqlite] INFO: Loading episodes for podcast 4
1603248711.880457 [gpodder.dbsqlite] INFO: Loading episodes for podcast 5
1603248711.883288 [gpodder.dbsqlite] INFO: Loading episodes for podcast 6
1603248711.887440 [gpodder.dbsqlite] INFO: Loading episodes for podcast 7
1603248711.890494 [gpodder.dbsqlite] INFO: Loading episodes for podcast 8
1603248711.894338 [gpodder.dbsqlite] INFO: Loading episodes for podcast 9
1603248711.898508 [gpodder.dbsqlite] INFO: Loading episodes for podcast 10
1603248711.899315 [gpodder.dbsqlite] INFO: Loading episodes for podcast 11
1603248711.900034 [gpodder.dbsqlite] INFO: Loading episodes for podcast 12
1603248711.901054 [gpodder.dbsqlite] INFO: Loading episodes for podcast 13
1603248711.901990 [gpodder.dbsqlite] INFO: Loading episodes for podcast 14
1603248711.904888 [gpodder.dbsqlite] INFO: Loading episodes for podcast 15
1603248711.908284 [gpodder.dbsqlite] INFO: Loading episodes for podcast 16
1603248711.908504 [gpodder.dbsqlite] INFO: Loading episodes for podcast 17
1603248711.931816 [gpodder.my] INFO: Reloading settings.
1603248711.932238 [gpodder.util] DEBUG: run_in_background: <bound method UserAppsReader.read of <gpodder.gtkui.desktopfile.UserAppsReader object at 0x7f239e175a90>> (False)
1603248712.104024 [gpodder.util] DEBUG: run_in_background: <bound method gPodder.find_partial_downloads of <gpodder.gtkui.main.gPodder at /gui at 0x7f23b61adb70>> (False)
1603248712.104347 [gpodder.gtkui.main] DEBUG: Setting up auto update timer with interval 20.
1603248726.195825 [gpodder.gtkui.main] DEBUG: Downloading episode: The Truth Behind William McRaven's "Support" for the 2A
1603248726.246833 [gpodder.gtkui.main] INFO: All tasks have finished.
1603248726.284580 [gpodder.gtkui.main] INFO: All tasks have finished.
1603248726.322256 [gpodder.my] DEBUG: Storing 1 episode download actions
1603248726.324396 [gpodder.download] INFO: Starting new worker thread.
1603248726.324539 [gpodder.util] DEBUG: run_in_background: <bound method DownloadQueueWorker.run of MainThread> (False)
1603248726.324811 [gpodder.download] INFO: Starting new thread: Thread-3
1603248726.325926 [gpodder.download] INFO: Thread-3 is processing: The Truth Behind William McRaven's "Support" for the 2A
1603248726.787030 [gpodder.download] ERROR: [Errno socket error] [Errno -2] Name or service not known while downloading "The Truth Behind William McRaven's "Support" for the 2A": None
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1764, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.6/urllib/request.py", line 1974, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1923, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1434, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 952, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1764, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.6/urllib/request.py", line 1974, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1939, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1955, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python3.6/urllib/request.py", line 2143, in http_error_302
    headers, data)
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 238, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python3.6/urllib/request.py", line 1770, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.6/urllib/request.py", line 1764, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.6/urllib/request.py", line 1974, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1923, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1434, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 952, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno socket error] [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 766, in run
    self.tempname, reporthook=self.status_updated)
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 275, in retrieve_resume
    fp = self.open(url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1770, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.6/urllib/request.py", line 1764, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.6/urllib/request.py", line 1974, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1939, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1955, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python3.6/urllib/request.py", line 2143, in http_error_302
    headers, data)
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 238, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python3.6/urllib/request.py", line 1770, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.6/urllib/request.py", line 1764, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.6/urllib/request.py", line 1974, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1923, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1434, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 952, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno socket error] [Errno socket error] [Errno -2] Name or service not known
1603248726.790896 [gpodder.download] INFO: No more tasks for Thread-3 to carry out.
1603248727.835572 [gpodder.gtkui.main] INFO: All tasks have finished.
1603248727.874907 [gpodder.gtkui.main] INFO: All tasks have finished.

**Comment by auouymous** [comment]
You aren't running the latest version of gpodder (3.10.16). It won't fix the issue, unless it does, but it will tell me exactly which URL it is trying to download.

**Comment by v758** [comment]
the new version works fine..  i appreciate your help
