### ISSUE TITLE
Hangs when marking as old and finishing downloads

### ISSUE THREAD

**Issue by eunikolsky** [gpodder/gpodder#942]
Hi.
gPodder 3.10.17 (installed by `brew cask`) on OSX 10.14.6, MacBook Pro 2015 hangs in these cases (a similar issue is #932, but it could be [different](https://github.com/gpodder/gpodder/issues/932#issuecomment-752792349)):
* for ~3 seconds after marking some episodes as old in the "New episodes available" dialog; running with `-v` prints only this:

        (gPodder:59760): GdkPixbuf-CRITICAL **: 21:09:08.820: gdk_pixbuf_composite: assertion 'dest_y >= 0 && dest_y + dest_height <= dest->height' failed

        (gPodder:59760): GdkPixbuf-CRITICAL **: 21:09:08.936: gdk_pixbuf_composite: assertion 'dest_y >= 0 && dest_y + dest_height <= dest->height' failed

        (gPodder:59760): GdkPixbuf-CRITICAL **: 21:09:09.113: gdk_pixbuf_composite: assertion 'dest_y >= 0 && dest_y +  dest_height <= dest->height' failed

* for ~5 seconds after all downloads are finished; verbose log:

```
1609355377.349149 [gpodder.gtkui.main] DEBUG: Downloading episode: 386: Perilously Precocious Predictions
1609355377.349807 [gpodder.model] INFO: Setting download filename: 541c62a6-f115-40c9-8fa8-0ba0fcd57ca3.mp3
1609355377.529823 [gpodder.my] DEBUG: Storing 1 episode download actions
1609355377.530508 [gpodder.download] INFO: 1 tasks to do, can start at most 1 threads
1609355377.530589 [gpodder.download] INFO: Starting new worker thread.
1609355377.530662 [gpodder.util] DEBUG: run_in_background: <bound method DownloadQueueWorker.run of MainThread> (False)
1609355377.530869 [gpodder.download] INFO: Starting new thread: Thread-17
1609355377.531423 [gpodder.download] INFO: Thread-17 is processing: 386: Perilously Precocious Predictions
1609355377.531977 [gpodder.download] INFO: Downloading https://aphid.fireside.fm/d/1437767933/f31a453c-fa15-491f-8618-3f71f1d565e5/541c62a6-f115-40c9-8fa8-0ba0fcd57ca3.mp3
1609355378.716040 [gpodder.download] DEBUG: Updating file size of ~/gPodder/Downloads/LINUX Unplugged/541c62a6-f115-40c9-8fa8-0ba0fcd57ca3.mp3 to 42264482.0
1609355382.589011 [gpodder.download] INFO: Updating mime type: audio/mp3 => audio/mpeg
1609355382.589889 [gpodder.download] INFO: Download was redirected (http://media.fireside.fm/file/fireside-audio/podcasts/audio/f/f31a453c-fa15-491f-8618-3f71f1d565e5/episodes/5/541c62a6-f115-40c9-8fa8-0ba0fcd57ca3/541c62a6-f115-40c9-8fa8-0ba0fcd57ca3.mp3). New filename: 541c62a6-f115-40c9-8fa8-0ba0fcd57ca3.mp3
1609355382.591572 [gpodder.download] INFO: No more tasks for Thread-17 to carry out.

(gPodder:59760): GdkPixbuf-CRITICAL **: 21:09:47.920: gdk_pixbuf_composite: assertion 'dest_y >= 0 && dest_y + dest_height <= dest->height' failed

(gPodder:59760): GdkPixbuf-CRITICAL **: 21:09:48.044: gdk_pixbuf_composite: assertion 'dest_y >= 0 && dest_y + dest_height <= dest->height' failed

(gPodder:59760): GdkPixbuf-CRITICAL **: 21:09:48.215: gdk_pixbuf_composite: assertion 'dest_y >= 0 && dest_y + dest_height <= dest->height' failed
1609355388.383416 [gpodder.gtkui.main] INFO: All tasks have finished.

(gPodder:59760): GdkPixbuf-CRITICAL **: 21:09:52.522: gdk_pixbuf_composite: assertion 'dest_y >= 0 && dest_y + dest_height <= dest->height' failed

(gPodder:59760): GdkPixbuf-CRITICAL **: 21:09:52.653: gdk_pixbuf_composite: assertion 'dest_y >= 0 && dest_y + dest_height <= dest->height' failed

(gPodder:59760): GdkPixbuf-CRITICAL **: 21:09:52.833: gdk_pixbuf_composite: assertion 'dest_y >= 0 && dest_y + dest_height <= dest->height' failed
1609355393.000494 [gpodder.gtkui.main] INFO: All tasks have finished.
```

This has always been happening since I upgraded from gPodder 3.9.6 to 3.10.16 a few months ago. The download limit is one podcast at a time. I don't use gpodder.net.

My gPodder `Database` is quite old and big now: 26876928 bytes = 26 MB. I ran gPodder with a fresh home and a 440 kB `Database` and didn't see these hangs there, so in my case they seem to be due to database access. However SQLite should be very fast and 26 MB isn't that much.

```bash
$ sqlite3 ~/gPodder/Database 'pragma integrity_check;'
ok
```

How can I debug this?

_Extracted from https://github.com/gpodder/gpodder/issues/932#issuecomment-752733592_

**Comment by eunikolsky** [comment]
> This could be a separate hang issue or another clue to a shared cause. Did you import an OPML in the new home or did you just run gpodder without feeds? Running with the same feeds from an imported OPML would indicate the hang is an issue with large databases. How big is your gpodder.net file?

@auouymous In my fresh gPodder home test, I only added two feeds and gPodder worked fine.
Then I started from scratch, imported the OPML of my regular app (78 podcasts) and I see the same hangs again. The `Database` is 18841600 bytes.

My regular `gpodder.net` is 2301952 bytes.

When I just toggle the New status of a number of episodes the episodes list, there is no hang.

Even if there is an error downloading an episode, there is still a hang after that:
```
1609485477.721584 [gpodder.gtkui.main] DEBUG: Downloading episode: Чиним MacBook 2015, дешевый газ из Сибири, ваши комментарии
1609485477.722311 [gpodder.model] INFO: Setting download filename: ab_20151103.mp3
1609485477.726357 [gpodder.my] DEBUG: Storing 1 episode download actions
1609485477.728566 [gpodder.download] INFO: 1 tasks to do, can start at most 1 threads
1609485477.728665 [gpodder.download] INFO: Starting new worker thread.
1609485477.728734 [gpodder.util] DEBUG: run_in_background: <bound method DownloadQueueWorker.run of MainThread> (False)
1609485477.728941 [gpodder.download] INFO: Starting new thread: Thread-4
1609485477.729474 [gpodder.download] INFO: Thread-4 is processing: Чиним MacBook 2015, дешевый газ из Сибири, ваши комментарии
1609485477.729748 [gpodder.download] INFO: Downloading http://dev.insuma.de/~alex/podcasts/dolcewelle/ab_20151103.mp3
1609485478.035391 [gpodder.download] ERROR: HTTP 404 while downloading "Чиним MacBook 2015, дешевый газ из Сибири, ваши комментарии": Not Found
Traceback (most recent call last):
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages/gpodder/download.py", line 863, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages/gpodder/download.py", line 402, in retrieve_resume
    headers, real_url = downloader.retrieve_resume(url,
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages/gpodder/download.py", line 315, in retrieve_resume
    fp = self.open(url, data)
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/urllib/request.py", line 1790, in open
    return getattr(self, name)(url)
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/urllib/request.py", line 1968, in open_http
    return self._open_generic_http(http.client.HTTPConnection, url, data)
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/urllib/request.py", line 1962, in _open_generic_http
    return self.http_error(
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages/gpodder/download.py", line 246, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/urllib/request.py", line 1984, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File "/Applications/gPodder.app/Contents/Resources/lib/python3.8/site-packages/gpodder/download.py", line 259, in http_error_default
    raise gPodderDownloadHTTPError(url, errcode, errmsg)
gpodder.download.gPodderDownloadHTTPError: ('//dev.insuma.de/~alex/podcasts/dolcewelle/ab_20151103.mp3', 404, 'Not Found')
1609485478.039574 [gpodder.download] INFO: No more tasks for Thread-4 to carry out.
1609485484.760022 [gpodder.gtkui.main] INFO: All tasks have finished.
1609485490.232379 [gpodder.gtkui.main] INFO: All tasks have finished.
```

**Comment by eunikolsky** [comment]
These hangs also occur in gPodder 3.10.16 on Manjaro Linux in a VM. They are about twice shorter there even though it's in a virtual machine.

**Comment by eunikolsky** [comment]
gPodder 3.11.1 is much better! I don't see these delays anymore. Thanks!
