### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by wdenton** [gpodder/gpodder#981]
I pulled down updates from the last couple of weeks or more and now the list of subscriptions isn't showed in the left-hand side.  There's just "All episodes / from all podcasts," and if I click on that I see the list of all episodes as before, but the list of podcasts never shows up.

This error shows:

```
1616033777.283304 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/local/src/gpodder/src/gpodder/gtkui/app.py", line 189, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/usr/local/src/gpodder/src/gpodder/gtkui/main.py", line 91, in __init__
    BuilderWidget.__init__(self, None, _builder_expose={'app': app})
  File "/usr/local/src/gpodder/src/gpodder/gtkui/interface/common.py", line 36, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "/usr/local/src/gpodder/src/gpodder/gtkui/base.py", line 71, in __init__
    self.new()
  File "/usr/local/src/gpodder/src/gpodder/gtkui/main.py", line 220, in new
    self.update_podcast_list_model()
  File "/usr/local/src/gpodder/src/gpodder/gtkui/main.py", line 2328, in update_podcast_list_model
    self.podcast_list_model.set_channels(self.db, self.config, self.channels)
  File "/usr/local/src/gpodder/src/gpodder/gtkui/model.py", line 849, in set_channels
    for section, section_channels in groupby(sorted(channels, key=key_func), groupby_func):
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

This is on Ubuntu 18.04, with Python 3.6.9.

I used git bisect and narrowed it down to this:

`
297c10cc40feb62f102c6f573375b3ecd6356ff1 is the first bad commit
`

**Comment by auouymous** [comment]
I'm guessing you have `Use sections for podcast list` disabled. I get the error when I uncheck it, will try to get it fixed soon.
